// Generated by Framer (747ab96)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  forwardLoader,
  getFonts,
  getLoadingLazyAtYPosition,
  Image,
  Link,
  ResolveLinks,
  RichText,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useRouter,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import MainCTA from "https://framerusercontent.com/modules/Mmg6iZbsAE1MxmCR6acH/bgxZoNs9unBkO14TvOir/ve3uyNBsX.js";
const MainCTAFonts = getFonts(MainCTA);
const enabledGestures = { FvMMfTZpN: { hover: true } };
const cycleOrder = ["FvMMfTZpN", "Av5QcKBD4"];
const serializationHash = "framer-EiXEl";
const variantClassNames = {
  Av5QcKBD4: "framer-v-14jodmz",
  FvMMfTZpN: "framer-v-71hgf2",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg;
  }
  return undefined;
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  "Phone - Discount Button": "Av5QcKBD4",
  "Variant 1": "FvMMfTZpN",
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "FvMMfTZpN",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "FvMMfTZpN",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const router = useRouter();
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-71hgf2",
            className,
            classNames
          ),
          "data-border": true,
          "data-framer-name": "Variant 1",
          layoutDependency: layoutDependency,
          layoutId: "FvMMfTZpN",
          ref: refBinding,
          style: {
            "--border-bottom-width": "1px",
            "--border-color": "rgb(0, 0, 0)",
            "--border-left-width": "1px",
            "--border-right-width": "1px",
            "--border-style": "solid",
            "--border-top-width": "1px",
            backgroundColor: "rgb(255, 255, 255)",
            borderBottomLeftRadius: 20,
            borderBottomRightRadius: 20,
            borderTopLeftRadius: 20,
            borderTopRightRadius: 20,
            ...style,
          },
          variants: { Av5QcKBD4: { backgroundColor: "rgba(0, 0, 0, 0)" } },
          ...addPropertyOverrides(
            {
              "FvMMfTZpN-hover": { "data-framer-name": undefined },
              Av5QcKBD4: { "data-framer-name": "Phone - Discount Button" },
            },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-1s0wnhq",
              layoutDependency: layoutDependency,
              layoutId: "Hek0fMKVQ",
              children: /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-1icwkox",
                layoutDependency: layoutDependency,
                layoutId: "cj0GMn7WB",
                children: [
                  /*#__PURE__*/ _jsxs(motion.div, {
                    className: "framer-fhbwew",
                    layoutDependency: layoutDependency,
                    layoutId: "BEyXbyxsN",
                    children: [
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.h1, {
                            dir: "auto",
                            style: {
                              "--font-selector": "R0Y7TWFucm9wZS03MDA=",
                              "--framer-font-family":
                                '"Manrope", "Manrope Placeholder", sans-serif',
                              "--framer-font-size": "30px",
                              "--framer-font-weight": "700",
                              "--framer-letter-spacing": "-0.03em",
                              "--framer-text-alignment": "left",
                            },
                            children: "Invite Your Guests in 10 Minutes!",
                          }),
                        }),
                        className: "framer-mpvk5u",
                        fonts: ["GF;Manrope-700"],
                        layoutDependency: layoutDependency,
                        layoutId: "uvn3qpWAz",
                        style: {
                          "--framer-link-text-color": "rgb(0, 153, 255)",
                          "--framer-link-text-decoration": "underline",
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides(
                          {
                            Av5QcKBD4: {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsxs(motion.h1, {
                                  style: {
                                    "--font-selector": "R0Y7TWFucm9wZS03MDA=",
                                    "--framer-font-family":
                                      '"Manrope", "Manrope Placeholder", sans-serif',
                                    "--framer-font-size": "25px",
                                    "--framer-font-weight": "700",
                                    "--framer-letter-spacing": "-0.03em",
                                    "--framer-line-height": "1em",
                                    "--framer-text-alignment": "left",
                                  },
                                  children: [
                                    "Invite Your Guests ",
                                    /*#__PURE__*/ _jsx(motion.br, {}),
                                    "in 10 Minutes!",
                                  ],
                                }),
                              }),
                            },
                          },
                          baseVariant,
                          gestureVariant
                        ),
                      }),
                      /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-6akgo8",
                        layoutDependency: layoutDependency,
                        layoutId: "UxIyVOORN",
                        children: /*#__PURE__*/ _jsx(motion.div, {
                          className: "framer-gpn6pf",
                          layoutDependency: layoutDependency,
                          layoutId: "SYUAlNxIr",
                          children: /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx(motion.p, {
                                style: {
                                  "--font-selector": "RlM7TWFucm9wZS1tZWRpdW0=",
                                  "--framer-font-family":
                                    '"Manrope", "Manrope Placeholder", sans-serif',
                                  "--framer-font-open-type-features":
                                    "'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on",
                                  "--framer-font-size": "14px",
                                  "--framer-font-weight": "500",
                                  "--framer-letter-spacing": "-0.02em",
                                  "--framer-line-height": "1.6em",
                                  "--framer-text-alignment": "left",
                                  "--framer-text-color":
                                    "var(--extracted-r6o4lv, rgb(94, 94, 94))",
                                },
                                children: "Choose. Customise. Share.",
                              }),
                            }),
                            className: "framer-1iccavu",
                            fonts: ["FS;Manrope-medium"],
                            layoutDependency: layoutDependency,
                            layoutId: "rPjmNzOQB",
                            style: {
                              "--extracted-r6o4lv": "rgb(94, 94, 94)",
                              "--framer-link-text-color": "rgb(0, 153, 255)",
                              "--framer-link-text-decoration": "underline",
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true,
                          }),
                        }),
                      }),
                    ],
                  }),
                  /*#__PURE__*/ _jsx(ResolveLinks, {
                    links: [
                      {
                        href: { webPageId: "ftliO5er3" },
                        implicitPathVariables: undefined,
                      },
                      {
                        href: { webPageId: "ftliO5er3" },
                        implicitPathVariables: undefined,
                      },
                      {
                        href: { webPageId: "ftliO5er3" },
                        implicitPathVariables: undefined,
                      },
                    ],
                    children: (resolvedLinks) =>
                      /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 47,
                        y:
                          (componentViewport?.y || 0) +
                          30 +
                          0 +
                          0 +
                          0 +
                          0 +
                          70.4,
                        ...addPropertyOverrides(
                          {
                            Av5QcKBD4: {
                              y:
                                (componentViewport?.y || 0) +
                                20 +
                                0 +
                                0 +
                                0 +
                                0 +
                                62.4,
                            },
                          },
                          baseVariant,
                          gestureVariant
                        ),
                        children: /*#__PURE__*/ _jsx(
                          SmartComponentScopedContainer,
                          {
                            className: "framer-j6lcim-container",
                            layoutDependency: layoutDependency,
                            layoutId: "k2DA5bhq2-container",
                            nodeId: "k2DA5bhq2",
                            rendersWithMotion: true,
                            scopeId: "enDRnjdQs",
                            children: /*#__PURE__*/ _jsx(MainCTA, {
                              height: "100%",
                              id: "k2DA5bhq2",
                              layoutId: "k2DA5bhq2",
                              p7klC1ZHB: "Choose a template",
                              Ud5p4AQv5: resolvedLinks[0],
                              variant: matchVariant("Ix7kqPHgy"),
                              width: "100%",
                              ...addPropertyOverrides(
                                {
                                  "FvMMfTZpN-hover": {
                                    Ud5p4AQv5: resolvedLinks[2],
                                  },
                                  Av5QcKBD4: { Ud5p4AQv5: resolvedLinks[1] },
                                },
                                baseVariant,
                                gestureVariant
                              ),
                            }),
                          }
                        ),
                      }),
                  }),
                ],
              }),
            }),
            /*#__PURE__*/ _jsx(Link, {
              href: { webPageId: "ftliO5er3" },
              motionChild: true,
              nodeId: "RSdus1J6r",
              openInNewTab: false,
              scopeId: "enDRnjdQs",
              children: /*#__PURE__*/ _jsx(Image, {
                as: "a",
                background: {
                  alt: "",
                  fit: "fill",
                  intrinsicHeight: 768,
                  intrinsicWidth: 512,
                  loading: getLoadingLazyAtYPosition(
                    (componentViewport?.y || 0) +
                      (componentViewport?.height || 263) -
                      228
                  ),
                  pixelHeight: 1536,
                  pixelWidth: 1024,
                  sizes: "244px",
                  src: "https://framerusercontent.com/images/uvtfU55yBafBFhT3feL3T68KJs.png?width=1024&height=1536",
                  srcSet:
                    "https://framerusercontent.com/images/uvtfU55yBafBFhT3feL3T68KJs.png?scale-down-to=1024&width=1024&height=1536 682w,https://framerusercontent.com/images/uvtfU55yBafBFhT3feL3T68KJs.png?width=1024&height=1536 1024w",
                },
                className: "framer-svzb07 framer-lncyob",
                "data-framer-name": "Couple ad",
                layoutDependency: layoutDependency,
                layoutId: "RSdus1J6r",
                ...addPropertyOverrides(
                  {
                    "FvMMfTZpN-hover": {
                      background: {
                        alt: "",
                        fit: "fill",
                        intrinsicHeight: 768,
                        intrinsicWidth: 512,
                        loading: getLoadingLazyAtYPosition(
                          (componentViewport?.y || 0) +
                            (componentViewport?.height || 263) -
                            233
                        ),
                        pixelHeight: 1536,
                        pixelWidth: 1024,
                        sizes: "247px",
                        src: "https://framerusercontent.com/images/uvtfU55yBafBFhT3feL3T68KJs.png?width=1024&height=1536",
                        srcSet:
                          "https://framerusercontent.com/images/uvtfU55yBafBFhT3feL3T68KJs.png?scale-down-to=1024&width=1024&height=1536 682w,https://framerusercontent.com/images/uvtfU55yBafBFhT3feL3T68KJs.png?width=1024&height=1536 1024w",
                      },
                    },
                    Av5QcKBD4: {
                      background: {
                        alt: "",
                        fit: "fill",
                        intrinsicHeight: 768,
                        intrinsicWidth: 512,
                        loading: getLoadingLazyAtYPosition(
                          (componentViewport?.y || 0) + 121
                        ),
                        pixelHeight: 1536,
                        pixelWidth: 1024,
                        sizes: `calc(${
                          componentViewport?.width || "100vw"
                        } + 33px)`,
                        src: "https://framerusercontent.com/images/hQ7kq7nwm4rhjd0QsyrxKmHaUk.png?width=1024&height=1536",
                        srcSet:
                          "https://framerusercontent.com/images/hQ7kq7nwm4rhjd0QsyrxKmHaUk.png?scale-down-to=1024&width=1024&height=1536 682w,https://framerusercontent.com/images/hQ7kq7nwm4rhjd0QsyrxKmHaUk.png?width=1024&height=1536 1024w",
                      },
                    },
                  },
                  baseVariant,
                  gestureVariant
                ),
              }),
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-EiXEl.framer-lncyob, .framer-EiXEl .framer-lncyob { display: block; }",
  ".framer-EiXEl.framer-71hgf2 { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 92px; height: 263px; justify-content: flex-start; overflow: hidden; padding: 30px; position: relative; width: 635px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-EiXEl .framer-1s0wnhq { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 22px; height: 1px; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-EiXEl .framer-1icwkox { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-EiXEl .framer-fhbwew { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 2px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-EiXEl .framer-mpvk5u { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-EiXEl .framer-6akgo8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-EiXEl .framer-gpn6pf { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
  ".framer-EiXEl .framer-1iccavu { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-EiXEl .framer-j6lcim-container { flex: none; height: auto; position: relative; width: auto; }",
  ".framer-EiXEl .framer-svzb07 { aspect-ratio: 0.6666666666666666 / 1; bottom: -138px; flex: none; height: var(--framer-aspect-ratio-supported, 366px); overflow: visible; position: absolute; right: -15px; text-decoration: none; width: 244px; z-index: 1; }",
  ".framer-EiXEl.framer-v-14jodmz.framer-71hgf2 { cursor: unset; height: 383px; padding: 20px; width: 254px; }",
  ".framer-EiXEl.framer-v-14jodmz .framer-1s0wnhq { gap: 10px; }",
  ".framer-EiXEl.framer-v-14jodmz .framer-fhbwew { align-content: flex-start; align-items: flex-start; gap: 5px; }",
  ".framer-EiXEl.framer-v-14jodmz .framer-mpvk5u, .framer-EiXEl.framer-v-14jodmz .framer-gpn6pf { order: 0; }",
  ".framer-EiXEl.framer-v-14jodmz .framer-6akgo8 { gap: 4px; justify-content: flex-start; order: 1; }",
  ".framer-EiXEl.framer-v-14jodmz .framer-j6lcim-container { z-index: 2; }",
  ".framer-EiXEl.framer-v-14jodmz .framer-svzb07 { bottom: unset; height: var(--framer-aspect-ratio-supported, 431px); left: -7px; right: -26px; top: 121px; width: unset; }",
  ".framer-EiXEl.framer-v-71hgf2.hover .framer-svzb07 { height: var(--framer-aspect-ratio-supported, 371px); width: 247px; }",
  '.framer-EiXEl[data-border="true"]::after, .framer-EiXEl [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 263
 * @framerIntrinsicWidth 635
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"Av5QcKBD4":{"layout":["fixed","fixed"]},"bUuvpD26g":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerenDRnjdQs = withCSS(Component, css, "framer-EiXEl");
export default FramerenDRnjdQs;
FramerenDRnjdQs.displayName = "Discount button";
FramerenDRnjdQs.defaultProps = { height: 263, width: 635 };
addPropertyControls(FramerenDRnjdQs, {
  variant: {
    options: ["FvMMfTZpN", "Av5QcKBD4"],
    optionTitles: ["Variant 1", "Phone - Discount Button"],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(
  FramerenDRnjdQs,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Manrope",
          source: "google",
          style: "normal",
          uiFamilyName: "Manrope",
          url: "https://fonts.gstatic.com/s/manrope/v20/xn7_YHE41ni1AdIRqAuZuw1Bx9mbZk4aE-_A87jxeN7B.woff2",
          weight: "700",
        },
        {
          cssFamilyName: "Manrope",
          source: "fontshare",
          style: "normal",
          uiFamilyName: "Manrope",
          url: "https://framerusercontent.com/third-party-assets/fontshare/wf/BNWG6MUI4RTC6WEND2VPDH4MHMIVU3XZ/R5YXY5FMVG6PXU36GNEEA24MIPMEPGSM/CIM4KQCLZSMMLWPVH25IDDSTY4ENPHEY.woff2",
          weight: "500",
        },
      ],
    },
    ...MainCTAFonts,
  ],
  { supportsExplicitInterCodegen: true }
);
FramerenDRnjdQs.loader = {
  load: (props, context) => {
    const locale = context.locale;
    return Promise.allSettled([forwardLoader(MainCTA, {}, context)]);
  },
};
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerenDRnjdQs",
      slots: [],
      annotations: {
        framerImmutableVariables: "true",
        framerContractVersion: "1",
        framerColorSyntax: "true",
        framerComponentViewportWidth: "true",
        framerIntrinsicWidth: "635",
        framerDisplayContentsDiv: "false",
        framerAutoSizeImages: "true",
        framerIntrinsicHeight: "263",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"Av5QcKBD4":{"layout":["fixed","fixed"]},"bUuvpD26g":{"layout":["fixed","fixed"]}}}',
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./enDRnjdQs.map
