// Generated by Framer (6bbae76)
import { fontStore } from "framer";
fontStore.loadFonts([]);
export const fonts = [{ explicitInter: true, fonts: [] }];
export const css = [
  ".framer-qoU2h .framer-styles-preset-kmt2jv:not(.rich-text-wrapper), .framer-qoU2h .framer-styles-preset-kmt2jv.rich-text-wrapper a { --framer-link-current-text-decoration: underline; --framer-link-text-color: #000000; }",
];
export const className = "framer-qoU2h";
export const __FramerMetadata__ = {
  exports: {
    fonts: { type: "variable", annotations: { framerContractVersion: "1" } },
    className: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    css: { type: "variable", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
