// Generated by Framer (55d3d16)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  Link,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const cycleOrder = ["PeCAeFQ05", "L2SppujR3"];
const serializationHash = "framer-aYEnF";
const variantClassNames = {
  L2SppujR3: "framer-v-1ws6mst",
  PeCAeFQ05: "framer-v-149jzij",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const oYsZVBOnc = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  "Buy button - 1999": "L2SppujR3",
  "Variant 1": "PeCAeFQ05",
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, link, width, ...props }) => {
  return {
    ...props,
    oYsZVBOnc: link ?? props.oYsZVBOnc,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "PeCAeFQ05",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, oYsZVBOnc, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "PeCAeFQ05",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(Link, {
          href: oYsZVBOnc,
          motionChild: true,
          nodeId: "PeCAeFQ05",
          openInNewTab: true,
          scopeId: "LpQMHSxlP",
          children: /*#__PURE__*/ _jsxs(motion.a, {
            ...restProps,
            ...gestureHandlers,
            className: `${cx(
              scopingClassNames,
              "framer-149jzij",
              className,
              classNames
            )} framer-1hoq8tr`,
            "data-border": true,
            "data-framer-name": "Variant 1",
            layoutDependency: layoutDependency,
            layoutId: "PeCAeFQ05",
            ref: refBinding,
            style: {
              "--border-bottom-width": "1px",
              "--border-color": "rgb(34, 34, 34)",
              "--border-left-width": "1px",
              "--border-right-width": "1px",
              "--border-style": "solid",
              "--border-top-width": "1px",
              backdropFilter: "blur(8px)",
              backgroundColor: "rgba(255, 255, 255, 0.73)",
              borderBottomLeftRadius: 38.81,
              borderBottomRightRadius: 38.81,
              borderTopLeftRadius: 38.81,
              borderTopRightRadius: 38.81,
              WebkitBackdropFilter: "blur(8px)",
              ...style,
            },
            ...addPropertyOverrides(
              { L2SppujR3: { "data-framer-name": "Buy button - 1999" } },
              baseVariant,
              gestureVariant
            ),
            children: [
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-1bblg9p",
                layoutDependency: layoutDependency,
                layoutId: "J6ZPj5zBg",
                children: /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.p, {
                      style: {
                        "--font-selector": "R0Y7TWFucm9wZS02MDA=",
                        "--framer-font-family":
                          '"Manrope", "Manrope Placeholder", sans-serif',
                        "--framer-font-size": "22px",
                        "--framer-font-weight": "600",
                        "--framer-letter-spacing": "-0.02em",
                      },
                      children: "Buy Now ",
                    }),
                  }),
                  className: "framer-z9wsth",
                  "data-framer-name": "₹ 5999",
                  fonts: ["GF;Manrope-600"],
                  layoutDependency: layoutDependency,
                  layoutId: "XWLNgWw6I",
                  style: { "--framer-paragraph-spacing": "0px" },
                  verticalAlignment: "top",
                  withExternalLayout: true,
                }),
              }),
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-tabn6s",
                layoutDependency: layoutDependency,
                layoutId: "lGoWcJjeR",
                style: {
                  backgroundColor: "rgb(0, 0, 0)",
                  borderBottomLeftRadius: 90,
                  borderBottomRightRadius: 90,
                  borderTopLeftRadius: 90,
                  borderTopRightRadius: 90,
                },
                children: /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.p, {
                      dir: "auto",
                      style: {
                        "--font-selector": "R0Y7TWFucm9wZS02MDA=",
                        "--framer-font-family":
                          '"Manrope", "Manrope Placeholder", sans-serif',
                        "--framer-font-size": "18px",
                        "--framer-font-weight": "600",
                        "--framer-letter-spacing": "-0.02em",
                        "--framer-text-color":
                          "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                      },
                      children: "INR 3999",
                    }),
                  }),
                  className: "framer-1uyt5ek",
                  "data-framer-name": "₹ 5999",
                  fonts: ["GF;Manrope-600"],
                  layoutDependency: layoutDependency,
                  layoutId: "Phk6tH1ih",
                  style: {
                    "--extracted-r6o4lv": "rgb(255, 255, 255)",
                    "--framer-paragraph-spacing": "0px",
                  },
                  verticalAlignment: "top",
                  withExternalLayout: true,
                  ...addPropertyOverrides(
                    {
                      L2SppujR3: {
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            dir: "auto",
                            style: {
                              "--font-selector": "R0Y7TWFucm9wZS02MDA=",
                              "--framer-font-family":
                                '"Manrope", "Manrope Placeholder", sans-serif',
                              "--framer-font-size": "18px",
                              "--framer-font-weight": "600",
                              "--framer-letter-spacing": "-0.02em",
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                            },
                            children: "INR 1999",
                          }),
                        }),
                      },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                }),
              }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-aYEnF.framer-1hoq8tr, .framer-aYEnF .framer-1hoq8tr { display: block; }",
  ".framer-aYEnF.framer-149jzij { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 48px; justify-content: center; overflow: visible; padding: 0px 5px 0px 0px; position: relative; text-decoration: none; width: 246px; }",
  ".framer-aYEnF .framer-1bblg9p { align-content: center; align-items: center; display: flex; flex: 2 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px 0px 0px 12px; position: relative; width: 1px; }",
  ".framer-aYEnF .framer-z9wsth, .framer-aYEnF .framer-1uyt5ek { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-aYEnF .framer-tabn6s { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 40px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 131px; }",
  '.framer-aYEnF[data-border="true"]::after, .framer-aYEnF [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 48
 * @framerIntrinsicWidth 246
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"L2SppujR3":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"oYsZVBOnc":"link"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerLpQMHSxlP = withCSS(Component, css, "framer-aYEnF");
export default FramerLpQMHSxlP;
FramerLpQMHSxlP.displayName = "Floating button";
FramerLpQMHSxlP.defaultProps = { height: 48, width: 246 };
addPropertyControls(FramerLpQMHSxlP, {
  variant: {
    options: ["PeCAeFQ05", "L2SppujR3"],
    optionTitles: ["Variant 1", "Buy button - 1999"],
    title: "Variant",
    type: ControlType.Enum,
  },
  oYsZVBOnc: { title: "Link", type: ControlType.Link },
});
addFonts(
  FramerLpQMHSxlP,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Manrope",
          source: "google",
          style: "normal",
          uiFamilyName: "Manrope",
          url: "https://fonts.gstatic.com/s/manrope/v20/xn7_YHE41ni1AdIRqAuZuw1Bx9mbZk4jE-_A87jxeN7B.woff2",
          weight: "600",
        },
      ],
    },
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerLpQMHSxlP",
      slots: [],
      annotations: {
        framerIntrinsicWidth: "246",
        framerComponentViewportWidth: "true",
        framerColorSyntax: "true",
        framerVariables: '{"oYsZVBOnc":"link"}',
        framerIntrinsicHeight: "48",
        framerDisplayContentsDiv: "false",
        framerAutoSizeImages: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"L2SppujR3":{"layout":["fixed","fixed"]}}}',
        framerContractVersion: "1",
        framerImmutableVariables: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./LpQMHSxlP.map
