// Generated by Framer (0b247b4)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const cycleOrder = ["z089AuR5l", "wor1YeEME"];
const serializationHash = "framer-y7uVk";
const variantClassNames = {
  wor1YeEME: "framer-v-3hvfbh",
  z089AuR5l: "framer-v-1ga6uwi",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  "Desktop + tablet": "z089AuR5l",
  Phone: "wor1YeEME",
};
const getProps = ({ height, id, parents, relation, width, ...props }) => {
  return {
    ...props,
    fPwO_te5_: relation ?? props.fPwO_te5_ ?? "Daughter of",
    TUzHr1aqL: parents ?? props.TUzHr1aqL ?? "Mrs. Reena & Mr. Kamal Mittal,",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "z089AuR5l",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    fPwO_te5_,
    TUzHr1aqL,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "z089AuR5l",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1ga6uwi",
            className,
            classNames
          ),
          "data-framer-name": "Desktop + tablet",
          layoutDependency: layoutDependency,
          layoutId: "z089AuR5l",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            { wor1YeEME: { "data-framer-name": "Phone" } },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-ueptxf",
              layoutDependency: layoutDependency,
              layoutId: "eWJvZCRTg",
              children: [
                /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.p, {
                      style: {
                        "--font-selector":
                          "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                        "--framer-font-family":
                          '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                        "--framer-font-size": "30px",
                        "--framer-letter-spacing": "-0.05em",
                        "--framer-line-height": "100%",
                        "--framer-text-alignment": "center",
                        "--framer-text-color":
                          "var(--extracted-r6o4lv, rgb(230, 210, 255))",
                      },
                      children: "Daughter of",
                    }),
                  }),
                  className: "framer-1msl1i3",
                  "data-framer-name": "Daughter of...",
                  fonts: ["GF;Cormorant Upright-regular"],
                  layoutDependency: layoutDependency,
                  layoutId: "Hyh4e8iej",
                  style: {
                    "--extracted-r6o4lv": "rgb(230, 210, 255)",
                    "--framer-paragraph-spacing": "0px",
                  },
                  text: fPwO_te5_,
                  verticalAlignment: "top",
                  withExternalLayout: true,
                  ...addPropertyOverrides(
                    {
                      wor1YeEME: {
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            style: {
                              "--font-selector":
                                "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                              "--framer-font-family":
                                '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                              "--framer-font-size": "20px",
                              "--framer-letter-spacing": "-0.05em",
                              "--framer-line-height": "100%",
                              "--framer-text-alignment": "center",
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, rgb(230, 210, 255))",
                            },
                            children: "Daughter of",
                          }),
                        }),
                      },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                }),
                /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.p, {
                      style: {
                        "--font-selector":
                          "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                        "--framer-font-family":
                          '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                        "--framer-font-size": "30px",
                        "--framer-letter-spacing": "-0.05em",
                        "--framer-line-height": "100%",
                        "--framer-text-alignment": "center",
                        "--framer-text-color":
                          "var(--extracted-r6o4lv, rgb(230, 210, 255))",
                      },
                      children: "Mrs. Reena & Mr. Kamal Mittal,",
                    }),
                  }),
                  className: "framer-1ojbndv",
                  "data-framer-name": "Names",
                  fonts: ["GF;Cormorant Upright-regular"],
                  layoutDependency: layoutDependency,
                  layoutId: "R_HxhOYAW",
                  style: {
                    "--extracted-r6o4lv": "rgb(230, 210, 255)",
                    "--framer-paragraph-spacing": "0px",
                  },
                  text: TUzHr1aqL,
                  verticalAlignment: "top",
                  withExternalLayout: true,
                  ...addPropertyOverrides(
                    {
                      wor1YeEME: {
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            style: {
                              "--font-selector":
                                "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                              "--framer-font-family":
                                '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                              "--framer-font-size": "20px",
                              "--framer-letter-spacing": "-0.05em",
                              "--framer-line-height": "100%",
                              "--framer-text-alignment": "center",
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, rgb(230, 210, 255))",
                            },
                            children: "Mrs. Reena & Mr. Kamal Mittal,",
                          }),
                        }),
                      },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                }),
              ],
            }),
            /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.p, {
                  style: {
                    "--font-selector":
                      "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                    "--framer-font-family":
                      '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                    "--framer-font-size": "30px",
                    "--framer-letter-spacing": "-0.05em",
                    "--framer-line-height": "100%",
                    "--framer-text-alignment": "center",
                    "--framer-text-color":
                      "var(--extracted-r6o4lv, rgb(230, 210, 255))",
                  },
                  children: "On the following events",
                }),
              }),
              className: "framer-1190sm8",
              "data-framer-name":
                "You to join us in the wedding celebrations of",
              fonts: ["GF;Cormorant Upright-regular"],
              layoutDependency: layoutDependency,
              layoutId: "OKRN1MstQ",
              style: {
                "--extracted-r6o4lv": "rgb(230, 210, 255)",
                "--framer-paragraph-spacing": "0px",
              },
              verticalAlignment: "top",
              withExternalLayout: true,
              ...addPropertyOverrides(
                {
                  wor1YeEME: {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector":
                            "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                          "--framer-font-family":
                            '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                          "--framer-font-size": "20px",
                          "--framer-letter-spacing": "-0.05em",
                          "--framer-line-height": "100%",
                          "--framer-text-alignment": "center",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, rgb(230, 210, 255))",
                        },
                        children: "On the following events",
                      }),
                    }),
                  },
                },
                baseVariant,
                gestureVariant
              ),
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-y7uVk.framer-7p4lcf, .framer-y7uVk .framer-7p4lcf { display: block; }",
  ".framer-y7uVk.framer-1ga6uwi { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 46px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 32px 0px 32px 0px; position: relative; width: 1200px; }",
  ".framer-y7uVk .framer-ueptxf { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-y7uVk .framer-1msl1i3, .framer-y7uVk .framer-1ojbndv, .framer-y7uVk .framer-1190sm8 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 210
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"wor1YeEME":{"layout":["fixed","auto"]}}}
 * @framerVariables {"fPwO_te5_":"relation","TUzHr1aqL":"parents"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerJP1lk4ZGx = withCSS(Component, css, "framer-y7uVk");
export default FramerJP1lk4ZGx;
FramerJP1lk4ZGx.displayName = "Parent's names";
FramerJP1lk4ZGx.defaultProps = { height: 210, width: 1200 };
addPropertyControls(FramerJP1lk4ZGx, {
  variant: {
    options: ["z089AuR5l", "wor1YeEME"],
    optionTitles: ["Desktop + tablet", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
  fPwO_te5_: {
    defaultValue: "Daughter of",
    description: '"Son of" or "Daughter of"',
    displayTextArea: false,
    title: "Relation",
    type: ControlType.String,
  },
  TUzHr1aqL: {
    defaultValue: "Mrs. Reena & Mr. Kamal Mittal,",
    description:
      "Enter parent's names above\n\nFind more templates on ",
    displayTextArea: true,
    title: "Parents",
    type: ControlType.String,
  },
});
addFonts(
  FramerJP1lk4ZGx,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Cormorant Upright",
          source: "google",
          style: "normal",
          url: "https://fonts.gstatic.com/s/cormorantupright/v19/VuJrdM3I2Y35poFONtLdafkUCHw1y2vQjjTkeMnz.woff2",
          weight: "400",
        },
      ],
    },
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerJP1lk4ZGx",
      slots: [],
      annotations: {
        framerComponentViewportWidth: "true",
        framerVariables: '{"fPwO_te5_":"relation","TUzHr1aqL":"parents"}',
        framerDisplayContentsDiv: "false",
        framerImmutableVariables: "true",
        framerIntrinsicWidth: "1200",
        framerIntrinsicHeight: "210",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"wor1YeEME":{"layout":["fixed","auto"]}}}',
        framerAutoSizeImages: "true",
        framerColorSyntax: "true",
        framerContractVersion: "1",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./JP1lk4ZGx.map
