// Generated by Framer (0b247b4)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const cycleOrder = ["uhz8VnBzv", "S9MRRk9Jl"];
const serializationHash = "framer-dRcD6";
const variantClassNames = {
  S9MRRk9Jl: "framer-v-c8lky7",
  uhz8VnBzv: "framer-v-2fnoyj",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  "Desktop + tablet": "uhz8VnBzv",
  Phone: "S9MRRk9Jl",
};
const getProps = ({ height, id, message, width, ...props }) => {
  return {
    ...props,
    IbIM0E4Jn:
      message ??
      props.IbIM0E4Jn ??
      "We are both so delighted that you are able to join us in celebrating what we hope will be one of the happiest days of our lives. The affection shown to us by so many people since our roka has been incredibly moving, and has touched us both deeply. We would like to take this opportunity to thank everyone most sincerely for their kindness.We are looking forward to see you at the wedding.",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "uhz8VnBzv",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, IbIM0E4Jn, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "uhz8VnBzv",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-2fnoyj",
            className,
            classNames
          ),
          "data-framer-name": "Desktop + tablet",
          layoutDependency: layoutDependency,
          layoutId: "uhz8VnBzv",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            { S9MRRk9Jl: { "data-framer-name": "Phone" } },
            baseVariant,
            gestureVariant
          ),
          children: /*#__PURE__*/ _jsx(motion.div, {
            className: "framer-riuc69",
            layoutDependency: layoutDependency,
            layoutId: "MBAJY8o3u",
            children: /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsxs(motion.p, {
                  style: {
                    "--font-selector": "R0Y7Q29ybW9yYW50IFVwcmlnaHQtNTAw",
                    "--framer-font-family":
                      '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                    "--framer-font-size": "30px",
                    "--framer-font-weight": "500",
                    "--framer-line-height": "110.1%",
                    "--framer-text-alignment": "center",
                    "--framer-text-color":
                      "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                  },
                  children: [
                    "We are both so delighted that you are able to join us in celebrating what we hope will be one of the happiest days of our lives. The affection shown to us by so many people since our roka has been incredibly moving, and has touched us both deeply. We would like to take this opportunity to thank everyone most sincerely for their kindness.",
                    /*#__PURE__*/ _jsxs(motion.span, {
                      style: {
                        "--framer-text-color":
                          "var(--extracted-1w3ko1f, rgb(255, 17, 0))",
                      },
                      children: [
                        /*#__PURE__*/ _jsx(motion.br, {}),
                        /*#__PURE__*/ _jsx(motion.br, {}),
                      ],
                    }),
                    "We are looking forward to see you at the wedding.",
                  ],
                }),
              }),
              className: "framer-u7ok4r",
              "data-framer-name": "Message",
              fonts: ["GF;Cormorant Upright-500"],
              layoutDependency: layoutDependency,
              layoutId: "clhdql29j",
              style: {
                "--extracted-1w3ko1f": "rgb(255, 17, 0)",
                "--extracted-r6o4lv": "rgb(255, 255, 255)",
                "--framer-paragraph-spacing": "0px",
              },
              text: IbIM0E4Jn,
              verticalAlignment: "top",
              withExternalLayout: true,
              ...addPropertyOverrides(
                {
                  S9MRRk9Jl: {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsxs(motion.p, {
                        style: {
                          "--font-selector": "R0Y7Q29ybW9yYW50IFVwcmlnaHQtNTAw",
                          "--framer-font-family":
                            '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                          "--framer-font-size": "20px",
                          "--framer-font-weight": "500",
                          "--framer-line-height": "110.1%",
                          "--framer-text-alignment": "center",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                        },
                        children: [
                          "We are both so delighted that you are able to join us in celebrating what we hope will be one of the happiest days of our lives. The affection shown to us by so many people since our roka has been incredibly moving, and has touched us both deeply. We would like to take this opportunity to thank everyone most sincerely for their kindness.",
                          /*#__PURE__*/ _jsx(motion.br, {}),
                          /*#__PURE__*/ _jsx(motion.br, {}),
                          "We are looking forward to see you at the wedding.",
                        ],
                      }),
                    }),
                  },
                },
                baseVariant,
                gestureVariant
              ),
            }),
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-dRcD6.framer-1oo5jbk, .framer-dRcD6 .framer-1oo5jbk { display: block; }",
  ".framer-dRcD6.framer-2fnoyj { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 600px; }",
  ".framer-dRcD6 .framer-riuc69 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-dRcD6 .framer-u7ok4r { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 264
 * @framerIntrinsicWidth 600
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"S9MRRk9Jl":{"layout":["fixed","auto"]}}}
 * @framerVariables {"IbIM0E4Jn":"message"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerTfVJaka8I = withCSS(Component, css, "framer-dRcD6");
export default FramerTfVJaka8I;
FramerTfVJaka8I.displayName = "Message";
FramerTfVJaka8I.defaultProps = { height: 264, width: 600 };
addPropertyControls(FramerTfVJaka8I, {
  variant: {
    options: ["uhz8VnBzv", "S9MRRk9Jl"],
    optionTitles: ["Desktop + tablet", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
  IbIM0E4Jn: {
    defaultValue:
      "We are both so delighted that you are able to join us in celebrating what we hope will be one of the happiest days of our lives. The affection shown to us by so many people since our roka has been incredibly moving, and has touched us both deeply. We would like to take this opportunity to thank everyone most sincerely for their kindness.We are looking forward to see you at the wedding.",
    description:
      "Write your custom couple's message above\n\nFind more templates on ",
    displayTextArea: true,
    title: "Message",
    type: ControlType.String,
  },
});
addFonts(
  FramerTfVJaka8I,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Cormorant Upright",
          source: "google",
          style: "normal",
          url: "https://fonts.gstatic.com/s/cormorantupright/v19/VuJudM3I2Y35poFONtLdafkUCHw1y1MhpxDpU9X6RPzQ.woff2",
          weight: "500",
        },
      ],
    },
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerTfVJaka8I",
      slots: [],
      annotations: {
        framerIntrinsicWidth: "600",
        framerColorSyntax: "true",
        framerAutoSizeImages: "true",
        framerContractVersion: "1",
        framerDisplayContentsDiv: "false",
        framerImmutableVariables: "true",
        framerVariables: '{"IbIM0E4Jn":"message"}',
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"S9MRRk9Jl":{"layout":["fixed","auto"]}}}',
        framerIntrinsicHeight: "264",
        framerComponentViewportWidth: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./TfVJaka8I.map
