// Generated by Framer (0b247b4)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const cycleOrder = ["GL0XiSXPn", "UqNwCmL3c"];
const serializationHash = "framer-2mBa6";
const variantClassNames = {
  GL0XiSXPn: "framer-v-92bqda",
  UqNwCmL3c: "framer-v-1ku5gjx",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  "Desktop + tablet": "GL0XiSXPn",
  Phone: "UqNwCmL3c",
};
const getProps = ({ height, id, name1, name2, width, ...props }) => {
  return {
    ...props,
    jKoV97PFE: name2 ?? props.jKoV97PFE ?? "Kanika",
    TGnFtroN5: name1 ?? props.TGnFtroN5 ?? "Abhishek",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "GL0XiSXPn",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    TGnFtroN5,
    jKoV97PFE,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "GL0XiSXPn",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-92bqda",
            className,
            classNames
          ),
          "data-framer-name": "Desktop + tablet",
          layoutDependency: layoutDependency,
          layoutId: "GL0XiSXPn",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            { UqNwCmL3c: { "data-framer-name": "Phone" } },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.p, {
                  style: {
                    "--font-selector":
                      "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                    "--framer-font-family":
                      '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                    "--framer-font-size": "150px",
                    "--framer-line-height": "190.1%",
                    "--framer-text-alignment": "center",
                    "--framer-text-color":
                      "var(--extracted-r6o4lv, rgb(230, 210, 255))",
                  },
                  children: "Abhishek",
                }),
              }),
              className: "framer-1xeng68",
              "data-framer-name": "Aaditya",
              fonts: ["GF;Cormorant Upright-regular"],
              layoutDependency: layoutDependency,
              layoutId: "AC8enpkTq",
              style: {
                "--extracted-r6o4lv": "rgb(230, 210, 255)",
                "--framer-paragraph-spacing": "0px",
              },
              text: TGnFtroN5,
              verticalAlignment: "top",
              withExternalLayout: true,
              ...addPropertyOverrides(
                {
                  UqNwCmL3c: {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector":
                            "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                          "--framer-font-family":
                            '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                          "--framer-font-size": "70px",
                          "--framer-line-height": "190.1%",
                          "--framer-text-alignment": "center",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, rgb(230, 210, 255))",
                        },
                        children: "Abhishek",
                      }),
                    }),
                  },
                },
                baseVariant,
                gestureVariant
              ),
            }),
            /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.p, {
                  style: {
                    "--font-selector":
                      "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                    "--framer-font-family":
                      '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                    "--framer-font-size": "156px",
                    "--framer-line-height": "110%",
                    "--framer-text-color":
                      "var(--extracted-r6o4lv, rgb(230, 210, 255))",
                  },
                  children: "&",
                }),
              }),
              className: "framer-3lgz0f",
              "data-framer-name": "&",
              fonts: ["GF;Cormorant Upright-regular"],
              layoutDependency: layoutDependency,
              layoutId: "SjMYqsNw1",
              style: {
                "--extracted-r6o4lv": "rgb(230, 210, 255)",
                "--framer-paragraph-spacing": "0px",
              },
              verticalAlignment: "top",
              withExternalLayout: true,
              ...addPropertyOverrides(
                {
                  UqNwCmL3c: {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector":
                            "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                          "--framer-font-family":
                            '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                          "--framer-font-size": "70px",
                          "--framer-line-height": "110%",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, rgb(230, 210, 255))",
                        },
                        children: "&",
                      }),
                    }),
                  },
                },
                baseVariant,
                gestureVariant
              ),
            }),
            /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.p, {
                  style: {
                    "--font-selector": "R0Y7Q29ybW9yYW50LXJlZ3VsYXI=",
                    "--framer-font-family":
                      '"Cormorant", "Cormorant Placeholder", serif',
                    "--framer-font-size": "150px",
                    "--framer-line-height": "60.1%",
                    "--framer-text-alignment": "center",
                    "--framer-text-color":
                      "var(--extracted-r6o4lv, rgb(230, 210, 255))",
                  },
                  children: "Kanika",
                }),
              }),
              className: "framer-2fhrb9",
              "data-framer-name": "Veera",
              fonts: ["GF;Cormorant-regular"],
              layoutDependency: layoutDependency,
              layoutId: "uhQ8K4auN",
              style: {
                "--extracted-r6o4lv": "rgb(230, 210, 255)",
                "--framer-paragraph-spacing": "0px",
              },
              text: jKoV97PFE,
              verticalAlignment: "top",
              withExternalLayout: true,
              ...addPropertyOverrides(
                {
                  UqNwCmL3c: {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector": "R0Y7Q29ybW9yYW50LXJlZ3VsYXI=",
                          "--framer-font-family":
                            '"Cormorant", "Cormorant Placeholder", serif',
                          "--framer-font-size": "70px",
                          "--framer-line-height": "60.1%",
                          "--framer-text-alignment": "center",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, rgb(230, 210, 255))",
                        },
                        children: "Kanika",
                      }),
                    }),
                  },
                },
                baseVariant,
                gestureVariant
              ),
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-2mBa6.framer-l2wunz, .framer-2mBa6 .framer-l2wunz { display: block; }",
  ".framer-2mBa6.framer-92bqda { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1200px; }",
  ".framer-2mBa6 .framer-1xeng68 { flex: none; height: 210px; position: relative; white-space: pre; width: auto; }",
  ".framer-2mBa6 .framer-3lgz0f { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-2mBa6 .framer-2fhrb9 { flex: none; height: 186px; position: relative; white-space: pre; width: auto; }",
  ".framer-2mBa6.framer-v-1ku5gjx .framer-1xeng68 { height: 95px; }",
  ".framer-2mBa6.framer-v-1ku5gjx .framer-2fhrb9 { height: 63px; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 567.5
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"UqNwCmL3c":{"layout":["fixed","auto"]}}}
 * @framerVariables {"TGnFtroN5":"name1","jKoV97PFE":"name2"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerTY5o_js_2 = withCSS(Component, css, "framer-2mBa6");
export default FramerTY5o_js_2;
FramerTY5o_js_2.displayName = "Couple's names 2";
FramerTY5o_js_2.defaultProps = { height: 567.5, width: 1200 };
addPropertyControls(FramerTY5o_js_2, {
  variant: {
    options: ["GL0XiSXPn", "UqNwCmL3c"],
    optionTitles: ["Desktop + tablet", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
  TGnFtroN5: {
    defaultValue: "Abhishek",
    description:
      "Enter groom or bride's name above\n\nFind more templates on ",
    displayTextArea: false,
    title: "Name 1",
    type: ControlType.String,
  },
  jKoV97PFE: {
    defaultValue: "Kanika",
    description:
      "Enter groom or bride's name above\n\nFind more templates on ",
    displayTextArea: false,
    title: "Name 2",
    type: ControlType.String,
  },
});
addFonts(
  FramerTY5o_js_2,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Cormorant Upright",
          source: "google",
          style: "normal",
          url: "https://fonts.gstatic.com/s/cormorantupright/v19/VuJrdM3I2Y35poFONtLdafkUCHw1y2vQjjTkeMnz.woff2",
          weight: "400",
        },
        {
          family: "Cormorant",
          source: "google",
          style: "normal",
          url: "https://fonts.gstatic.com/s/cormorant/v24/H4c2BXOCl9bbnla_nHIA47NMUjsNbCVrFhFTQ7Fg7A2uwYs.woff2",
          weight: "400",
        },
      ],
    },
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerTY5o_js_2",
      slots: [],
      annotations: {
        framerImmutableVariables: "true",
        framerColorSyntax: "true",
        framerComponentViewportWidth: "true",
        framerIntrinsicHeight: "567.5",
        framerContractVersion: "1",
        framerDisplayContentsDiv: "false",
        framerIntrinsicWidth: "1200",
        framerAutoSizeImages: "true",
        framerVariables: '{"TGnFtroN5":"name1","jKoV97PFE":"name2"}',
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"UqNwCmL3c":{"layout":["fixed","auto"]}}}',
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./TY5o_js_2.map
