// Generated by Framer (0b247b4)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getLoadingLazyAtYPosition,
  Image,
  Link,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const cycleOrder = ["fZ4Ix4Xet", "lAXr04cRF"];
const serializationHash = "framer-DMmux";
const variantClassNames = {
  fZ4Ix4Xet: "framer-v-gk1ruy",
  lAXr04cRF: "framer-v-1j778hb",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = { Desktop: "fZ4Ix4Xet", Phone: "lAXr04cRF" };
const getProps = ({ height, id, location, width, ...props }) => {
  return {
    ...props,
    mbbsTWHqX: location ?? props.mbbsTWHqX,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "fZ4Ix4Xet",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, mbbsTWHqX, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "fZ4Ix4Xet",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(Image, {
          ...restProps,
          ...gestureHandlers,
          background: {
            alt: "",
            fit: "stretch",
            loading: getLoadingLazyAtYPosition(componentViewport?.y || 0),
            pixelHeight: 1024,
            pixelWidth: 1024,
            positionX: "center",
            positionY: "center",
            sizes: componentViewport?.width || "100vw",
            src: "https://framerusercontent.com/images/eJP5CWHTXk7vpBFwgKNnevhWwso.png?width=1024&height=1024",
            srcSet:
              "https://framerusercontent.com/images/eJP5CWHTXk7vpBFwgKNnevhWwso.png?scale-down-to=512&width=1024&height=1024 512w,https://framerusercontent.com/images/eJP5CWHTXk7vpBFwgKNnevhWwso.png?width=1024&height=1024 1024w",
          },
          className: cx(
            scopingClassNames,
            "framer-gk1ruy",
            className,
            classNames
          ),
          "data-framer-name": "Desktop",
          layoutDependency: layoutDependency,
          layoutId: "fZ4Ix4Xet",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            { lAXr04cRF: { "data-framer-name": "Phone" } },
            baseVariant,
            gestureVariant
          ),
          children: /*#__PURE__*/ _jsxs(motion.div, {
            className: "framer-1el3ec7",
            layoutDependency: layoutDependency,
            layoutId: "ArX6lCbeM",
            children: [
              /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsxs(React.Fragment, {
                  children: [
                    /*#__PURE__*/ _jsx(motion.p, {
                      style: {
                        "--font-selector":
                          "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                        "--framer-font-family":
                          '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                        "--framer-font-size": "90px",
                        "--framer-line-height": "64%",
                        "--framer-text-alignment": "center",
                        "--framer-text-color":
                          "var(--extracted-r6o4lv, rgb(78, 52, 116))",
                      },
                      children: "See the",
                    }),
                    /*#__PURE__*/ _jsx(motion.p, {
                      style: {
                        "--font-selector":
                          "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                        "--framer-font-family":
                          '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                        "--framer-font-size": "90px",
                        "--framer-line-height": "64%",
                        "--framer-text-alignment": "center",
                        "--framer-text-color":
                          "var(--extracted-2gxw0f, rgb(78, 52, 116))",
                      },
                      children: "route",
                    }),
                  ],
                }),
                className: "framer-h9wqbf",
                "data-framer-name": "See the route",
                fonts: ["GF;Cormorant Upright-regular"],
                layoutDependency: layoutDependency,
                layoutId: "oOnTTL7sl",
                style: {
                  "--extracted-2gxw0f": "rgb(78, 52, 116)",
                  "--extracted-r6o4lv": "rgb(78, 52, 116)",
                  "--framer-paragraph-spacing": "0px",
                },
                verticalAlignment: "top",
                withExternalLayout: true,
                ...addPropertyOverrides(
                  {
                    lAXr04cRF: {
                      children: /*#__PURE__*/ _jsxs(React.Fragment, {
                        children: [
                          /*#__PURE__*/ _jsx(motion.p, {
                            style: {
                              "--font-selector":
                                "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                              "--framer-font-family":
                                '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                              "--framer-font-size": "120px",
                              "--framer-line-height": "64%",
                              "--framer-text-alignment": "center",
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, rgb(78, 52, 116))",
                            },
                            children: "See the",
                          }),
                          /*#__PURE__*/ _jsx(motion.p, {
                            style: {
                              "--font-selector":
                                "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                              "--framer-font-family":
                                '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                              "--framer-font-size": "120px",
                              "--framer-line-height": "64%",
                              "--framer-text-alignment": "center",
                              "--framer-text-color":
                                "var(--extracted-2gxw0f, rgb(78, 52, 116))",
                            },
                            children: "route",
                          }),
                        ],
                      }),
                    },
                  },
                  baseVariant,
                  gestureVariant
                ),
              }),
              /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    style: {
                      "--font-selector": "R0Y7Q29ybW9yYW50LXJlZ3VsYXI=",
                      "--framer-font-family":
                        '"Cormorant", "Cormorant Placeholder", serif',
                      "--framer-font-size": "17px",
                      "--framer-text-alignment": "center",
                      "--framer-text-color":
                        "var(--extracted-r6o4lv, rgb(78, 52, 116))",
                    },
                    children: "Click to open the map",
                  }),
                }),
                className: "framer-45zct4",
                "data-framer-name": "Click to open the map",
                fonts: ["GF;Cormorant-regular"],
                layoutDependency: layoutDependency,
                layoutId: "dAFY1Xhp3",
                style: {
                  "--extracted-r6o4lv": "rgb(78, 52, 116)",
                  "--framer-paragraph-spacing": "0px",
                },
                verticalAlignment: "top",
                withExternalLayout: true,
              }),
              /*#__PURE__*/ _jsx(Link, {
                href: mbbsTWHqX,
                motionChild: true,
                nodeId: "lLSpy50DJ",
                openInNewTab: false,
                scopeId: "jQWVylDLi",
                children: /*#__PURE__*/ _jsx(Image, {
                  as: "a",
                  background: {
                    alt: "",
                    fit: "fill",
                    loading: getLoadingLazyAtYPosition(
                      (componentViewport?.y || 0) +
                        ((componentViewport?.height || 767.5) *
                          0.5146579804560263 -
                          98) +
                        0 +
                        408
                    ),
                    pixelHeight: 1536,
                    pixelWidth: 1024,
                    sizes: "76px",
                    src: "https://framerusercontent.com/images/iS3ts4kTWQdx3wHxV4eRWhlM6GY.png?width=1024&height=1536",
                    srcSet:
                      "https://framerusercontent.com/images/iS3ts4kTWQdx3wHxV4eRWhlM6GY.png?scale-down-to=1024&width=1024&height=1536 682w,https://framerusercontent.com/images/iS3ts4kTWQdx3wHxV4eRWhlM6GY.png?width=1024&height=1536 1024w",
                  },
                  className: "framer-okxxtm framer-y6cuof",
                  "data-framer-name":
                    "ChatGPT Image Aug 20, 2025 at 01_02_57 PM 1",
                  layoutDependency: layoutDependency,
                  layoutId: "lLSpy50DJ",
                  ...addPropertyOverrides(
                    {
                      lAXr04cRF: {
                        background: {
                          alt: "",
                          fit: "fill",
                          loading: getLoadingLazyAtYPosition(
                            (componentViewport?.y || 0) +
                              ((componentViewport?.height || 767.5) *
                                0.5407166123778504 -
                                98) +
                              0 +
                              504
                          ),
                          pixelHeight: 1536,
                          pixelWidth: 1024,
                          sizes: "76px",
                          src: "https://framerusercontent.com/images/iS3ts4kTWQdx3wHxV4eRWhlM6GY.png?width=1024&height=1536",
                          srcSet:
                            "https://framerusercontent.com/images/iS3ts4kTWQdx3wHxV4eRWhlM6GY.png?scale-down-to=1024&width=1024&height=1536 682w,https://framerusercontent.com/images/iS3ts4kTWQdx3wHxV4eRWhlM6GY.png?width=1024&height=1536 1024w",
                        },
                      },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                }),
              }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-DMmux.framer-y6cuof, .framer-DMmux .framer-y6cuof { display: block; }",
  ".framer-DMmux.framer-gk1ruy { height: 768px; position: relative; width: 718px; }",
  ".framer-DMmux .framer-1el3ec7 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 28px; height: 196px; justify-content: center; left: calc(50.00000000000002% - 170px / 2); overflow: visible; padding: 0px; position: absolute; top: calc(51.465798045602625% - 196px / 2); width: 170px; }",
  ".framer-DMmux .framer-h9wqbf { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 321px; word-break: break-word; word-wrap: break-word; }",
  ".framer-DMmux .framer-45zct4 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 170px; word-break: break-word; word-wrap: break-word; }",
  ".framer-DMmux .framer-okxxtm { aspect-ratio: 0.6666666495843672 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 114px); position: relative; text-decoration: none; width: 76px; }",
  ".framer-DMmux.framer-v-1j778hb.framer-gk1ruy { aspect-ratio: 0.9355346948861287 / 1; height: var(--framer-aspect-ratio-supported, 768px); }",
  ".framer-DMmux.framer-v-1j778hb .framer-1el3ec7 { top: calc(54.07166123778504% - 196px / 2); }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 767.5
 * @framerIntrinsicWidth 718
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"lAXr04cRF":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"mbbsTWHqX":"location"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerjQWVylDLi = withCSS(Component, css, "framer-DMmux");
export default FramerjQWVylDLi;
FramerjQWVylDLi.displayName = "See the route";
FramerjQWVylDLi.defaultProps = { height: 767.5, width: 718 };
addPropertyControls(FramerjQWVylDLi, {
  variant: {
    options: ["fZ4Ix4Xet", "lAXr04cRF"],
    optionTitles: ["Desktop", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
  mbbsTWHqX: {
    description:
      "Enter the link of venue location above.\n\nFind more templates on ",
    title: "Location",
    type: ControlType.Link,
  },
});
addFonts(
  FramerjQWVylDLi,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Cormorant Upright",
          source: "google",
          style: "normal",
          url: "https://fonts.gstatic.com/s/cormorantupright/v19/VuJrdM3I2Y35poFONtLdafkUCHw1y2vQjjTkeMnz.woff2",
          weight: "400",
        },
        {
          family: "Cormorant",
          source: "google",
          style: "normal",
          url: "https://fonts.gstatic.com/s/cormorant/v24/H4c2BXOCl9bbnla_nHIA47NMUjsNbCVrFhFTQ7Fg7A2uwYs.woff2",
          weight: "400",
        },
      ],
    },
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerjQWVylDLi",
      slots: [],
      annotations: {
        framerVariables: '{"mbbsTWHqX":"location"}',
        framerAutoSizeImages: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"lAXr04cRF":{"layout":["fixed","fixed"]}}}',
        framerImmutableVariables: "true",
        framerDisplayContentsDiv: "false",
        framerIntrinsicWidth: "718",
        framerContractVersion: "1",
        framerColorSyntax: "true",
        framerComponentViewportWidth: "true",
        framerIntrinsicHeight: "767.5",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./jQWVylDLi.map
