// Generated by Framer (0b247b4)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getLoadingLazyAtYPosition,
  Image,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const cycleOrder = ["J1jpdeNFp", "NhYDSHdkA"];
const serializationHash = "framer-YJnEI";
const variantClassNames = {
  J1jpdeNFp: "framer-v-ws2yct",
  NhYDSHdkA: "framer-v-7i446v",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value;
  }
  return typeof value === "string" ? { src: value } : undefined;
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = { Desktop: "J1jpdeNFp", Phone: "NhYDSHdkA" };
const getProps = ({ height, icon, id, info, title, width, ...props }) => {
  return {
    ...props,
    PrrSJxMUh:
      info ??
      props.PrrSJxMUh ??
      "While posting photos on social media please use the hashtag - #Abkan",
    PVzPSjchM: title ?? props.PVzPSjchM ?? "Hashtag",
    RXLhSfcG1: icon ??
      props.RXLhSfcG1 ?? {
        alt: "",
        pixelHeight: 1024,
        pixelWidth: 1024,
        src: "https://framerusercontent.com/images/WtUtKiZfYvFe6ob7yo3S6KaxT4.png?scale-down-to=512&width=1024&height=1024",
        srcSet:
          "https://framerusercontent.com/images/WtUtKiZfYvFe6ob7yo3S6KaxT4.png?scale-down-to=512&width=1024&height=1024 512w,https://framerusercontent.com/images/WtUtKiZfYvFe6ob7yo3S6KaxT4.png?width=1024&height=1024 1024w",
      },
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "J1jpdeNFp",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    RXLhSfcG1,
    PVzPSjchM,
    PrrSJxMUh,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "J1jpdeNFp",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-ws2yct",
            className,
            classNames
          ),
          "data-framer-name": "Desktop",
          layoutDependency: layoutDependency,
          layoutId: "J1jpdeNFp",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            { NhYDSHdkA: { "data-framer-name": "Phone" } },
            baseVariant,
            gestureVariant
          ),
          children: /*#__PURE__*/ _jsxs(motion.div, {
            className: "framer-1nqscw9",
            layoutDependency: layoutDependency,
            layoutId: "eoKkJ37YL",
            children: [
              /*#__PURE__*/ _jsx(Image, {
                background: {
                  alt: "",
                  fit: "fill",
                  loading: getLoadingLazyAtYPosition(
                    (componentViewport?.y || 0) +
                      0 +
                      (((componentViewport?.height || 141) -
                        0 -
                        (Math.max(
                          0,
                          ((componentViewport?.height || 141) - 0 - 0) / 1
                        ) *
                          1 +
                          0)) /
                        2 +
                        0 +
                        0) +
                      0 +
                      ((Math.max(
                        0,
                        ((componentViewport?.height || 141) - 0 - 0) / 1
                      ) *
                        1 -
                        0 -
                        363) /
                        2 +
                        0 +
                        0)
                  ),
                  sizes: "71px",
                  ...toResponsiveImage(RXLhSfcG1),
                },
                className: "framer-1w0x74n",
                "data-framer-name":
                  "ChatGPT Image Aug 20, 2025 at 02_43_47 PM 1",
                layoutDependency: layoutDependency,
                layoutId: "sTSxFkgAj",
                ...addPropertyOverrides(
                  {
                    NhYDSHdkA: {
                      background: {
                        alt: "",
                        fit: "fill",
                        loading: getLoadingLazyAtYPosition(
                          (componentViewport?.y || 0) +
                            0 +
                            (((componentViewport?.height || 197) -
                              0 -
                              (Math.max(
                                0,
                                ((componentViewport?.height || 197) - 0 - 0) / 1
                              ) *
                                1 +
                                0)) /
                              2 +
                              0 +
                              0) +
                            0 +
                            ((Math.max(
                              0,
                              ((componentViewport?.height || 197) - 0 - 0) / 1
                            ) *
                              1 -
                              0 -
                              580.57) /
                              2 +
                              0 +
                              0)
                        ),
                        sizes: "118.57px",
                        ...toResponsiveImage(RXLhSfcG1),
                      },
                    },
                  },
                  baseVariant,
                  gestureVariant
                ),
              }),
              /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    style: {
                      "--font-selector":
                        "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                      "--framer-font-family":
                        '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                      "--framer-font-size": "32px",
                      "--framer-text-alignment": "center",
                      "--framer-text-color":
                        "var(--extracted-r6o4lv, rgb(230, 211, 255))",
                    },
                    children: "Hashtag",
                  }),
                }),
                className: "framer-mmvjnq",
                "data-framer-name": "Hashtag",
                fonts: ["GF;Cormorant Upright-regular"],
                layoutDependency: layoutDependency,
                layoutId: "Pwru7UNqw",
                style: {
                  "--extracted-r6o4lv": "rgb(230, 211, 255)",
                  "--framer-paragraph-spacing": "0px",
                },
                text: PVzPSjchM,
                verticalAlignment: "top",
                withExternalLayout: true,
                ...addPropertyOverrides(
                  {
                    NhYDSHdkA: {
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx(motion.p, {
                          style: {
                            "--font-selector":
                              "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                            "--framer-font-family":
                              '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                            "--framer-font-size": "59px",
                            "--framer-text-alignment": "center",
                            "--framer-text-color":
                              "var(--extracted-r6o4lv, rgb(230, 211, 255))",
                          },
                          children: "Hashtag",
                        }),
                      }),
                    },
                  },
                  baseVariant,
                  gestureVariant
                ),
              }),
              /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    style: {
                      "--font-selector": "R0Y7Q29ybW9yYW50LXJlZ3VsYXI=",
                      "--framer-font-family":
                        '"Cormorant", "Cormorant Placeholder", serif',
                      "--framer-font-size": "14px",
                      "--framer-text-alignment": "center",
                      "--framer-text-color":
                        "var(--extracted-r6o4lv, rgb(230, 211, 255))",
                    },
                    children: "#BadriKiDulhania",
                  }),
                }),
                className: "framer-1qb8kic",
                "data-framer-name": "#BadriKiDulhania",
                fonts: ["GF;Cormorant-regular"],
                layoutDependency: layoutDependency,
                layoutId: "JHL7gZEbk",
                style: {
                  "--extracted-r6o4lv": "rgb(230, 211, 255)",
                  "--framer-paragraph-spacing": "0px",
                },
                text: PrrSJxMUh,
                verticalAlignment: "top",
                withExternalLayout: true,
                ...addPropertyOverrides(
                  {
                    NhYDSHdkA: {
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx(motion.p, {
                          style: {
                            "--font-selector": "R0Y7Q29ybW9yYW50LXJlZ3VsYXI=",
                            "--framer-font-family":
                              '"Cormorant", "Cormorant Placeholder", serif',
                            "--framer-font-size": "15px",
                            "--framer-text-alignment": "center",
                            "--framer-text-color":
                              "var(--extracted-r6o4lv, rgb(230, 211, 255))",
                          },
                          children:
                            "While posting photos on social media please use the hashtag - #BadriKiDulhania",
                        }),
                      }),
                    },
                  },
                  baseVariant,
                  gestureVariant
                ),
              }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-YJnEI.framer-16zq1yz, .framer-YJnEI .framer-16zq1yz { display: block; }",
  ".framer-YJnEI.framer-ws2yct { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 141px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 188px; }",
  ".framer-YJnEI .framer-1nqscw9 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: 1px; justify-content: center; max-width: 200px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-YJnEI .framer-1w0x74n { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 71px); position: relative; width: 71px; }",
  ".framer-YJnEI .framer-mmvjnq { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 234px; word-break: break-word; word-wrap: break-word; }",
  ".framer-YJnEI .framer-1qb8kic { flex: none; height: auto; max-width: 150%; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-YJnEI.framer-v-7i446v.framer-ws2yct { height: 197px; width: 327px; }",
  ".framer-YJnEI.framer-v-7i446v .framer-1nqscw9 { gap: 9px; }",
  ".framer-YJnEI.framer-v-7i446v .framer-1w0x74n { height: var(--framer-aspect-ratio-supported, 119px); width: 119px; }",
  ".framer-YJnEI.framer-v-7i446v .framer-mmvjnq { width: 327px; }",
  ".framer-YJnEI.framer-v-7i446v .framer-1qb8kic { max-width: 100%; width: 327px; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 141
 * @framerIntrinsicWidth 188
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"NhYDSHdkA":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"RXLhSfcG1":"icon","PVzPSjchM":"title","PrrSJxMUh":"info"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerZRbsVaPgC = withCSS(Component, css, "framer-YJnEI");
export default FramerZRbsVaPgC;
FramerZRbsVaPgC.displayName = "Thing to know - Info";
FramerZRbsVaPgC.defaultProps = { height: 141, width: 188 };
addPropertyControls(FramerZRbsVaPgC, {
  variant: {
    options: ["J1jpdeNFp", "NhYDSHdkA"],
    optionTitles: ["Desktop", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
  RXLhSfcG1: {
    __defaultAssetReference:
      "data:framer/asset-reference,WtUtKiZfYvFe6ob7yo3S6KaxT4.png?originalFilename=ChatGPT+Image+Aug+20%2C+2025+at+02_43_47+PM+1.png&preferredSize=auto",
    __vekterDefault: {
      alt: "",
      assetReference:
        "data:framer/asset-reference,WtUtKiZfYvFe6ob7yo3S6KaxT4.png?originalFilename=ChatGPT+Image+Aug+20%2C+2025+at+02_43_47+PM+1.png&preferredSize=auto",
    },
    title: "Icon",
    type: ControlType.ResponsiveImage,
  },
  PVzPSjchM: {
    defaultValue: "Hashtag",
    displayTextArea: false,
    title: "Title",
    type: ControlType.String,
  },
  PrrSJxMUh: {
    defaultValue:
      "While posting photos on social media please use the hashtag - #Abkan",
    description:
      "Enter the info above\n\nFind more templates on ",
    displayTextArea: true,
    title: "Info",
    type: ControlType.String,
  },
});
addFonts(
  FramerZRbsVaPgC,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Cormorant Upright",
          source: "google",
          style: "normal",
          url: "https://fonts.gstatic.com/s/cormorantupright/v19/VuJrdM3I2Y35poFONtLdafkUCHw1y2vQjjTkeMnz.woff2",
          weight: "400",
        },
        {
          family: "Cormorant",
          source: "google",
          style: "normal",
          url: "https://fonts.gstatic.com/s/cormorant/v24/H4c2BXOCl9bbnla_nHIA47NMUjsNbCVrFhFTQ7Fg7A2uwYs.woff2",
          weight: "400",
        },
      ],
    },
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerZRbsVaPgC",
      slots: [],
      annotations: {
        framerDisplayContentsDiv: "false",
        framerContractVersion: "1",
        framerAutoSizeImages: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"NhYDSHdkA":{"layout":["fixed","fixed"]}}}',
        framerColorSyntax: "true",
        framerImmutableVariables: "true",
        framerComponentViewportWidth: "true",
        framerVariables:
          '{"RXLhSfcG1":"icon","PVzPSjchM":"title","PrrSJxMUh":"info"}',
        framerIntrinsicWidth: "188",
        framerIntrinsicHeight: "141",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./ZRbsVaPgC.map
