// Generated by Framer (4076eae)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const cycleOrder = ["jRXYa6AaO", "o6R_blFxt"];
const serializationHash = "framer-2X779";
const variantClassNames = {
  jRXYa6AaO: "framer-v-1o2x9ao",
  o6R_blFxt: "framer-v-1a50k7e",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = { Desktop: "jRXYa6AaO", Phone: "o6R_blFxt" };
const getProps = ({ and, height, id, name1, name2, width, ...props }) => {
  return {
    ...props,
    mGvfTjyIu: and ?? props.mGvfTjyIu ?? "&",
    RmKtqkZTr: name2 ?? props.RmKtqkZTr ?? "Kanika",
    Tq1LjDJDw: name1 ?? props.Tq1LjDJDw ?? "Abhishek",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "jRXYa6AaO",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    Tq1LjDJDw,
    mGvfTjyIu,
    RmKtqkZTr,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "jRXYa6AaO",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1o2x9ao",
            className,
            classNames
          ),
          "data-framer-name": "Desktop",
          layoutDependency: layoutDependency,
          layoutId: "jRXYa6AaO",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            { o6R_blFxt: { "data-framer-name": "Phone" } },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.p, {
                  style: {
                    "--font-selector":
                      "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                    "--framer-font-family":
                      '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                    "--framer-font-size": "100px",
                    "--framer-line-height": "30.1%",
                    "--framer-text-alignment": "center",
                    "--framer-text-color":
                      "var(--extracted-r6o4lv, rgb(173, 186, 255))",
                  },
                  children: "Abhishek",
                }),
              }),
              className: "framer-g0yo23",
              "data-framer-name": "Bride",
              fonts: ["GF;Cormorant Upright-regular"],
              layoutDependency: layoutDependency,
              layoutId: "pcvUM1xBM",
              style: {
                "--extracted-r6o4lv": "rgb(173, 186, 255)",
                "--framer-paragraph-spacing": "0px",
              },
              text: Tq1LjDJDw,
              verticalAlignment: "top",
              withExternalLayout: true,
              ...addPropertyOverrides(
                {
                  o6R_blFxt: {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector":
                            "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                          "--framer-font-family":
                            '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                          "--framer-font-size": "60px",
                          "--framer-line-height": "30.1%",
                          "--framer-text-alignment": "center",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, rgb(173, 186, 255))",
                        },
                        children: "Abhishek",
                      }),
                    }),
                  },
                },
                baseVariant,
                gestureVariant
              ),
            }),
            /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.p, {
                  style: {
                    "--font-selector":
                      "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                    "--framer-font-family":
                      '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                    "--framer-font-size": "150px",
                    "--framer-line-height": "30.1%",
                    "--framer-text-color":
                      "var(--extracted-r6o4lv, rgb(0, 234, 255))",
                  },
                  children: "&",
                }),
              }),
              className: "framer-1snbgqb",
              "data-framer-name": "&",
              fonts: ["GF;Cormorant Upright-regular"],
              layoutDependency: layoutDependency,
              layoutId: "DG4oJbcfQ",
              style: {
                "--extracted-r6o4lv": "rgb(0, 234, 255)",
                "--framer-paragraph-spacing": "0px",
              },
              text: mGvfTjyIu,
              verticalAlignment: "top",
              withExternalLayout: true,
              ...addPropertyOverrides(
                {
                  o6R_blFxt: {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector":
                            "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                          "--framer-font-family":
                            '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                          "--framer-font-size": "100px",
                          "--framer-line-height": "30.1%",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, rgb(0, 234, 255))",
                        },
                        children: "&",
                      }),
                    }),
                  },
                },
                baseVariant,
                gestureVariant
              ),
            }),
            /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.p, {
                  style: {
                    "--font-selector":
                      "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                    "--framer-font-family":
                      '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                    "--framer-font-size": "100px",
                    "--framer-line-height": "30.1%",
                    "--framer-text-alignment": "center",
                    "--framer-text-color":
                      "var(--extracted-r6o4lv, rgb(63, 169, 255))",
                  },
                  children: "Kanika",
                }),
              }),
              className: "framer-19aos8w",
              "data-framer-name": "Groom",
              fonts: ["GF;Cormorant Upright-regular"],
              layoutDependency: layoutDependency,
              layoutId: "o0ITR8xxU",
              style: {
                "--extracted-r6o4lv": "rgb(63, 169, 255)",
                "--framer-paragraph-spacing": "0px",
              },
              text: RmKtqkZTr,
              verticalAlignment: "top",
              withExternalLayout: true,
              ...addPropertyOverrides(
                {
                  o6R_blFxt: {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector":
                            "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                          "--framer-font-family":
                            '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                          "--framer-font-size": "60px",
                          "--framer-line-height": "30.1%",
                          "--framer-text-alignment": "center",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, rgb(63, 169, 255))",
                        },
                        children: "Kanika",
                      }),
                    }),
                  },
                },
                baseVariant,
                gestureVariant
              ),
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-2X779.framer-u26i5w, .framer-2X779 .framer-u26i5w { display: block; }",
  ".framer-2X779.framer-1o2x9ao { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1200px; }",
  ".framer-2X779 .framer-g0yo23, .framer-2X779 .framer-1snbgqb, .framer-2X779 .framer-19aos8w { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 105
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"o6R_blFxt":{"layout":["fixed","auto"]}}}
 * @framerVariables {"Tq1LjDJDw":"name1","mGvfTjyIu":"and","RmKtqkZTr":"name2"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerfTpkHQ_TJ = withCSS(Component, css, "framer-2X779");
export default FramerfTpkHQ_TJ;
FramerfTpkHQ_TJ.displayName = "Couple's name";
FramerfTpkHQ_TJ.defaultProps = { height: 105, width: 1200 };
addPropertyControls(FramerfTpkHQ_TJ, {
  variant: {
    options: ["jRXYa6AaO", "o6R_blFxt"],
    optionTitles: ["Desktop", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
  Tq1LjDJDw: {
    defaultValue: "Abhishek",
    displayTextArea: false,
    title: "Name 1",
    type: ControlType.String,
  },
  mGvfTjyIu: {
    defaultValue: "&",
    displayTextArea: false,
    title: "and",
    type: ControlType.String,
  },
  RmKtqkZTr: {
    defaultValue: "Kanika",
    displayTextArea: false,
    title: "Name 2",
    type: ControlType.String,
  },
});
addFonts(
  FramerfTpkHQ_TJ,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Cormorant Upright",
          source: "google",
          style: "normal",
          url: "https://fonts.gstatic.com/s/cormorantupright/v18/VuJrdM3I2Y35poFONtLdafkUCHw1y2vQjjTkeMnz.woff2",
          weight: "400",
        },
      ],
    },
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerfTpkHQ_TJ",
      slots: [],
      annotations: {
        framerImmutableVariables: "true",
        framerVariables:
          '{"Tq1LjDJDw":"name1","mGvfTjyIu":"and","RmKtqkZTr":"name2"}',
        framerIntrinsicHeight: "105",
        framerDisplayContentsDiv: "false",
        framerAutoSizeImages: "true",
        framerContractVersion: "1",
        framerColorSyntax: "true",
        framerComponentViewportWidth: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"o6R_blFxt":{"layout":["fixed","auto"]}}}',
        framerIntrinsicWidth: "1200",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./fTpkHQ_TJ.map
