// Generated by Framer (0b247b4)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const serializationHash = "framer-RNUy2";
const variantClassNames = { wxl3GvO0o: "framer-v-133hv0k" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, message, width, ...props }) => {
  return {
    ...props,
    zUny4mBH5:
      message ??
      props.zUny4mBH5 ??
      "Our families are excited that you are able to join us in celebrating what we hope will be one of the happiest days of our lives. ",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, zUny4mBH5, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    defaultVariant: "wxl3GvO0o",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-133hv0k",
            className,
            classNames
          ),
          "data-framer-name": "Variant 1",
          layoutDependency: layoutDependency,
          layoutId: "wxl3GvO0o",
          ref: refBinding,
          style: { ...style },
          children: /*#__PURE__*/ _jsx(motion.div, {
            className: "framer-1ekqgkn",
            layoutDependency: layoutDependency,
            layoutId: "WoPzdmdoV",
            children: /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.p, {
                  style: {
                    "--font-selector":
                      "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                    "--framer-font-family":
                      '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                    "--framer-font-size": "14px",
                    "--framer-text-alignment": "center",
                    "--framer-text-color":
                      "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                  },
                  children:
                    "Our families are excited that you are able to join us in celebrating what we hope will be one of the happiest days of our lives. ",
                }),
              }),
              className: "framer-1rwre08",
              "data-framer-name":
                "Our families are excited that you are able to join us in celebrating what we hope will be one of the happiest days of our lives.",
              fonts: ["GF;Cormorant Upright-regular"],
              layoutDependency: layoutDependency,
              layoutId: "TlYVmkUMW",
              style: {
                "--extracted-r6o4lv": "rgb(255, 255, 255)",
                "--framer-paragraph-spacing": "0px",
              },
              text: zUny4mBH5,
              verticalAlignment: "top",
              withExternalLayout: true,
            }),
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-RNUy2.framer-1dydaj1, .framer-RNUy2 .framer-1dydaj1 { display: block; }",
  ".framer-RNUy2.framer-133hv0k { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 34px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 418px; }",
  ".framer-RNUy2 .framer-1ekqgkn { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: center; overflow: visible; padding: 0px 30px 0px 30px; position: relative; width: 1px; }",
  ".framer-RNUy2 .framer-1rwre08 { flex: 1 0 0px; height: 100%; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 34
 * @framerIntrinsicWidth 418
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"zUny4mBH5":"message"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerDvdUC6gqM = withCSS(Component, css, "framer-RNUy2");
export default FramerDvdUC6gqM;
FramerDvdUC6gqM.displayName = "Family message";
FramerDvdUC6gqM.defaultProps = { height: 34, width: 418 };
addPropertyControls(FramerDvdUC6gqM, {
  zUny4mBH5: {
    defaultValue:
      "Our families are excited that you are able to join us in celebrating what we hope will be one of the happiest days of our lives. ",
    description:
      "Write your custom family message above\n\nFind more templates on ",
    displayTextArea: true,
    title: "Message",
    type: ControlType.String,
  },
});
addFonts(
  FramerDvdUC6gqM,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Cormorant Upright",
          source: "google",
          style: "normal",
          url: "https://fonts.gstatic.com/s/cormorantupright/v19/VuJrdM3I2Y35poFONtLdafkUCHw1y2vQjjTkeMnz.woff2",
          weight: "400",
        },
      ],
    },
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerDvdUC6gqM",
      slots: [],
      annotations: {
        framerAutoSizeImages: "true",
        framerVariables: '{"zUny4mBH5":"message"}',
        framerDisplayContentsDiv: "false",
        framerColorSyntax: "true",
        framerIntrinsicHeight: "34",
        framerImmutableVariables: "true",
        framerContractVersion: "1",
        framerIntrinsicWidth: "418",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}',
        framerComponentViewportWidth: "true",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./DvdUC6gqM.map
