// Generated by Framer (569fd08)
import { fontStore } from "framer";
fontStore.loadFonts([]);
export const fonts = [{ explicitInter: true, fonts: [] }];
export const css = [
  ".framer-BoWl1 .framer-styles-preset-1x56uk9:not(.rich-text-wrapper), .framer-BoWl1 .framer-styles-preset-1x56uk9.rich-text-wrapper a { --framer-link-text-color: #e6d3ff; --framer-link-text-decoration: underline; }",
];
export const className = "framer-BoWl1";
export const __FramerMetadata__ = {
  exports: {
    fonts: { type: "variable", annotations: { framerContractVersion: "1" } },
    css: { type: "variable", annotations: { framerContractVersion: "1" } },
    className: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
