// Generated by Framer (f21d278)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  getLoadingLazyAtYPosition,
  Image,
  Link,
  RichText,
  SmartComponentScopedContainer,
  SVG,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import ButtonsNavBarMenu from "https://framerusercontent.com/modules/JPMcWwjBNjk577UlKPOa/NyFD7MsO1DVnKNI8btCY/rNzK92DPl.js";
const ButtonsNavBarMenuFonts = getFonts(ButtonsNavBarMenu);
const cycleOrder = [
  "ekxO47tKl",
  "m_ObLaheF",
  "T0ybRMQG9",
  "T5sy80Cd3",
  "yOmRuYc45",
  "Xe70Yohth",
];
const serializationHash = "framer-5bt97";
const variantClassNames = {
  ekxO47tKl: "framer-v-ikey9a",
  m_ObLaheF: "framer-v-brhuhl",
  T0ybRMQG9: "framer-v-4mf2zt",
  T5sy80Cd3: "framer-v-19nvtza",
  Xe70Yohth: "framer-v-1v27xz8",
  yOmRuYc45: "framer-v-uz18jd",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const TPhwWe8Ov = undefined;
const L15NHuJRh = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value;
  }
  return typeof value === "string" ? { src: value } : undefined;
};
const matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg;
  }
  return undefined;
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  "Footer - Phone": "T5sy80Cd3",
  "Main - Desktop": "ekxO47tKl",
  "Phone - White ": "yOmRuYc45",
  "Phone View": "m_ObLaheF",
  "Product card": "Xe70Yohth",
  Footer: "T0ybRMQG9",
};
const Variants = motion.create(React.Fragment);
const getProps = ({ darkModeLogo, height, hover, id, width, ...props }) => {
  return {
    ...props,
    L15NHuJRh: darkModeLogo ??
      props.L15NHuJRh ?? {
        alt: "",
        pixelHeight: 200,
        pixelWidth: 772,
        src: "https://framerusercontent.com/images/QenpdsxekcGblQYXRuoiDLSOABs.png?width=772&height=200",
        srcSet:
          "https://framerusercontent.com/images/QenpdsxekcGblQYXRuoiDLSOABs.png?scale-down-to=512&width=772&height=200 512w,https://framerusercontent.com/images/QenpdsxekcGblQYXRuoiDLSOABs.png?width=772&height=200 772w",
      },
    TPhwWe8Ov: hover ?? props.TPhwWe8Ov,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "ekxO47tKl",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    L15NHuJRh,
    TPhwWe8Ov,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "ekxO47tKl",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onMouseEnter1nw75fi = activeVariantCallback(async (...args) => {
    setGestureState({ isHovered: true });
    if (TPhwWe8Ov) {
      const res = await TPhwWe8Ov(...args);
      if (res === false) return false;
    }
  });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (
      ["m_ObLaheF", "T5sy80Cd3", "yOmRuYc45", "Xe70Yohth"].includes(baseVariant)
    )
      return false;
    return true;
  };
  const isDisplayed1 = () => {
    if (baseVariant === "T0ybRMQG9") return true;
    return false;
  };
  const isDisplayed2 = () => {
    if (baseVariant === "T0ybRMQG9") return false;
    return true;
  };
  const isDisplayed3 = () => {
    if (["m_ObLaheF", "T5sy80Cd3", "yOmRuYc45"].includes(baseVariant))
      return true;
    return false;
  };
  const isDisplayed4 = () => {
    if (baseVariant === "T5sy80Cd3") return false;
    return true;
  };
  const isDisplayed5 = () => {
    if (baseVariant === "T5sy80Cd3") return true;
    return false;
  };
  const isDisplayed6 = () => {
    if (["m_ObLaheF", "T5sy80Cd3", "yOmRuYc45"].includes(baseVariant))
      return false;
    return true;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-ikey9a",
            className,
            classNames
          ),
          "data-framer-name": "Main - Desktop",
          "data-highlight": true,
          layoutDependency: layoutDependency,
          layoutId: "ekxO47tKl",
          onMouseEnter: onMouseEnter1nw75fi,
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            {
              m_ObLaheF: { "data-framer-name": "Phone View" },
              T0ybRMQG9: { "data-framer-name": "Footer" },
              T5sy80Cd3: { "data-framer-name": "Footer - Phone" },
              Xe70Yohth: { "data-framer-name": "Product card" },
              yOmRuYc45: { "data-framer-name": "Phone - White " },
            },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-1sgevnc",
              "data-framer-name": "MP Logo",
              layoutDependency: layoutDependency,
              layoutId: "OC3sOUEIE",
              children: [
                /*#__PURE__*/ _jsx(Link, {
                  href: { webPageId: "FyjNQr0sT" },
                  motionChild: true,
                  nodeId: "LgntGeGSy",
                  openInNewTab: false,
                  scopeId: "HYEJo7hq0",
                  ...addPropertyOverrides(
                    {
                      T0ybRMQG9: { href: { webPageId: "NU5gDu6ml" } },
                      T5sy80Cd3: { href: { webPageId: "NU5gDu6ml" } },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                  children: /*#__PURE__*/ _jsx(Image, {
                    as: "a",
                    background: {
                      alt: "",
                      fit: "fit",
                      loading: getLoadingLazyAtYPosition(
                        (componentViewport?.y || 0) +
                          (13 +
                            ((componentViewport?.height || 92) -
                              13 -
                              ((componentViewport?.height || 92) - 13) * 1) /
                              2) +
                          0 +
                          (((componentViewport?.height || 92) - 13) * 1 -
                            0 -
                            50 +
                            0 +
                            0)
                      ),
                      sizes: "191px",
                      ...toResponsiveImage(L15NHuJRh),
                      ...{ positionX: "center", positionY: "center" },
                    },
                    className: "framer-fp3v26 framer-ma8qqy",
                    "data-framer-name": "Logo",
                    layoutDependency: layoutDependency,
                    layoutId: "LgntGeGSy",
                    ...addPropertyOverrides(
                      {
                        m_ObLaheF: {
                          background: {
                            alt: "",
                            fit: "fill",
                            loading: getLoadingLazyAtYPosition(
                              (componentViewport?.y || 0) +
                                (0 +
                                  ((componentViewport?.height || 99) -
                                    0 -
                                    ((componentViewport?.height || 99) - 0) *
                                      1) /
                                    2) +
                                0 +
                                (((componentViewport?.height || 99) - 0) * 1 -
                                  0 -
                                  44 +
                                  0 +
                                  0)
                            ),
                            sizes: "191px",
                            ...toResponsiveImage(L15NHuJRh),
                          },
                        },
                        T0ybRMQG9: {
                          background: {
                            alt: "",
                            fit: "fit",
                            loading: getLoadingLazyAtYPosition(
                              (componentViewport?.y || 0) +
                                (0 +
                                  ((componentViewport?.height || 79) -
                                    0 -
                                    ((componentViewport?.height || 79) - 0) *
                                      1) /
                                    2) +
                                0 +
                                (((componentViewport?.height || 79) - 0) * 1 -
                                  0 -
                                  50 +
                                  0 +
                                  0)
                            ),
                            sizes: "191px",
                            ...toResponsiveImage(L15NHuJRh),
                            ...{ positionX: "center", positionY: "center" },
                          },
                        },
                        T5sy80Cd3: {
                          background: {
                            alt: "",
                            fit: "fill",
                            loading: getLoadingLazyAtYPosition(
                              (componentViewport?.y || 0) +
                                (0 +
                                  ((componentViewport?.height || 99) -
                                    0 -
                                    ((componentViewport?.height || 99) - 0) *
                                      1) /
                                    2) +
                                0 +
                                (((componentViewport?.height || 99) - 0) * 1 -
                                  0 -
                                  44 +
                                  0 +
                                  0)
                            ),
                            sizes: "191px",
                            ...toResponsiveImage(L15NHuJRh),
                          },
                        },
                        yOmRuYc45: {
                          background: {
                            alt: "",
                            fit: "fill",
                            loading: getLoadingLazyAtYPosition(
                              (componentViewport?.y || 0) +
                                (10 +
                                  ((componentViewport?.height || 99) -
                                    10 -
                                    ((componentViewport?.height || 99) - 10) *
                                      1) /
                                    2) +
                                0 +
                                (((componentViewport?.height || 99) - 10) * 1 -
                                  0 -
                                  44 +
                                  0 +
                                  0)
                            ),
                            pixelHeight: 1024,
                            pixelWidth: 1024,
                            sizes: "217px",
                            src: "https://framerusercontent.com/images/O3szoASldqWFjoAkrjVgpQhpe3A.png?width=1024&height=1024",
                            srcSet:
                              "https://framerusercontent.com/images/O3szoASldqWFjoAkrjVgpQhpe3A.png?scale-down-to=512&width=1024&height=1024 512w,https://framerusercontent.com/images/O3szoASldqWFjoAkrjVgpQhpe3A.png?width=1024&height=1024 1024w",
                          },
                        },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                  }),
                }),
                /*#__PURE__*/ _jsx(SVG, {
                  className: "framer-1p4lvwn",
                  layoutDependency: layoutDependency,
                  layoutId: "DbfL3dZwI",
                  requiresOverflowVisible: true,
                  svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 221 17" overflow="visible"><path d="M 221 17 L 0 17 L 0 12.871 L 0 8.743 L 0 4.614 L 0 0" fill="transparent" stroke-width="3" stroke="rgb(0, 0, 0)"></path></svg>',
                  withExternalLayout: true,
                  ...addPropertyOverrides(
                    {
                      m_ObLaheF: {
                        svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 221 17" overflow="visible"><path d="M 221 0 L 221 17 L 0 17 L 0 12.871 L 0 8.743 L 0 4.614 L 0 0" fill="transparent" stroke-width="2" stroke="rgb(0, 0, 0)"></path></svg>',
                      },
                      T5sy80Cd3: {
                        svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 221 17" overflow="visible"><path d="M 221 0 L 221 17 L 0 17 L 0 12.871 L 0 8.743 L 0 4.614 L 0 0" fill="transparent" stroke-width="2" stroke="rgb(0, 0, 0)"></path></svg>',
                      },
                      yOmRuYc45: {
                        svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 221 17" overflow="visible"><path d="M 221 0 L 221 17 L 0 17 L 0 12.871 L 0 8.743 L 0 4.614 L 0 0" fill="transparent" stroke-width="2" stroke="rgb(255, 255, 255)"></path></svg>',
                      },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                }),
              ],
            }),
            /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-u63ci8",
              "data-framer-name": "Content",
              layoutDependency: layoutDependency,
              layoutId: "JYhPTclm1",
              children: [
                /*#__PURE__*/ _jsx(motion.div, {
                  className: "framer-nz0a96",
                  layoutDependency: layoutDependency,
                  layoutId: "MPElPjRRZ",
                  children: /*#__PURE__*/ _jsxs(motion.div, {
                    className: "framer-1499680",
                    layoutDependency: layoutDependency,
                    layoutId: "dovSMAt4d",
                    children: [
                      /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-1rlt4ay",
                        "data-framer-name": "Center line",
                        layoutDependency: layoutDependency,
                        layoutId: "keGiqe0fX",
                        children: /*#__PURE__*/ _jsx(SVG, {
                          className: "framer-10lkubo",
                          layoutDependency: layoutDependency,
                          layoutId: "Qkg9jV_xR",
                          requiresOverflowVisible: true,
                          svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 2060 16" overflow="visible"><path d="M 2060 16 L 0 16 L 0 0" fill="transparent" stroke-width="3" stroke="rgb(0, 0, 0)"></path></svg>',
                          withExternalLayout: true,
                          ...addPropertyOverrides(
                            {
                              m_ObLaheF: {
                                svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 2060 1" overflow="visible"><path d="M 2060 0 L 0 0" fill="transparent" stroke-width="3" stroke="rgb(0, 0, 0)"></path></svg>',
                              },
                              T5sy80Cd3: {
                                svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 2060 1" overflow="visible"><path d="M 2060 0 L 0 0" fill="transparent" stroke-width="3" stroke="rgb(0, 0, 0)"></path></svg>',
                              },
                              yOmRuYc45: {
                                svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 2060 1" overflow="visible"><path d="M 2060 0 L 0 0" fill="transparent" stroke-width="3" stroke="rgb(255, 255, 255)"></path></svg>',
                              },
                            },
                            baseVariant,
                            gestureVariant
                          ),
                        }),
                      }),
                      isDisplayed() &&
                        /*#__PURE__*/ _jsxs(motion.div, {
                          className: "framer-zs28r2",
                          "data-framer-name": "NB Part 3 (CTA)",
                          layoutDependency: layoutDependency,
                          layoutId: "HV4Z1t9zI",
                          children: [
                            /*#__PURE__*/ _jsxs(motion.div, {
                              className: "framer-1ik1128",
                              layoutDependency: layoutDependency,
                              layoutId: "oTaoMm2KE",
                              children: [
                                isDisplayed1() &&
                                  /*#__PURE__*/ _jsx(RichText, {
                                    __fromCanvasComponent: true,
                                    children: /*#__PURE__*/ _jsx(
                                      React.Fragment,
                                      {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                          dir: "auto",
                                          style: {
                                            "--font-selector":
                                              "RlM7TWFucm9wZS1tZWRpdW0=",
                                            "--framer-font-family":
                                              '"Manrope", "Manrope Placeholder", sans-serif',
                                            "--framer-font-size": "15px",
                                            "--framer-font-weight": "500",
                                            "--framer-letter-spacing":
                                              "-0.03em",
                                          },
                                          children: "",
                                        }),
                                      }
                                    ),
                                    className: "framer-b3behq",
                                    fonts: ["FS;Manrope-medium"],
                                    layoutDependency: layoutDependency,
                                    layoutId: "xb7fD6JBf",
                                    style: {
                                      "--framer-link-text-color":
                                        "rgb(0, 153, 255)",
                                      "--framer-link-text-decoration":
                                        "underline",
                                    },
                                    verticalAlignment: "top",
                                    withExternalLayout: true,
                                  }),
                                isDisplayed2() &&
                                  /*#__PURE__*/ _jsx(Link, {
                                    href: {
                                      hash: ":eA5YfGPOn",
                                      webPageId: "NU5gDu6ml",
                                    },
                                    motionChild: true,
                                    nodeId: "T_qnnF6Wn",
                                    openInNewTab: false,
                                    scopeId: "HYEJo7hq0",
                                    smoothScroll: true,
                                    children: /*#__PURE__*/ _jsx(motion.a, {
                                      className: "framer-12l9bk framer-ma8qqy",
                                      "data-framer-name": "Main CTA",
                                      layoutDependency: layoutDependency,
                                      layoutId: "T_qnnF6Wn",
                                      style: {
                                        backgroundColor: "rgb(0, 0, 0)",
                                        borderBottomLeftRadius: 60,
                                        borderBottomRightRadius: 60,
                                        borderTopLeftRadius: 60,
                                        borderTopRightRadius: 60,
                                      },
                                      children: /*#__PURE__*/ _jsx(RichText, {
                                        __fromCanvasComponent: true,
                                        children: /*#__PURE__*/ _jsx(
                                          React.Fragment,
                                          {
                                            children: /*#__PURE__*/ _jsx(
                                              motion.p,
                                              {
                                                style: {
                                                  "--font-selector":
                                                    "R0Y7TWFucm9wZS02MDA=",
                                                  "--framer-font-family":
                                                    '"Manrope", "Manrope Placeholder", sans-serif',
                                                  "--framer-font-size": "14px",
                                                  "--framer-font-weight": "600",
                                                  "--framer-letter-spacing":
                                                    "-0.03em",
                                                  "--framer-text-alignment":
                                                    "center",
                                                  "--framer-text-color":
                                                    "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                                                },
                                                children: "Choose a template",
                                              }
                                            ),
                                          }
                                        ),
                                        className: "framer-ncmopt",
                                        "data-framer-name":
                                          "See Wedding Templates",
                                        fonts: ["GF;Manrope-600"],
                                        layoutDependency: layoutDependency,
                                        layoutId: "rbcPti1ZP",
                                        style: {
                                          "--extracted-r6o4lv":
                                            "rgb(255, 255, 255)",
                                          "--framer-paragraph-spacing": "0px",
                                        },
                                        verticalAlignment: "top",
                                        withExternalLayout: true,
                                      }),
                                    }),
                                  }),
                              ],
                            }),
                            /*#__PURE__*/ _jsx(motion.div, {
                              className: "framer-1cnqrty",
                              layoutDependency: layoutDependency,
                              layoutId: "m1wiWJWRZ",
                              children: /*#__PURE__*/ _jsx(SVG, {
                                className: "framer-1gl4jr1",
                                layoutDependency: layoutDependency,
                                layoutId: "kUvk8GLhg",
                                requiresOverflowVisible: true,
                                svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 229 16" overflow="visible"><path d="M 229 16 L 0 16 L 0 0" fill="transparent" stroke-width="3" stroke="rgb(0, 0, 0)" stroke-dasharray="-1"></path></svg>',
                                withExternalLayout: true,
                              }),
                            }),
                          ],
                        }),
                    ],
                  }),
                }),
                /*#__PURE__*/ _jsxs(motion.div, {
                  className: "framer-oqpa8z",
                  "data-framer-name": "NB Menu",
                  layoutDependency: layoutDependency,
                  layoutId: "CG9GJuzHn",
                  children: [
                    isDisplayed3() &&
                      /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-nzmlea",
                        "data-framer-name": "NB Part 4 (Menu)",
                        layoutDependency: layoutDependency,
                        layoutId: "Zufoa28yy",
                        children: [
                          isDisplayed4() &&
                            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                              height: 48,
                              width: "48px",
                              ...addPropertyOverrides(
                                {
                                  m_ObLaheF: {
                                    y:
                                      (componentViewport?.y || 0) +
                                      (0 +
                                        ((componentViewport?.height || 99) -
                                          0 -
                                          ((componentViewport?.height || 99) -
                                            0) *
                                            1) /
                                          2) +
                                      0 +
                                      (((componentViewport?.height || 99) - 0) *
                                        1 -
                                        0 -
                                        79) +
                                      0 +
                                      0 +
                                      31,
                                  },
                                  yOmRuYc45: {
                                    y:
                                      (componentViewport?.y || 0) +
                                      (10 +
                                        ((componentViewport?.height || 99) -
                                          10 -
                                          ((componentViewport?.height || 99) -
                                            10) *
                                            1) /
                                          2) +
                                      0 +
                                      (((componentViewport?.height || 99) -
                                        10) *
                                        1 -
                                        0 -
                                        79) +
                                      0 +
                                      0 +
                                      31,
                                  },
                                },
                                baseVariant,
                                gestureVariant
                              ),
                              children: /*#__PURE__*/ _jsx(
                                SmartComponentScopedContainer,
                                {
                                  className: "framer-1k2z127-container",
                                  layoutDependency: layoutDependency,
                                  layoutId: "HJKGimXQb-container",
                                  nodeId: "HJKGimXQb",
                                  rendersWithMotion: true,
                                  scopeId: "HYEJo7hq0",
                                  children: /*#__PURE__*/ _jsx(
                                    ButtonsNavBarMenu,
                                    {
                                      height: "100%",
                                      id: "HJKGimXQb",
                                      layoutId: "HJKGimXQb",
                                      style: { height: "100%", width: "100%" },
                                      variant: matchVariant("vjC9_SR0h"),
                                      width: "100%",
                                      ...addPropertyOverrides(
                                        {
                                          yOmRuYc45: {
                                            variant: matchVariant("TYFyCzt5t"),
                                          },
                                        },
                                        baseVariant,
                                        gestureVariant
                                      ),
                                    }
                                  ),
                                }
                              ),
                            }),
                          isDisplayed5() &&
                            /*#__PURE__*/ _jsx(RichText, {
                              __fromCanvasComponent: true,
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                  dir: "auto",
                                  style: {
                                    "--font-selector":
                                      "RlM7TWFucm9wZS1tZWRpdW0=",
                                    "--framer-font-family":
                                      '"Manrope", "Manrope Placeholder", sans-serif',
                                    "--framer-font-size": "8px",
                                    "--framer-font-weight": "500",
                                    "--framer-letter-spacing": "-0.03em",
                                  },
                                  children: "",
                                }),
                              }),
                              className: "framer-1lv77om",
                              fonts: ["FS;Manrope-medium"],
                              layoutDependency: layoutDependency,
                              layoutId: "USMOFXn9I",
                              style: {
                                "--framer-link-text-color": "rgb(0, 153, 255)",
                                "--framer-link-text-decoration": "underline",
                              },
                              verticalAlignment: "top",
                              withExternalLayout: true,
                            }),
                          /*#__PURE__*/ _jsx(motion.div, {
                            className: "framer-1w8efrb",
                            layoutDependency: layoutDependency,
                            layoutId: "ARuoNJ_EQ",
                            children: /*#__PURE__*/ _jsx(SVG, {
                              className: "framer-l678w1",
                              layoutDependency: layoutDependency,
                              layoutId: "Hc2bqEIyY",
                              requiresOverflowVisible: true,
                              svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 76 16" overflow="visible"><path d="M 76 0 L 76 16 L 0 16 L 0 0" fill="transparent" stroke-width="2" stroke="rgb(0, 0, 0)"></path></svg>',
                              withExternalLayout: true,
                              ...addPropertyOverrides(
                                {
                                  m_ObLaheF: {
                                    svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 76 17" overflow="visible"><path d="M 76 0 L 76 17 L 0 17 L 0 0" fill="transparent" stroke-width="2" stroke="rgb(0, 0, 0)"></path></svg>',
                                  },
                                  T5sy80Cd3: {
                                    svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 95 16" overflow="visible"><path d="M 95 0 L 95 16 L 0 16 L 0 0" fill="transparent" stroke-width="2" stroke="rgb(0, 0, 0)"></path></svg>',
                                  },
                                  yOmRuYc45: {
                                    svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 76 17" overflow="visible"><path d="M 76 0 L 76 17 L 0 17 L 0 0" fill="transparent" stroke-width="2" stroke="rgb(255, 255, 255)"></path></svg>',
                                  },
                                },
                                baseVariant,
                                gestureVariant
                              ),
                            }),
                          }),
                        ],
                      }),
                    isDisplayed6() &&
                      /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-1e3hw5h",
                        "data-framer-name": "NB Part 4 (Menu)",
                        layoutDependency: layoutDependency,
                        layoutId: "SrhiDHwjb",
                        children: [
                          isDisplayed2() &&
                            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                              height: 48,
                              width: "48px",
                              y:
                                (componentViewport?.y || 0) +
                                (13 +
                                  ((componentViewport?.height || 92) -
                                    13 -
                                    79) /
                                    2) +
                                0 +
                                0 +
                                0 +
                                31,
                              ...addPropertyOverrides(
                                {
                                  Xe70Yohth: {
                                    y:
                                      (componentViewport?.y || 0) +
                                      (13 +
                                        ((componentViewport?.height || 92) -
                                          13 -
                                          79) /
                                          2) +
                                      0 +
                                      0 +
                                      0 +
                                      0 +
                                      31,
                                  },
                                },
                                baseVariant,
                                gestureVariant
                              ),
                              children: /*#__PURE__*/ _jsx(
                                SmartComponentScopedContainer,
                                {
                                  className: "framer-m1sh2j-container",
                                  layoutDependency: layoutDependency,
                                  layoutId: "dcl_7QlzD-container",
                                  nodeId: "dcl_7QlzD",
                                  rendersWithMotion: true,
                                  scopeId: "HYEJo7hq0",
                                  children: /*#__PURE__*/ _jsx(
                                    ButtonsNavBarMenu,
                                    {
                                      height: "100%",
                                      id: "dcl_7QlzD",
                                      layoutId: "dcl_7QlzD",
                                      style: { height: "100%", width: "100%" },
                                      variant: matchVariant("vjC9_SR0h"),
                                      width: "100%",
                                    }
                                  ),
                                }
                              ),
                            }),
                          isDisplayed1() &&
                            /*#__PURE__*/ _jsx(motion.div, {
                              className: "framer-1mvjy74",
                              "data-framer-name": "Mp Logo Single",
                              layoutDependency: layoutDependency,
                              layoutId: "tRTTZ07gv",
                              children: /*#__PURE__*/ _jsxs(motion.div, {
                                className: "framer-b53ewr",
                                layoutDependency: layoutDependency,
                                layoutId: "v0Y1xxifT",
                                children: [
                                  /*#__PURE__*/ _jsx(Image, {
                                    background: {
                                      alt: "",
                                      fit: "fill",
                                      pixelHeight: 752,
                                      pixelWidth: 752,
                                      sizes: "21px",
                                      src: "https://framerusercontent.com/images/iWobU73DxUodk4WEwzkuzjCsk6s.png?width=752&height=752",
                                      srcSet:
                                        "https://framerusercontent.com/images/iWobU73DxUodk4WEwzkuzjCsk6s.png?scale-down-to=512&width=752&height=752 512w,https://framerusercontent.com/images/iWobU73DxUodk4WEwzkuzjCsk6s.png?width=752&height=752 752w",
                                    },
                                    className: "framer-1c9lkym",
                                    "data-framer-name": "5 2",
                                    layoutDependency: layoutDependency,
                                    layoutId: "ilEZA2jVb",
                                    ...addPropertyOverrides(
                                      {
                                        T0ybRMQG9: {
                                          background: {
                                            alt: "",
                                            fit: "fill",
                                            loading: getLoadingLazyAtYPosition(
                                              (componentViewport?.y || 0) +
                                                (0 +
                                                  ((componentViewport?.height ||
                                                    79) -
                                                    0 -
                                                    79) /
                                                    2) +
                                                0 +
                                                0 +
                                                0 +
                                                34 +
                                                0 +
                                                28 -
                                                16
                                            ),
                                            pixelHeight: 752,
                                            pixelWidth: 752,
                                            sizes: "21px",
                                            src: "https://framerusercontent.com/images/iWobU73DxUodk4WEwzkuzjCsk6s.png?width=752&height=752",
                                            srcSet:
                                              "https://framerusercontent.com/images/iWobU73DxUodk4WEwzkuzjCsk6s.png?scale-down-to=512&width=752&height=752 512w,https://framerusercontent.com/images/iWobU73DxUodk4WEwzkuzjCsk6s.png?width=752&height=752 752w",
                                          },
                                        },
                                      },
                                      baseVariant,
                                      gestureVariant
                                    ),
                                  }),
                                  /*#__PURE__*/ _jsx(RichText, {
                                    __fromCanvasComponent: true,
                                    children: /*#__PURE__*/ _jsx(
                                      React.Fragment,
                                      {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                          style: {
                                            "--font-selector":
                                              "R0Y7TWFucm9wZS1yZWd1bGFy",
                                            "--framer-font-family":
                                              '"Manrope", "Manrope Placeholder", sans-serif',
                                            "--framer-font-size": "15px",
                                            "--framer-letter-spacing":
                                              "-0.03em",
                                            "--framer-text-alignment": "center",
                                          },
                                          children: "\xae",
                                        }),
                                      }
                                    ),
                                    className: "framer-zt2eeh",
                                    "data-framer-name": "\xae",
                                    fonts: ["GF;Manrope-regular"],
                                    layoutDependency: layoutDependency,
                                    layoutId: "pZf1IPK1Y",
                                    style: {
                                      "--framer-paragraph-spacing": "0px",
                                    },
                                    verticalAlignment: "top",
                                    withExternalLayout: true,
                                  }),
                                ],
                              }),
                            }),
                          /*#__PURE__*/ _jsx(motion.div, {
                            className: "framer-19q1rph",
                            layoutDependency: layoutDependency,
                            layoutId: "OqI6LiSxr",
                            children: /*#__PURE__*/ _jsx(SVG, {
                              className: "framer-vi5uj9",
                              layoutDependency: layoutDependency,
                              layoutId: "eI1EoQDpg",
                              requiresOverflowVisible: true,
                              svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 103 16" overflow="visible"><path d="M 103 0 L 103 16 L 0 16 L 0 0" fill="transparent" stroke-width="3" stroke="rgb(0, 0, 0)"></path></svg>',
                              withExternalLayout: true,
                            }),
                          }),
                        ],
                      }),
                  ],
                }),
              ],
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-5bt97.framer-ma8qqy, .framer-5bt97 .framer-ma8qqy { display: block; }",
  ".framer-5bt97.framer-ikey9a { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 13px 70px 0px 70px; position: relative; width: 1092px; }",
  ".framer-5bt97 .framer-1sgevnc { align-content: center; align-items: center; align-self: stretch; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: auto; justify-content: flex-end; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
  ".framer-5bt97 .framer-fp3v26 { flex: none; height: 50px; overflow: visible; position: relative; text-decoration: none; width: 191px; }",
  ".framer-5bt97 .framer-1p4lvwn { height: 17px; position: relative; width: 221px; }",
  ".framer-5bt97 .framer-u63ci8 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; max-width: 1000%; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
  ".framer-5bt97 .framer-nz0a96, .framer-5bt97 .framer-1499680 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
  ".framer-5bt97 .framer-1rlt4ay { align-content: flex-end; align-items: flex-end; align-self: stretch; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: auto; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
  ".framer-5bt97 .framer-10lkubo { height: 16px; position: relative; width: 2060px; }",
  ".framer-5bt97 .framer-zs28r2 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 79px; justify-content: flex-end; overflow: hidden; padding: 0px; position: relative; width: 229px; }",
  ".framer-5bt97 .framer-1ik1128 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 48px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 217px; }",
  ".framer-5bt97 .framer-b3behq, .framer-5bt97 .framer-ncmopt, .framer-5bt97 .framer-1lv77om { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-5bt97 .framer-12l9bk { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: center; overflow: visible; padding: 15px 30px 15px 30px; position: relative; text-decoration: none; width: 1px; }",
  ".framer-5bt97 .framer-1cnqrty { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px 4px 0px 4px; position: relative; width: min-content; }",
  ".framer-5bt97 .framer-1gl4jr1 { height: 16px; position: relative; width: 229px; }",
  ".framer-5bt97 .framer-oqpa8z { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 79px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 103px; }",
  ".framer-5bt97 .framer-nzmlea { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 100%; justify-content: flex-end; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
  ".framer-5bt97 .framer-1k2z127-container, .framer-5bt97 .framer-m1sh2j-container { flex: none; height: 48px; position: relative; width: 48px; }",
  ".framer-5bt97 .framer-1w8efrb { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 76px; }",
  ".framer-5bt97 .framer-l678w1 { height: 16px; position: relative; width: 76px; }",
  ".framer-5bt97 .framer-1e3hw5h { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 79px; justify-content: flex-end; overflow: hidden; padding: 0px; position: relative; width: 106px; }",
  ".framer-5bt97 .framer-1mvjy74 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 28px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 27px; }",
  ".framer-5bt97 .framer-b53ewr { flex: none; height: 28px; overflow: hidden; position: relative; width: 27px; }",
  ".framer-5bt97 .framer-1c9lkym { bottom: 0px; flex: none; height: 16px; left: 0px; position: absolute; width: 21px; }",
  ".framer-5bt97 .framer-zt2eeh { flex: none; height: auto; position: absolute; right: 1px; top: 0px; white-space: pre; width: auto; }",
  ".framer-5bt97 .framer-19q1rph { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
  ".framer-5bt97 .framer-vi5uj9 { height: 16px; position: relative; width: 103px; }",
  ".framer-5bt97.framer-v-brhuhl.framer-ikey9a { height: 99px; padding: 0px 20px 0px 20px; width: 390px; }",
  ".framer-5bt97.framer-v-brhuhl .framer-1sgevnc, .framer-5bt97.framer-v-19nvtza .framer-1sgevnc, .framer-5bt97.framer-v-uz18jd .framer-1sgevnc { align-self: unset; height: 100%; }",
  ".framer-5bt97.framer-v-brhuhl .framer-fp3v26, .framer-5bt97.framer-v-19nvtza .framer-fp3v26 { height: 44px; order: 0; }",
  ".framer-5bt97.framer-v-brhuhl .framer-1p4lvwn, .framer-5bt97.framer-v-19nvtza .framer-1p4lvwn, .framer-5bt97.framer-v-uz18jd .framer-1p4lvwn { order: 1; }",
  ".framer-5bt97.framer-v-brhuhl .framer-u63ci8, .framer-5bt97.framer-v-19nvtza .framer-u63ci8, .framer-5bt97.framer-v-uz18jd .framer-u63ci8 { align-content: flex-end; align-items: flex-end; height: 100%; }",
  ".framer-5bt97.framer-v-brhuhl .framer-10lkubo, .framer-5bt97.framer-v-19nvtza .framer-10lkubo, .framer-5bt97.framer-v-uz18jd .framer-10lkubo { height: 1px; }",
  ".framer-5bt97.framer-v-brhuhl .framer-oqpa8z, .framer-5bt97.framer-v-uz18jd .framer-oqpa8z { width: 76px; }",
  ".framer-5bt97.framer-v-brhuhl .framer-l678w1, .framer-5bt97.framer-v-uz18jd .framer-l678w1 { height: 17px; }",
  ".framer-5bt97.framer-v-4mf2zt.framer-ikey9a { padding: 0px; }",
  ".framer-5bt97.framer-v-4mf2zt .framer-1e3hw5h { gap: 17px; height: 100%; }",
  ".framer-5bt97.framer-v-4mf2zt .framer-19q1rph, .framer-5bt97.framer-v-1v27xz8 .framer-u63ci8 { align-content: flex-end; align-items: flex-end; }",
  ".framer-5bt97.framer-v-19nvtza.framer-ikey9a { height: 99px; justify-content: flex-start; padding: 0px; width: 390px; }",
  ".framer-5bt97.framer-v-19nvtza .framer-oqpa8z, .framer-5bt97.framer-v-19nvtza .framer-l678w1 { width: 95px; }",
  ".framer-5bt97.framer-v-19nvtza .framer-nzmlea { flex: 1 0 0px; gap: 14px; width: 1px; }",
  ".framer-5bt97.framer-v-19nvtza .framer-1w8efrb { width: 100%; }",
  ".framer-5bt97.framer-v-uz18jd.framer-ikey9a { height: 99px; padding: 10px 20px 0px 20px; width: 390px; }",
  ".framer-5bt97.framer-v-uz18jd .framer-fp3v26 { height: 44px; order: 0; width: 217px; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 92
 * @framerIntrinsicWidth 1092
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"m_ObLaheF":{"layout":["fixed","fixed"]},"T0ybRMQG9":{"layout":["fixed","auto"]},"T5sy80Cd3":{"layout":["fixed","fixed"]},"yOmRuYc45":{"layout":["fixed","fixed"]},"Xe70Yohth":{"layout":["fixed","auto"]}}}
 * @framerVariables {"L15NHuJRh":"darkModeLogo","TPhwWe8Ov":"hover"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerHYEJo7hq0 = withCSS(Component, css, "framer-5bt97");
export default FramerHYEJo7hq0;
FramerHYEJo7hq0.displayName = "Navigation Bar";
FramerHYEJo7hq0.defaultProps = { height: 92, width: 1092 };
addPropertyControls(FramerHYEJo7hq0, {
  variant: {
    options: [
      "ekxO47tKl",
      "m_ObLaheF",
      "T0ybRMQG9",
      "T5sy80Cd3",
      "yOmRuYc45",
      "Xe70Yohth",
    ],
    optionTitles: [
      "Main - Desktop",
      "Phone View",
      "Footer",
      "Footer - Phone",
      "Phone - White ",
      "Product card",
    ],
    title: "Variant",
    type: ControlType.Enum,
  },
  L15NHuJRh: {
    __defaultAssetReference:
      "data:framer/asset-reference,QenpdsxekcGblQYXRuoiDLSOABs.png?originalFilename=Missing+Piece+Logo+-+PNG.png&preferredSize=auto",
    __vekterDefault: {
      alt: "",
      assetReference:
        "data:framer/asset-reference,QenpdsxekcGblQYXRuoiDLSOABs.png?originalFilename=Missing+Piece+Logo+-+PNG.png&preferredSize=auto",
    },
    title: "Dark Mode Logo",
    type: ControlType.ResponsiveImage,
  },
  TPhwWe8Ov: { title: "Hover", type: ControlType.EventHandler },
});
addFonts(
  FramerHYEJo7hq0,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Manrope",
          source: "fontshare",
          style: "normal",
          uiFamilyName: "Manrope",
          url: "https://framerusercontent.com/third-party-assets/fontshare/wf/BNWG6MUI4RTC6WEND2VPDH4MHMIVU3XZ/R5YXY5FMVG6PXU36GNEEA24MIPMEPGSM/CIM4KQCLZSMMLWPVH25IDDSTY4ENPHEY.woff2",
          weight: "500",
        },
        {
          cssFamilyName: "Manrope",
          source: "google",
          style: "normal",
          uiFamilyName: "Manrope",
          url: "https://fonts.gstatic.com/s/manrope/v20/xn7_YHE41ni1AdIRqAuZuw1Bx9mbZk4jE-_A87jxeN7B.woff2",
          weight: "600",
        },
        {
          cssFamilyName: "Manrope",
          source: "google",
          style: "normal",
          uiFamilyName: "Manrope",
          url: "https://fonts.gstatic.com/s/manrope/v20/xn7_YHE41ni1AdIRqAuZuw1Bx9mbZk79FO_A87jxeN7B.woff2",
          weight: "400",
        },
      ],
    },
    ...ButtonsNavBarMenuFonts,
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerHYEJo7hq0",
      slots: [],
      annotations: {
        framerDisplayContentsDiv: "false",
        framerComponentViewportWidth: "true",
        framerContractVersion: "1",
        framerIntrinsicWidth: "1092",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"m_ObLaheF":{"layout":["fixed","fixed"]},"T0ybRMQG9":{"layout":["fixed","auto"]},"T5sy80Cd3":{"layout":["fixed","fixed"]},"yOmRuYc45":{"layout":["fixed","fixed"]},"Xe70Yohth":{"layout":["fixed","auto"]}}}',
        framerVariables: '{"L15NHuJRh":"darkModeLogo","TPhwWe8Ov":"hover"}',
        framerAutoSizeImages: "true",
        framerColorSyntax: "true",
        framerIntrinsicHeight: "92",
        framerImmutableVariables: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./HYEJo7hq0.map
