// Generated by Framer (53c1d35)
import { fontStore } from "framer";
fontStore.loadFonts(["GF;Manrope-700", "GF;Manrope-800"]);
export const fonts = [
  {
    explicitInter: true,
    fonts: [
      {
        family: "Manrope",
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/manrope/v19/xn7_YHE41ni1AdIRqAuZuw1Bx9mbZk4aE-_A87jxeN7B.woff2",
        weight: "700",
      },
      {
        family: "Manrope",
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/manrope/v19/xn7_YHE41ni1AdIRqAuZuw1Bx9mbZk59E-_A87jxeN7B.woff2",
        weight: "800",
      },
    ],
  },
];
export const css = [
  '.framer-w9iVa .framer-styles-preset-1j8be3x:not(.rich-text-wrapper), .framer-w9iVa .framer-styles-preset-1j8be3x.rich-text-wrapper h1 { --framer-font-family: "Manrope", "Manrope Placeholder", sans-serif; --framer-font-family-bold: "Manrope", "Manrope Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 30px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 700; --framer-font-weight-bold: 800; --framer-letter-spacing: -0.03em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: #000000; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
  '@media (max-width: 1199px) and (min-width: 710px) { .framer-w9iVa .framer-styles-preset-1j8be3x:not(.rich-text-wrapper), .framer-w9iVa .framer-styles-preset-1j8be3x.rich-text-wrapper h1 { --framer-font-family: "Manrope", "Manrope Placeholder", sans-serif; --framer-font-family-bold: "Manrope", "Manrope Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 24px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 700; --framer-font-weight-bold: 800; --framer-letter-spacing: -0.03em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: #000000; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
  '@media (max-width: 709px) and (min-width: 0px) { .framer-w9iVa .framer-styles-preset-1j8be3x:not(.rich-text-wrapper), .framer-w9iVa .framer-styles-preset-1j8be3x.rich-text-wrapper h1 { --framer-font-family: "Manrope", "Manrope Placeholder", sans-serif; --framer-font-family-bold: "Manrope", "Manrope Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 31px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 700; --framer-font-weight-bold: 800; --framer-letter-spacing: -0.03em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: #000000; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
export const className = "framer-w9iVa";
export const __FramerMetadata__ = {
  exports: {
    fonts: { type: "variable", annotations: { framerContractVersion: "1" } },
    css: { type: "variable", annotations: { framerContractVersion: "1" } },
    className: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
