// Generated by Framer (0b247b4)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getLoadingLazyAtYPosition,
  Image,
  Link,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const cycleOrder = ["VytUo85jY", "FJ3_AMlrJ"];
const serializationHash = "framer-WfW2b";
const variantClassNames = {
  FJ3_AMlrJ: "framer-v-23kynz",
  VytUo85jY: "framer-v-n9jl7t",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = { Desktop: "VytUo85jY", Phone: "FJ3_AMlrJ" };
const getProps = ({ height, id, instagram, width, ...props }) => {
  return {
    ...props,
    HLKkJyfN9: instagram ?? props.HLKkJyfN9,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "VytUo85jY",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, HLKkJyfN9, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "VytUo85jY",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(Image, {
          ...restProps,
          ...gestureHandlers,
          background: {
            alt: "",
            fit: "fill",
            intrinsicHeight: 265.5,
            intrinsicWidth: 254,
            loading: getLoadingLazyAtYPosition(componentViewport?.y || 0),
            pixelHeight: 531,
            pixelWidth: 508,
            sizes: componentViewport?.width || "100vw",
            src: "https://framerusercontent.com/images/unZZWhOkyxdkg8F1mKw33yJK5pQ.png?scale-down-to=512&width=508&height=531",
            srcSet:
              "https://framerusercontent.com/images/unZZWhOkyxdkg8F1mKw33yJK5pQ.png?width=508&height=531 508w",
          },
          className: cx(
            scopingClassNames,
            "framer-n9jl7t",
            className,
            classNames
          ),
          "data-framer-name": "Desktop",
          layoutDependency: layoutDependency,
          layoutId: "VytUo85jY",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            { FJ3_AMlrJ: { "data-framer-name": "Phone" } },
            baseVariant,
            gestureVariant
          ),
          children: /*#__PURE__*/ _jsxs(motion.div, {
            className: "framer-1hk10wr",
            layoutDependency: layoutDependency,
            layoutId: "VA65Dz7u8",
            children: [
              /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsxs(React.Fragment, {
                  children: [
                    /*#__PURE__*/ _jsx(motion.p, {
                      style: {
                        "--font-selector":
                          "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                        "--framer-font-family":
                          '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                        "--framer-font-size": "64px",
                        "--framer-line-height": "74%",
                        "--framer-text-alignment": "center",
                        "--framer-text-color":
                          "var(--extracted-r6o4lv, rgb(78, 52, 116))",
                      },
                      children: "Follow",
                    }),
                    /*#__PURE__*/ _jsx(motion.p, {
                      style: {
                        "--font-selector":
                          "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                        "--framer-font-family":
                          '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                        "--framer-font-size": "64px",
                        "--framer-line-height": "74%",
                        "--framer-text-alignment": "center",
                        "--framer-text-color":
                          "var(--extracted-2gxw0f, rgb(78, 52, 116))",
                      },
                      children: "the action",
                    }),
                  ],
                }),
                className: "framer-l8iqvm",
                "data-framer-name": "Follow the action",
                fonts: ["GF;Cormorant Upright-regular"],
                layoutDependency: layoutDependency,
                layoutId: "iZhD9R1Vs",
                style: {
                  "--extracted-2gxw0f": "rgb(78, 52, 116)",
                  "--extracted-r6o4lv": "rgb(78, 52, 116)",
                  "--framer-paragraph-spacing": "0px",
                },
                verticalAlignment: "top",
                withExternalLayout: true,
                ...addPropertyOverrides(
                  {
                    FJ3_AMlrJ: {
                      children: /*#__PURE__*/ _jsxs(React.Fragment, {
                        children: [
                          /*#__PURE__*/ _jsx(motion.p, {
                            style: {
                              "--font-selector":
                                "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                              "--framer-font-family":
                                '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                              "--framer-font-size": "80px",
                              "--framer-line-height": "74%",
                              "--framer-text-alignment": "center",
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, rgb(78, 52, 116))",
                            },
                            children: "Follow",
                          }),
                          /*#__PURE__*/ _jsx(motion.p, {
                            style: {
                              "--font-selector":
                                "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                              "--framer-font-family":
                                '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                              "--framer-font-size": "80px",
                              "--framer-line-height": "74%",
                              "--framer-text-alignment": "center",
                              "--framer-text-color":
                                "var(--extracted-2gxw0f, rgb(78, 52, 116))",
                            },
                            children: "the action",
                          }),
                        ],
                      }),
                    },
                  },
                  baseVariant,
                  gestureVariant
                ),
              }),
              /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    style: {
                      "--font-selector": "R0Y7Q29ybW9yYW50LXJlZ3VsYXI=",
                      "--framer-font-family":
                        '"Cormorant", "Cormorant Placeholder", serif',
                      "--framer-font-size": "20px",
                      "--framer-text-alignment": "center",
                      "--framer-text-color":
                        "var(--extracted-r6o4lv, rgb(78, 52, 116))",
                    },
                    children: "Click to open Instagram",
                  }),
                }),
                className: "framer-4h7v7t",
                "data-framer-name": "Click to open Instagram",
                fonts: ["GF;Cormorant-regular"],
                layoutDependency: layoutDependency,
                layoutId: "Hg4FmfwbR",
                style: {
                  "--extracted-r6o4lv": "rgb(78, 52, 116)",
                  "--framer-paragraph-spacing": "0px",
                },
                verticalAlignment: "top",
                withExternalLayout: true,
              }),
              /*#__PURE__*/ _jsx(Link, {
                href: HLKkJyfN9,
                motionChild: true,
                nodeId: "TWiLC1_Vl",
                openInNewTab: true,
                scopeId: "r2lOaxLNK",
                children: /*#__PURE__*/ _jsx(Image, {
                  as: "a",
                  background: {
                    alt: "",
                    fit: "stretch",
                    loading: getLoadingLazyAtYPosition(
                      (componentViewport?.y || 0) +
                        130 +
                        0 +
                        (((componentViewport?.height || 522.5) -
                          260.5 -
                          0 -
                          730.05) /
                          2 +
                          593.6 +
                          50)
                    ),
                    pixelHeight: 260,
                    pixelWidth: 236,
                    positionX: "center",
                    positionY: "center",
                    src: "https://framerusercontent.com/images/a419J1KdzVtZR9Jh5dZ3Lyu6RU.png?width=236&height=260",
                  },
                  className: "framer-sx6vrq framer-kl1lv6",
                  "data-framer-name":
                    "ChatGPT Image Aug 20, 2025 at 01_02_57 PM 1",
                  layoutDependency: layoutDependency,
                  layoutId: "TWiLC1_Vl",
                  ...addPropertyOverrides(
                    {
                      FJ3_AMlrJ: {
                        background: {
                          alt: "",
                          fit: "stretch",
                          loading: getLoadingLazyAtYPosition(
                            (componentViewport?.y || 0) +
                              149 +
                              0 +
                              (((componentViewport?.height || 522.5) -
                                298.5 -
                                0 -
                                868) /
                                2 +
                                712 +
                                58)
                          ),
                          pixelHeight: 260,
                          pixelWidth: 236,
                          positionX: "center",
                          positionY: "center",
                          src: "https://framerusercontent.com/images/a419J1KdzVtZR9Jh5dZ3Lyu6RU.png?width=236&height=260",
                        },
                      },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                }),
              }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-WfW2b.framer-kl1lv6, .framer-WfW2b .framer-kl1lv6 { display: block; }",
  ".framer-WfW2b.framer-n9jl7t { height: 523px; overflow: visible; position: relative; width: 500px; }",
  ".framer-WfW2b .framer-1hk10wr { align-content: center; align-items: center; bottom: 131px; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 25px; justify-content: center; left: 116px; overflow: visible; padding: 0px; position: absolute; right: 117px; top: 130px; }",
  ".framer-WfW2b .framer-l8iqvm { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 267px; word-break: break-word; word-wrap: break-word; }",
  ".framer-WfW2b .framer-4h7v7t { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 259px; word-break: break-word; word-wrap: break-word; }",
  ".framer-WfW2b .framer-sx6vrq { aspect-ratio: 0.9086956879453464 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 86px); position: relative; text-decoration: none; width: 78px; }",
  ".framer-WfW2b.framer-v-23kynz.framer-n9jl7t { aspect-ratio: 0.9566854990583804 / 1; height: var(--framer-aspect-ratio-supported, 523px); }",
  ".framer-WfW2b.framer-v-23kynz .framer-1hk10wr { bottom: 150px; gap: 29px; left: 135px; right: 136px; top: 149px; }",
  ".framer-WfW2b.framer-v-23kynz .framer-l8iqvm { width: 383px; }",
  ".framer-WfW2b.framer-v-23kynz .framer-4h7v7t { width: 222px; }",
  ".framer-WfW2b.framer-v-23kynz .framer-sx6vrq { height: var(--framer-aspect-ratio-supported, 98px); width: 89px; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 522.5
 * @framerIntrinsicWidth 500
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"FJ3_AMlrJ":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"HLKkJyfN9":"instagram"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const Framerr2lOaxLNK = withCSS(Component, css, "framer-WfW2b");
export default Framerr2lOaxLNK;
Framerr2lOaxLNK.displayName = "Moon";
Framerr2lOaxLNK.defaultProps = { height: 522.5, width: 500 };
addPropertyControls(Framerr2lOaxLNK, {
  variant: {
    options: ["VytUo85jY", "FJ3_AMlrJ"],
    optionTitles: ["Desktop", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
  HLKkJyfN9: {
    description:
      "Paste your Instagram link above\n\nFind more templates on ",
    title: "Instagram",
    type: ControlType.Link,
  },
});
addFonts(
  Framerr2lOaxLNK,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Cormorant Upright",
          source: "google",
          style: "normal",
          url: "https://fonts.gstatic.com/s/cormorantupright/v19/VuJrdM3I2Y35poFONtLdafkUCHw1y2vQjjTkeMnz.woff2",
          weight: "400",
        },
        {
          family: "Cormorant",
          source: "google",
          style: "normal",
          url: "https://fonts.gstatic.com/s/cormorant/v24/H4c2BXOCl9bbnla_nHIA47NMUjsNbCVrFhFTQ7Fg7A2uwYs.woff2",
          weight: "400",
        },
      ],
    },
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "Framerr2lOaxLNK",
      slots: [],
      annotations: {
        framerColorSyntax: "true",
        framerAutoSizeImages: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"FJ3_AMlrJ":{"layout":["fixed","fixed"]}}}',
        framerComponentViewportWidth: "true",
        framerContractVersion: "1",
        framerDisplayContentsDiv: "false",
        framerVariables: '{"HLKkJyfN9":"instagram"}',
        framerImmutableVariables: "true",
        framerIntrinsicWidth: "500",
        framerIntrinsicHeight: "522.5",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./r2lOaxLNK.map
