// Generated by Framer (9840458)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  SVG,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const cycleOrder = ["vjC9_SR0h", "MU3zNC8QW", "TYFyCzt5t"];
const serializationHash = "framer-7uPOn";
const variantClassNames = {
  MU3zNC8QW: "framer-v-1q6eiag",
  TYFyCzt5t: "framer-v-ziulrl",
  vjC9_SR0h: "framer-v-fibfq1",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  "Variant 1": "vjC9_SR0h",
  "Variant 3": "TYFyCzt5t",
  Pressed: "MU3zNC8QW",
};
const getProps = ({ click, height, hover, id, width, ...props }) => {
  return {
    ...props,
    in1SMzJzE: click ?? props.in1SMzJzE,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "vjC9_SR0h",
    YqGtFXkBe: hover ?? props.YqGtFXkBe,
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    YqGtFXkBe,
    in1SMzJzE,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "vjC9_SR0h",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onTapbx6e64 = activeVariantCallback(async (...args) => {
    setGestureState({ isPressed: false });
    if (in1SMzJzE) {
      const res = await in1SMzJzE(...args);
      if (res === false) return false;
    }
    setVariant("MU3zNC8QW");
  });
  const onMouseEnter1fo49te = activeVariantCallback(async (...args) => {
    setGestureState({ isHovered: true });
    if (YqGtFXkBe) {
      const res = await YqGtFXkBe(...args);
      if (res === false) return false;
    }
  });
  const onTap14ej7lb = activeVariantCallback(async (...args) => {
    setGestureState({ isPressed: false });
    if (in1SMzJzE) {
      const res = await in1SMzJzE(...args);
      if (res === false) return false;
    }
    setVariant("vjC9_SR0h");
  });
  const onTapurbil2 = activeVariantCallback(async (...args) => {
    setGestureState({ isPressed: false });
    if (in1SMzJzE) {
      const res = await in1SMzJzE(...args);
      if (res === false) return false;
    }
  });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-fibfq1",
            className,
            classNames
          ),
          "data-framer-name": "Variant 1",
          "data-highlight": true,
          layoutDependency: layoutDependency,
          layoutId: "vjC9_SR0h",
          onMouseEnter: onMouseEnter1fo49te,
          onTap: onTapbx6e64,
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            {
              MU3zNC8QW: { "data-framer-name": "Pressed", onTap: onTap14ej7lb },
              TYFyCzt5t: {
                "data-framer-name": "Variant 3",
                onTap: onTapurbil2,
              },
            },
            baseVariant,
            gestureVariant
          ),
          children: /*#__PURE__*/ _jsxs(motion.div, {
            className: "framer-13sfv61",
            "data-border": true,
            "data-framer-name": "Ellipse 2",
            layoutDependency: layoutDependency,
            layoutId: "lztpAoduA",
            style: {
              "--border-bottom-width": "1.5px",
              "--border-color": "rgb(29, 29, 31)",
              "--border-left-width": "1.5px",
              "--border-right-width": "1.5px",
              "--border-style": "solid",
              "--border-top-width": "1.5px",
              borderBottomLeftRadius: "50%",
              borderBottomRightRadius: "50%",
              borderTopLeftRadius: "50%",
              borderTopRightRadius: "50%",
            },
            variants: { TYFyCzt5t: { "--border-color": "rgb(255, 255, 255)" } },
            children: [
              /*#__PURE__*/ _jsx(SVG, {
                className: "framer-qk7286",
                layoutDependency: layoutDependency,
                layoutId: "oPHeaEf8g",
                opacity: 1,
                requiresOverflowVisible: true,
                svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 25 1" overflow="visible"><path d="M 0 0 L 25 0" fill="transparent" stroke-width="2" stroke="rgb(0, 0, 0)" stroke-linecap="round"></path></svg>',
                variants: { MU3zNC8QW: { rotate: 45 } },
                withExternalLayout: true,
                ...addPropertyOverrides(
                  {
                    TYFyCzt5t: {
                      svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 25 1" overflow="visible"><path d="M 0 0 L 25 0" fill="transparent" stroke-width="2" stroke="rgb(255, 255, 255)" stroke-linecap="round"></path></svg>',
                    },
                  },
                  baseVariant,
                  gestureVariant
                ),
              }),
              /*#__PURE__*/ _jsx(SVG, {
                className: "framer-nbbwv6",
                layoutDependency: layoutDependency,
                layoutId: "hVuT3oiXB",
                opacity: 1,
                requiresOverflowVisible: true,
                svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 25 1" overflow="visible"><path d="M 0 0 L 25 0" fill="transparent" stroke-width="2" stroke="rgb(0, 0, 0)" stroke-linecap="round"></path></svg>',
                variants: { MU3zNC8QW: { rotate: -45 } },
                withExternalLayout: true,
                ...addPropertyOverrides(
                  {
                    TYFyCzt5t: {
                      svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 25 1" overflow="visible"><path d="M 0 0 L 25 0" fill="transparent" stroke-width="2" stroke="rgb(255, 255, 255)" stroke-linecap="round"></path></svg>',
                    },
                  },
                  baseVariant,
                  gestureVariant
                ),
              }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-7uPOn.framer-14732l2, .framer-7uPOn .framer-14732l2 { display: block; }",
  ".framer-7uPOn.framer-fibfq1 { cursor: pointer; height: 48px; overflow: hidden; position: relative; width: 48px; }",
  ".framer-7uPOn .framer-13sfv61 { bottom: 0px; flex: none; left: 0px; position: absolute; right: 0px; top: 0px; }",
  ".framer-7uPOn .framer-qk7286 { height: 1px; left: 12px; position: absolute; top: 20px; width: 25px; }",
  ".framer-7uPOn .framer-nbbwv6 { height: 1px; left: 12px; position: absolute; top: 29px; width: 25px; }",
  ".framer-7uPOn.framer-v-1q6eiag .framer-qk7286, .framer-7uPOn.framer-v-1q6eiag .framer-nbbwv6 { top: 24px; }",
  '.framer-7uPOn[data-border="true"]::after, .framer-7uPOn [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 48
 * @framerIntrinsicWidth 48
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"MU3zNC8QW":{"layout":["fixed","fixed"]},"TYFyCzt5t":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"YqGtFXkBe":"hover","in1SMzJzE":"click"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerrNzK92DPl = withCSS(Component, css, "framer-7uPOn");
export default FramerrNzK92DPl;
FramerrNzK92DPl.displayName = "Buttons/Nav Bar Menu";
FramerrNzK92DPl.defaultProps = { height: 48, width: 48 };
addPropertyControls(FramerrNzK92DPl, {
  variant: {
    options: ["vjC9_SR0h", "MU3zNC8QW", "TYFyCzt5t"],
    optionTitles: ["Variant 1", "Pressed", "Variant 3"],
    title: "Variant",
    type: ControlType.Enum,
  },
  YqGtFXkBe: { title: "Hover", type: ControlType.EventHandler },
  in1SMzJzE: { title: "Click", type: ControlType.EventHandler },
});
addFonts(FramerrNzK92DPl, [{ explicitInter: true, fonts: [] }], {
  supportsExplicitInterCodegen: true,
});
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerrNzK92DPl",
      slots: [],
      annotations: {
        framerAutoSizeImages: "true",
        framerComponentViewportWidth: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"MU3zNC8QW":{"layout":["fixed","fixed"]},"TYFyCzt5t":{"layout":["fixed","fixed"]}}}',
        framerIntrinsicWidth: "48",
        framerDisplayContentsDiv: "false",
        framerIntrinsicHeight: "48",
        framerVariables: '{"YqGtFXkBe":"hover","in1SMzJzE":"click"}',
        framerImmutableVariables: "true",
        framerColorSyntax: "true",
        framerContractVersion: "1",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./rNzK92DPl.map
