// Generated by Framer (569fd08)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFontsFromSharedStyle,
  getLoadingLazyAtYPosition,
  Image,
  Link,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/ObwW49yG8fy1HMWNyiJA/8zsDcbfvnCnN9MfrZZSl/O_RrSeicO.js";
const cycleOrder = ["YTjLd8kDk", "LegJflOTb", "M3dJlO3Ri"];
const serializationHash = "framer-Sbx4c";
const variantClassNames = {
  LegJflOTb: "framer-v-bft53x",
  M3dJlO3Ri: "framer-v-1jof4ma",
  YTjLd8kDk: "framer-v-1r33axl",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const XnbcXXegp = undefined;
const b0Odmcs_Z = undefined;
const I7wqgbAd_ = undefined;
const Oz7wr6hEc = undefined;
const Ee2cAuq7F = undefined;
const ZBTzs3upyaK3fHxEtT = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const transformTemplate1 = (_, t) => `translateY(-50%) ${t}`;
const transformTemplate2 = (_, t) => `translate(-50%, -50%) ${t}`;
const toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value;
  }
  return typeof value === "string" ? { src: value } : undefined;
};
const transformTemplate3 = (_, t) => `translateX(-50%) ${t}`;
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  "Event Card - Desktop ": "YTjLd8kDk",
  "Event Card - Phone": "LegJflOTb",
  Tablet: "M3dJlO3Ri",
};
const getProps = ({
  date,
  event,
  height,
  id,
  image,
  time,
  venue,
  width,
  ...props
}) => {
  return {
    ...props,
    b0Odmcs_Z: event ?? props.b0Odmcs_Z ?? "Mehendi",
    Ee2cAuq7F: time ?? props.Ee2cAuq7F ?? "6pm Onwards",
    I7wqgbAd_: date ?? props.I7wqgbAd_ ?? "Thursday, January 25th ",
    Oz7wr6hEc: venue ?? props.Oz7wr6hEc ?? "JW Mariott, Mussoorie",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "YTjLd8kDk",
    XnbcXXegp: image ??
      props.XnbcXXegp ?? {
        alt: "",
        pixelHeight: 1536,
        pixelWidth: 1024,
        src: "https://framerusercontent.com/images/zUjMeX1Vi81LrP1ei9hBLurabM.png?width=1024&height=1536",
        srcSet:
          "https://framerusercontent.com/images/zUjMeX1Vi81LrP1ei9hBLurabM.png?scale-down-to=1024&width=1024&height=1536 682w,https://framerusercontent.com/images/zUjMeX1Vi81LrP1ei9hBLurabM.png?width=1024&height=1536 1024w",
      },
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    b0Odmcs_Z,
    I7wqgbAd_,
    XnbcXXegp,
    Oz7wr6hEc,
    Ee2cAuq7F,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "YTjLd8kDk",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [sharedStyle.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1r33axl",
            className,
            classNames
          ),
          "data-framer-name": "Event Card - Desktop ",
          layoutDependency: layoutDependency,
          layoutId: "YTjLd8kDk",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            {
              LegJflOTb: { "data-framer-name": "Event Card - Phone" },
              M3dJlO3Ri: { "data-framer-name": "Tablet" },
            },
            baseVariant,
            gestureVariant
          ),
          children: /*#__PURE__*/ _jsxs(motion.div, {
            className: "framer-mj6uan",
            "data-framer-name": "All elements",
            layoutDependency: layoutDependency,
            layoutId: "SWFez4cTc",
            children: [
              /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-gmp0mt",
                "data-framer-name": "Event card",
                layoutDependency: layoutDependency,
                layoutId: "t_faGnAZz",
                children: [
                  /*#__PURE__*/ _jsx(motion.div, {
                    className: "framer-1wf6mf2",
                    layoutDependency: layoutDependency,
                    layoutId: "lfWJmJHwy",
                    transformTemplate: transformTemplate1,
                    ...addPropertyOverrides(
                      { LegJflOTb: { transformTemplate: transformTemplate2 } },
                      baseVariant,
                      gestureVariant
                    ),
                    children: /*#__PURE__*/ _jsx(Image, {
                      background: {
                        alt: "",
                        fit: "fill",
                        loading: getLoadingLazyAtYPosition(
                          (componentViewport?.y || 0) +
                            0 +
                            (((componentViewport?.height || 483.5) -
                              0 -
                              483.5) /
                              2 +
                              0 +
                              0) +
                            0 +
                            -141 +
                            193.8661 +
                            -119
                        ),
                        sizes: "158px",
                        ...toResponsiveImage(XnbcXXegp),
                      },
                      className: "framer-1wd6ffz",
                      "data-framer-name": "Inside",
                      layoutDependency: layoutDependency,
                      layoutId: "eMFt8QRWV",
                      style: {
                        borderBottomLeftRadius: 83.48,
                        borderBottomRightRadius: 83.48,
                        borderTopLeftRadius: 83.48,
                        borderTopRightRadius: 83.48,
                      },
                      transformTemplate: transformTemplate2,
                      variants: {
                        LegJflOTb: {
                          borderBottomLeftRadius: 113.76,
                          borderBottomRightRadius: 113.76,
                          borderTopLeftRadius: 113.76,
                          borderTopRightRadius: 113.76,
                        },
                        M3dJlO3Ri: {
                          borderBottomLeftRadius: 62.69,
                          borderBottomRightRadius: 62.69,
                          borderTopLeftRadius: 62.69,
                          borderTopRightRadius: 62.69,
                        },
                      },
                      ...addPropertyOverrides(
                        {
                          LegJflOTb: {
                            background: {
                              alt: "",
                              fit: "fill",
                              loading: getLoadingLazyAtYPosition(
                                (componentViewport?.y || 0) +
                                  50 +
                                  (((componentViewport?.height || 594.5) -
                                    50 -
                                    483.5) /
                                    2 +
                                    0 +
                                    0) +
                                  0 +
                                  -197.645 +
                                  222.1409 +
                                  -5
                              ),
                              sizes: "22.6466px",
                              ...toResponsiveImage(XnbcXXegp),
                            },
                            transformTemplate: transformTemplate3,
                          },
                          M3dJlO3Ri: {
                            background: {
                              alt: "",
                              fit: "fill",
                              loading: getLoadingLazyAtYPosition(
                                (componentViewport?.y || 0) +
                                  0 +
                                  (((componentViewport?.height || 426.5) -
                                    0 -
                                    483.5) /
                                    2 +
                                    0 +
                                    0) +
                                  0 +
                                  -96.7 +
                                  159.3434 +
                                  18.5
                              ),
                              sizes: "130.68px",
                              ...toResponsiveImage(XnbcXXegp),
                            },
                            transformTemplate: transformTemplate3,
                          },
                        },
                        baseVariant,
                        gestureVariant
                      ),
                    }),
                  }),
                  /*#__PURE__*/ _jsx(motion.div, {
                    className: "framer-1hd6f5q",
                    layoutDependency: layoutDependency,
                    layoutId: "KTsu0xLK2",
                    children: /*#__PURE__*/ _jsx(Image, {
                      background: {
                        alt: "",
                        fit: "fill",
                        loading: getLoadingLazyAtYPosition(
                          (componentViewport?.y || 0) +
                            0 +
                            (((componentViewport?.height || 483.5) -
                              0 -
                              483.5) /
                              2 +
                              0 +
                              0) +
                            0 +
                            -141 +
                            0 +
                            0
                        ),
                        pixelHeight: 1536,
                        pixelWidth: 1024,
                        sizes: "309px",
                        src: "https://framerusercontent.com/images/igxDnCEjBozB9NGYPnTUlljFk.png?width=1024&height=1536",
                        srcSet:
                          "https://framerusercontent.com/images/igxDnCEjBozB9NGYPnTUlljFk.png?scale-down-to=1024&width=1024&height=1536 682w,https://framerusercontent.com/images/igxDnCEjBozB9NGYPnTUlljFk.png?width=1024&height=1536 1024w",
                      },
                      className: "framer-1ii7uku",
                      "data-framer-name": "Cane border",
                      layoutDependency: layoutDependency,
                      layoutId: "F8VhpQV4q",
                      style: {
                        filter:
                          "drop-shadow(0px 0px 9px rgba(0, 0, 0, 0.800000011920929))",
                        WebkitFilter:
                          "drop-shadow(0px 0px 9px rgba(0, 0, 0, 0.800000011920929))",
                      },
                      ...addPropertyOverrides(
                        {
                          LegJflOTb: {
                            background: {
                              alt: "",
                              fit: "fill",
                              loading: getLoadingLazyAtYPosition(
                                (componentViewport?.y || 0) +
                                  50 +
                                  (((componentViewport?.height || 594.5) -
                                    50 -
                                    483.5) /
                                    2 +
                                    0 +
                                    0) +
                                  0 +
                                  -197.645 +
                                  0 +
                                  0
                              ),
                              pixelHeight: 1536,
                              pixelWidth: 1024,
                              sizes: "377.82px",
                              src: "https://framerusercontent.com/images/igxDnCEjBozB9NGYPnTUlljFk.png?width=1024&height=1536",
                              srcSet:
                                "https://framerusercontent.com/images/igxDnCEjBozB9NGYPnTUlljFk.png?scale-down-to=1024&width=1024&height=1536 682w,https://framerusercontent.com/images/igxDnCEjBozB9NGYPnTUlljFk.png?width=1024&height=1536 1024w",
                            },
                          },
                          M3dJlO3Ri: {
                            background: {
                              alt: "",
                              fit: "fill",
                              loading: getLoadingLazyAtYPosition(
                                (componentViewport?.y || 0) +
                                  0 +
                                  (((componentViewport?.height || 426.5) -
                                    0 -
                                    483.5) /
                                    2 +
                                    0 +
                                    0) +
                                  0 +
                                  -96.7 +
                                  0 +
                                  0
                              ),
                              pixelHeight: 1536,
                              pixelWidth: 1024,
                              sizes: "253.97px",
                              src: "https://framerusercontent.com/images/igxDnCEjBozB9NGYPnTUlljFk.png?width=1024&height=1536",
                              srcSet:
                                "https://framerusercontent.com/images/igxDnCEjBozB9NGYPnTUlljFk.png?scale-down-to=1024&width=1024&height=1536 682w,https://framerusercontent.com/images/igxDnCEjBozB9NGYPnTUlljFk.png?width=1024&height=1536 1024w",
                            },
                          },
                        },
                        baseVariant,
                        gestureVariant
                      ),
                      children: /*#__PURE__*/ _jsx(Image, {
                        background: {
                          alt: "",
                          fit: "fit",
                          loading: getLoadingLazyAtYPosition(
                            (componentViewport?.y || 0) +
                              0 +
                              (((componentViewport?.height || 483.5) -
                                0 -
                                483.5) /
                                2 +
                                0 +
                                0) +
                              0 +
                              -141 +
                              0 +
                              0 +
                              -87
                          ),
                          pixelHeight: 2891,
                          pixelWidth: 2914,
                          positionX: "center",
                          positionY: "center",
                          sizes: "315px",
                          src: "https://framerusercontent.com/images/lkjJYEzOGIA7bz1eXTWpMfHpsjc.png?width=2914&height=2891",
                          srcSet:
                            "https://framerusercontent.com/images/lkjJYEzOGIA7bz1eXTWpMfHpsjc.png?scale-down-to=512&width=2914&height=2891 512w,https://framerusercontent.com/images/lkjJYEzOGIA7bz1eXTWpMfHpsjc.png?scale-down-to=1024&width=2914&height=2891 1024w,https://framerusercontent.com/images/lkjJYEzOGIA7bz1eXTWpMfHpsjc.png?scale-down-to=2048&width=2914&height=2891 2048w,https://framerusercontent.com/images/lkjJYEzOGIA7bz1eXTWpMfHpsjc.png?width=2914&height=2891 2914w",
                        },
                        className: "framer-lw8yq8",
                        "data-framer-name": "Left gold leaves",
                        layoutDependency: layoutDependency,
                        layoutId: "yuZf8HgbF",
                        style: { rotate: -14 },
                        variants: { LegJflOTb: { rotate: 0 } },
                        ...addPropertyOverrides(
                          {
                            LegJflOTb: {
                              background: {
                                alt: "",
                                fit: "fit",
                                loading: getLoadingLazyAtYPosition(
                                  (componentViewport?.y || 0) +
                                    50 +
                                    (((componentViewport?.height || 594.5) -
                                      50 -
                                      483.5) /
                                      2 +
                                      0 +
                                      0) +
                                    0 +
                                    -197.645 +
                                    0 +
                                    0 +
                                    -119
                                ),
                                pixelHeight: 2891,
                                pixelWidth: 2914,
                                positionX: "center",
                                positionY: "center",
                                sizes: "415px",
                                src: "https://framerusercontent.com/images/lkjJYEzOGIA7bz1eXTWpMfHpsjc.png?width=2914&height=2891",
                                srcSet:
                                  "https://framerusercontent.com/images/lkjJYEzOGIA7bz1eXTWpMfHpsjc.png?scale-down-to=512&width=2914&height=2891 512w,https://framerusercontent.com/images/lkjJYEzOGIA7bz1eXTWpMfHpsjc.png?scale-down-to=1024&width=2914&height=2891 1024w,https://framerusercontent.com/images/lkjJYEzOGIA7bz1eXTWpMfHpsjc.png?scale-down-to=2048&width=2914&height=2891 2048w,https://framerusercontent.com/images/lkjJYEzOGIA7bz1eXTWpMfHpsjc.png?width=2914&height=2891 2914w",
                              },
                            },
                            M3dJlO3Ri: {
                              background: {
                                alt: "",
                                fit: "fit",
                                loading: getLoadingLazyAtYPosition(
                                  (componentViewport?.y || 0) +
                                    0 +
                                    (((componentViewport?.height || 426.5) -
                                      0 -
                                      483.5) /
                                      2 +
                                      0 +
                                      0) +
                                    0 +
                                    -96.7 +
                                    0 +
                                    0 +
                                    -52
                                ),
                                pixelHeight: 2891,
                                pixelWidth: 2914,
                                positionX: "center",
                                positionY: "center",
                                sizes: "225px",
                                src: "https://framerusercontent.com/images/lkjJYEzOGIA7bz1eXTWpMfHpsjc.png?width=2914&height=2891",
                                srcSet:
                                  "https://framerusercontent.com/images/lkjJYEzOGIA7bz1eXTWpMfHpsjc.png?scale-down-to=512&width=2914&height=2891 512w,https://framerusercontent.com/images/lkjJYEzOGIA7bz1eXTWpMfHpsjc.png?scale-down-to=1024&width=2914&height=2891 1024w,https://framerusercontent.com/images/lkjJYEzOGIA7bz1eXTWpMfHpsjc.png?scale-down-to=2048&width=2914&height=2891 2048w,https://framerusercontent.com/images/lkjJYEzOGIA7bz1eXTWpMfHpsjc.png?width=2914&height=2891 2914w",
                              },
                            },
                          },
                          baseVariant,
                          gestureVariant
                        ),
                      }),
                    }),
                  }),
                  /*#__PURE__*/ _jsx(Image, {
                    background: {
                      alt: "",
                      fit: "fit",
                      loading: getLoadingLazyAtYPosition(
                        (componentViewport?.y || 0) +
                          0 +
                          (((componentViewport?.height || 483.5) - 0 - 483.5) /
                            2 +
                            0 +
                            0) +
                          0 +
                          -141 +
                          374 -
                          225.5
                      ),
                      pixelHeight: 2891,
                      pixelWidth: 2914,
                      positionX: "center",
                      positionY: "center",
                      sizes: "294px",
                      src: "https://framerusercontent.com/images/lkjJYEzOGIA7bz1eXTWpMfHpsjc.png?width=2914&height=2891",
                      srcSet:
                        "https://framerusercontent.com/images/lkjJYEzOGIA7bz1eXTWpMfHpsjc.png?scale-down-to=512&width=2914&height=2891 512w,https://framerusercontent.com/images/lkjJYEzOGIA7bz1eXTWpMfHpsjc.png?scale-down-to=1024&width=2914&height=2891 1024w,https://framerusercontent.com/images/lkjJYEzOGIA7bz1eXTWpMfHpsjc.png?scale-down-to=2048&width=2914&height=2891 2048w,https://framerusercontent.com/images/lkjJYEzOGIA7bz1eXTWpMfHpsjc.png?width=2914&height=2891 2914w",
                    },
                    className: "framer-mw81tp",
                    "data-framer-name": "Right gold leaves",
                    layoutDependency: layoutDependency,
                    layoutId: "RA29OWr1W",
                    style: { rotate: 174 },
                    variants: { LegJflOTb: { rotate: 210 } },
                    ...addPropertyOverrides(
                      {
                        LegJflOTb: {
                          background: {
                            alt: "",
                            fit: "fit",
                            loading: getLoadingLazyAtYPosition(
                              (componentViewport?.y || 0) +
                                50 +
                                (((componentViewport?.height || 594.5) -
                                  50 -
                                  483.5) /
                                  2 +
                                  0 +
                                  0) +
                                0 +
                                -197.645 +
                                457.29 -
                                332.5
                            ),
                            pixelHeight: 2891,
                            pixelWidth: 2914,
                            positionX: "center",
                            positionY: "center",
                            sizes: "436px",
                            src: "https://framerusercontent.com/images/lkjJYEzOGIA7bz1eXTWpMfHpsjc.png?width=2914&height=2891",
                            srcSet:
                              "https://framerusercontent.com/images/lkjJYEzOGIA7bz1eXTWpMfHpsjc.png?scale-down-to=512&width=2914&height=2891 512w,https://framerusercontent.com/images/lkjJYEzOGIA7bz1eXTWpMfHpsjc.png?scale-down-to=1024&width=2914&height=2891 1024w,https://framerusercontent.com/images/lkjJYEzOGIA7bz1eXTWpMfHpsjc.png?scale-down-to=2048&width=2914&height=2891 2048w,https://framerusercontent.com/images/lkjJYEzOGIA7bz1eXTWpMfHpsjc.png?width=2914&height=2891 2914w",
                          },
                        },
                        M3dJlO3Ri: {
                          background: {
                            alt: "",
                            fit: "fit",
                            loading: getLoadingLazyAtYPosition(
                              (componentViewport?.y || 0) +
                                0 +
                                (((componentViewport?.height || 426.5) -
                                  0 -
                                  483.5) /
                                  2 +
                                  0 +
                                  0) +
                                0 +
                                -96.7 +
                                307.4 -
                                172.5
                            ),
                            pixelHeight: 2891,
                            pixelWidth: 2914,
                            positionX: "center",
                            positionY: "center",
                            sizes: "230px",
                            src: "https://framerusercontent.com/images/lkjJYEzOGIA7bz1eXTWpMfHpsjc.png?width=2914&height=2891",
                            srcSet:
                              "https://framerusercontent.com/images/lkjJYEzOGIA7bz1eXTWpMfHpsjc.png?scale-down-to=512&width=2914&height=2891 512w,https://framerusercontent.com/images/lkjJYEzOGIA7bz1eXTWpMfHpsjc.png?scale-down-to=1024&width=2914&height=2891 1024w,https://framerusercontent.com/images/lkjJYEzOGIA7bz1eXTWpMfHpsjc.png?scale-down-to=2048&width=2914&height=2891 2048w,https://framerusercontent.com/images/lkjJYEzOGIA7bz1eXTWpMfHpsjc.png?width=2914&height=2891 2914w",
                          },
                        },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                  }),
                ],
              }),
              /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-wkk6z1",
                layoutDependency: layoutDependency,
                layoutId: "qqgdAgXxM",
                children: [
                  /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector":
                            "R0Y7Q29ybW9yYW50IEluZmFudC1yZWd1bGFy",
                          "--framer-font-family":
                            '"Cormorant Infant", "Cormorant Infant Placeholder", serif',
                          "--framer-font-size": "45px",
                          "--framer-line-height": "150%",
                          "--framer-text-alignment": "center",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, rgb(230, 211, 255))",
                        },
                        children: "Mehendi",
                      }),
                    }),
                    className: "framer-1sla6rb",
                    "data-framer-name": "Event name",
                    fonts: ["GF;Cormorant Infant-regular"],
                    layoutDependency: layoutDependency,
                    layoutId: "h9wyLqbRF",
                    style: {
                      "--extracted-r6o4lv": "rgb(230, 211, 255)",
                      "--framer-paragraph-spacing": "0px",
                    },
                    text: b0Odmcs_Z,
                    verticalAlignment: "top",
                    withExternalLayout: true,
                    ...addPropertyOverrides(
                      {
                        LegJflOTb: {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              style: {
                                "--font-selector":
                                  "R0Y7Q29ybW9yYW50IEluZmFudC1yZWd1bGFy",
                                "--framer-font-family":
                                  '"Cormorant Infant", "Cormorant Infant Placeholder", serif',
                                "--framer-font-size": "55px",
                                "--framer-line-height": "150%",
                                "--framer-text-alignment": "center",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, rgb(230, 211, 255))",
                              },
                              children: "Mehendi",
                            }),
                          }),
                        },
                        M3dJlO3Ri: {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              style: {
                                "--font-selector":
                                  "R0Y7Q29ybW9yYW50IEluZmFudC1yZWd1bGFy",
                                "--framer-font-family":
                                  '"Cormorant Infant", "Cormorant Infant Placeholder", serif',
                                "--framer-font-size": "37px",
                                "--framer-line-height": "150%",
                                "--framer-text-alignment": "center",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, rgb(230, 211, 255))",
                              },
                              children: "Mehendi",
                            }),
                          }),
                        },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                  }),
                  /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsxs(React.Fragment, {
                      children: [
                        /*#__PURE__*/ _jsx(motion.p, {
                          style: {
                            "--font-selector": "R0Y7Q29ybW9yYW50LXJlZ3VsYXI=",
                            "--framer-font-family":
                              '"Cormorant", "Cormorant Placeholder", serif',
                            "--framer-font-size": "14px",
                            "--framer-line-height": "100%",
                            "--framer-text-alignment": "center",
                            "--framer-text-color":
                              "var(--extracted-r6o4lv, rgb(230, 211, 255))",
                          },
                          children: "Thursday, January 25th",
                        }),
                        /*#__PURE__*/ _jsx(motion.p, {
                          style: {
                            "--font-selector": "R0Y7Q29ybW9yYW50LXJlZ3VsYXI=",
                            "--framer-font-family":
                              '"Cormorant", "Cormorant Placeholder", serif',
                            "--framer-font-size": "14px",
                            "--framer-line-height": "100%",
                            "--framer-text-alignment": "center",
                            "--framer-text-color":
                              "var(--extracted-2gxw0f, rgb(230, 211, 255))",
                          },
                          children: "JW Mariott, Mussoorie",
                        }),
                        /*#__PURE__*/ _jsx(motion.p, {
                          style: {
                            "--font-selector": "R0Y7Q29ybW9yYW50LXJlZ3VsYXI=",
                            "--framer-font-family":
                              '"Cormorant", "Cormorant Placeholder", serif',
                            "--framer-font-size": "14px",
                            "--framer-line-height": "100%",
                            "--framer-text-alignment": "center",
                            "--framer-text-color":
                              "var(--extracted-1iakedh, rgb(230, 211, 255))",
                          },
                          children: "6pm Onwards",
                        }),
                      ],
                    }),
                    className: "framer-kbffm1",
                    "data-framer-name": "Date and day",
                    fonts: ["GF;Cormorant-regular"],
                    layoutDependency: layoutDependency,
                    layoutId: "y8qKeQJrG",
                    style: {
                      "--extracted-1iakedh": "rgb(230, 211, 255)",
                      "--extracted-2gxw0f": "rgb(230, 211, 255)",
                      "--extracted-r6o4lv": "rgb(230, 211, 255)",
                      "--framer-paragraph-spacing": "0px",
                    },
                    text: I7wqgbAd_,
                    verticalAlignment: "top",
                    withExternalLayout: true,
                    ...addPropertyOverrides(
                      {
                        LegJflOTb: {
                          children: /*#__PURE__*/ _jsxs(React.Fragment, {
                            children: [
                              /*#__PURE__*/ _jsx(motion.p, {
                                style: {
                                  "--font-selector":
                                    "R0Y7Q29ybW9yYW50LXJlZ3VsYXI=",
                                  "--framer-font-family":
                                    '"Cormorant", "Cormorant Placeholder", serif',
                                  "--framer-font-size": "17px",
                                  "--framer-line-height": "100%",
                                  "--framer-text-alignment": "center",
                                  "--framer-text-color":
                                    "var(--extracted-r6o4lv, rgb(230, 211, 255))",
                                },
                                children: "Thursday, January 25th",
                              }),
                              /*#__PURE__*/ _jsx(motion.p, {
                                style: {
                                  "--font-selector":
                                    "R0Y7Q29ybW9yYW50LXJlZ3VsYXI=",
                                  "--framer-font-family":
                                    '"Cormorant", "Cormorant Placeholder", serif',
                                  "--framer-font-size": "17px",
                                  "--framer-line-height": "100%",
                                  "--framer-text-alignment": "center",
                                  "--framer-text-color":
                                    "var(--extracted-2gxw0f, rgb(230, 211, 255))",
                                },
                                children: "JW Mariott, Mussoorie",
                              }),
                              /*#__PURE__*/ _jsx(motion.p, {
                                style: {
                                  "--font-selector":
                                    "R0Y7Q29ybW9yYW50LXJlZ3VsYXI=",
                                  "--framer-font-family":
                                    '"Cormorant", "Cormorant Placeholder", serif',
                                  "--framer-font-size": "17px",
                                  "--framer-line-height": "100%",
                                  "--framer-text-alignment": "center",
                                  "--framer-text-color":
                                    "var(--extracted-1iakedh, rgb(230, 211, 255))",
                                },
                                children: "6pm Onwards",
                              }),
                            ],
                          }),
                        },
                        M3dJlO3Ri: {
                          children: /*#__PURE__*/ _jsxs(React.Fragment, {
                            children: [
                              /*#__PURE__*/ _jsx(motion.p, {
                                style: {
                                  "--font-selector":
                                    "R0Y7Q29ybW9yYW50LXJlZ3VsYXI=",
                                  "--framer-font-family":
                                    '"Cormorant", "Cormorant Placeholder", serif',
                                  "--framer-font-size": "12px",
                                  "--framer-line-height": "100%",
                                  "--framer-text-alignment": "center",
                                  "--framer-text-color":
                                    "var(--extracted-r6o4lv, rgb(230, 211, 255))",
                                },
                                children: "Thursday, January 25th",
                              }),
                              /*#__PURE__*/ _jsx(motion.p, {
                                style: {
                                  "--font-selector":
                                    "R0Y7Q29ybW9yYW50LXJlZ3VsYXI=",
                                  "--framer-font-family":
                                    '"Cormorant", "Cormorant Placeholder", serif',
                                  "--framer-font-size": "12px",
                                  "--framer-line-height": "100%",
                                  "--framer-text-alignment": "center",
                                  "--framer-text-color":
                                    "var(--extracted-2gxw0f, rgb(230, 211, 255))",
                                },
                                children: "JW Mariott, Mussoorie",
                              }),
                              /*#__PURE__*/ _jsx(motion.p, {
                                style: {
                                  "--font-selector":
                                    "R0Y7Q29ybW9yYW50LXJlZ3VsYXI=",
                                  "--framer-font-family":
                                    '"Cormorant", "Cormorant Placeholder", serif',
                                  "--framer-font-size": "12px",
                                  "--framer-line-height": "100%",
                                  "--framer-text-alignment": "center",
                                  "--framer-text-color":
                                    "var(--extracted-1iakedh, rgb(230, 211, 255))",
                                },
                                children: "6pm Onwards",
                              }),
                            ],
                          }),
                        },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                  }),
                  /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsxs(React.Fragment, {
                      children: [
                        /*#__PURE__*/ _jsx(motion.p, {
                          style: {
                            "--font-selector": "R0Y7Q29ybW9yYW50LXJlZ3VsYXI=",
                            "--framer-font-family":
                              '"Cormorant", "Cormorant Placeholder", serif',
                            "--framer-font-size": "14px",
                            "--framer-line-height": "100%",
                            "--framer-text-alignment": "center",
                            "--framer-text-color":
                              "var(--extracted-r6o4lv, rgb(230, 211, 255))",
                          },
                          children: "Thursday, January 25th",
                        }),
                        /*#__PURE__*/ _jsx(motion.p, {
                          style: {
                            "--font-selector": "R0Y7Q29ybW9yYW50LXJlZ3VsYXI=",
                            "--framer-font-family":
                              '"Cormorant", "Cormorant Placeholder", serif',
                            "--framer-font-size": "14px",
                            "--framer-line-height": "100%",
                            "--framer-text-alignment": "center",
                            "--framer-text-color":
                              "var(--extracted-2gxw0f, rgb(230, 211, 255))",
                          },
                          children: "JW Mariott, Mussoorie",
                        }),
                        /*#__PURE__*/ _jsx(motion.p, {
                          style: {
                            "--font-selector": "R0Y7Q29ybW9yYW50LXJlZ3VsYXI=",
                            "--framer-font-family":
                              '"Cormorant", "Cormorant Placeholder", serif',
                            "--framer-font-size": "14px",
                            "--framer-line-height": "100%",
                            "--framer-text-alignment": "center",
                            "--framer-text-color":
                              "var(--extracted-1iakedh, rgb(230, 211, 255))",
                          },
                          children: "6pm Onwards",
                        }),
                      ],
                    }),
                    className: "framer-ah2i2x",
                    "data-framer-name": "Venue",
                    fonts: ["GF;Cormorant-regular"],
                    layoutDependency: layoutDependency,
                    layoutId: "gsIigK5Mr",
                    style: {
                      "--extracted-1iakedh": "rgb(230, 211, 255)",
                      "--extracted-2gxw0f": "rgb(230, 211, 255)",
                      "--extracted-r6o4lv": "rgb(230, 211, 255)",
                      "--framer-paragraph-spacing": "0px",
                    },
                    text: Oz7wr6hEc,
                    verticalAlignment: "top",
                    withExternalLayout: true,
                  }),
                  /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsxs(React.Fragment, {
                      children: [
                        /*#__PURE__*/ _jsx(motion.p, {
                          style: {
                            "--font-selector": "R0Y7Q29ybW9yYW50LXJlZ3VsYXI=",
                            "--framer-font-family":
                              '"Cormorant", "Cormorant Placeholder", serif',
                            "--framer-font-size": "14px",
                            "--framer-line-height": "100%",
                            "--framer-text-alignment": "center",
                            "--framer-text-color":
                              "var(--extracted-r6o4lv, rgb(230, 211, 255))",
                          },
                          children: "Thursday, January 25th",
                        }),
                        /*#__PURE__*/ _jsx(motion.p, {
                          style: {
                            "--font-selector": "R0Y7Q29ybW9yYW50LXJlZ3VsYXI=",
                            "--framer-font-family":
                              '"Cormorant", "Cormorant Placeholder", serif',
                            "--framer-font-size": "14px",
                            "--framer-line-height": "100%",
                            "--framer-text-alignment": "center",
                            "--framer-text-color":
                              "var(--extracted-2gxw0f, rgb(230, 211, 255))",
                          },
                          children: "JW Mariott, Mussoorie",
                        }),
                        /*#__PURE__*/ _jsx(motion.p, {
                          style: {
                            "--font-selector": "R0Y7Q29ybW9yYW50LXJlZ3VsYXI=",
                            "--framer-font-family":
                              '"Cormorant", "Cormorant Placeholder", serif',
                            "--framer-font-size": "14px",
                            "--framer-line-height": "100%",
                            "--framer-text-alignment": "center",
                            "--framer-text-color":
                              "var(--extracted-1iakedh, rgb(230, 211, 255))",
                          },
                          children: "6pm Onwards",
                        }),
                      ],
                    }),
                    className: "framer-qvgap9",
                    "data-framer-name": "Time",
                    fonts: ["GF;Cormorant-regular"],
                    layoutDependency: layoutDependency,
                    layoutId: "bxBOW4Exe",
                    style: {
                      "--extracted-1iakedh": "rgb(230, 211, 255)",
                      "--extracted-2gxw0f": "rgb(230, 211, 255)",
                      "--extracted-r6o4lv": "rgb(230, 211, 255)",
                      "--framer-paragraph-spacing": "0px",
                    },
                    text: Ee2cAuq7F,
                    verticalAlignment: "top",
                    withExternalLayout: true,
                  }),
                  /*#__PURE__*/ _jsx(motion.div, {
                    className: "framer-muryeq",
                    "data-framer-name": "Location",
                    layoutDependency: layoutDependency,
                    layoutId: "fvM24mBFd",
                    children: /*#__PURE__*/ _jsx(RichText, {
                      __fromCanvasComponent: true,
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx(motion.p, {
                          style: {
                            "--font-selector": "R0Y7Q29ybW9yYW50LTcwMA==",
                            "--framer-font-family":
                              '"Cormorant", "Cormorant Placeholder", serif',
                            "--framer-font-size": "14px",
                            "--framer-font-weight": "700",
                            "--framer-line-height": "100%",
                            "--framer-text-alignment": "center",
                            "--framer-text-color":
                              "var(--extracted-r6o4lv, rgb(230, 211, 255))",
                          },
                          children: /*#__PURE__*/ _jsx(Link, {
                            href: ZBTzs3upyaK3fHxEtT,
                            motionChild: true,
                            nodeId: "cXgzWG9yf",
                            openInNewTab: true,
                            relValues: [],
                            scopeId: "vdZO2iG_9",
                            smoothScroll: false,
                            children: /*#__PURE__*/ _jsx(motion.a, {
                              className: "framer-styles-preset-1x56uk9",
                              "data-styles-preset": "O_RrSeicO",
                              children: "See the route",
                            }),
                          }),
                        }),
                      }),
                      className: "framer-1hgedki",
                      "data-framer-name": "Map link",
                      fonts: ["GF;Cormorant-700"],
                      layoutDependency: layoutDependency,
                      layoutId: "cXgzWG9yf",
                      style: {
                        "--extracted-r6o4lv": "rgb(230, 211, 255)",
                        "--framer-paragraph-spacing": "0px",
                      },
                      verticalAlignment: "top",
                      withExternalLayout: true,
                    }),
                  }),
                ],
              }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-Sbx4c.framer-1fubukv, .framer-Sbx4c .framer-1fubukv { display: block; }",
  ".framer-Sbx4c.framer-1r33axl { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 480px; }",
  ".framer-Sbx4c .framer-mj6uan { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 484px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-Sbx4c .framer-gmp0mt { flex: none; height: 374px; overflow: visible; position: relative; width: 480px; }",
  ".framer-Sbx4c .framer-1wf6mf2 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; left: 0px; min-height: 262px; overflow: visible; padding: 0px; position: absolute; top: 52%; width: 100%; }",
  ".framer-Sbx4c .framer-1wd6ffz { aspect-ratio: 0.666077738515901 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 237px); left: 50%; position: absolute; top: 49%; width: 158px; z-index: 1; }",
  ".framer-Sbx4c .framer-1hd6f5q { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; left: 0px; overflow: visible; padding: 0px; position: absolute; top: 0px; width: 100%; }",
  ".framer-Sbx4c .framer-1ii7uku { flex: none; height: 377px; position: relative; width: 309px; }",
  ".framer-Sbx4c .framer-lw8yq8 { flex: none; height: 314px; left: -52px; position: absolute; top: -87px; width: 315px; }",
  ".framer-Sbx4c .framer-mw81tp { bottom: -68px; flex: none; height: 293px; left: calc(54.166666666666686% - 294px / 2); position: absolute; width: 294px; }",
  ".framer-Sbx4c .framer-wkk6z1 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-Sbx4c .framer-1sla6rb { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-Sbx4c .framer-kbffm1, .framer-Sbx4c .framer-ah2i2x, .framer-Sbx4c .framer-qvgap9, .framer-Sbx4c .framer-1hgedki { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-Sbx4c .framer-muryeq { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 22px 0px 22px 0px; position: relative; width: 100%; }",
  ".framer-Sbx4c.framer-v-bft53x.framer-1r33axl { gap: 11.45px; height: 595px; padding: 50px 0px 0px 0px; width: min-content; }",
  ".framer-Sbx4c.framer-v-bft53x .framer-mj6uan { width: 586px; }",
  ".framer-Sbx4c.framer-v-bft53x .framer-gmp0mt { height: 457px; order: 0; width: 587px; }",
  ".framer-Sbx4c.framer-v-bft53x .framer-1wf6mf2 { gap: 13.62px; left: 50%; top: 49%; width: 655px; }",
  ".framer-Sbx4c.framer-v-bft53x .framer-1wd6ffz { bottom: -29px; height: unset; left: 50%; top: -5px; width: var(--framer-aspect-ratio-supported, 197px); }",
  ".framer-Sbx4c.framer-v-bft53x .framer-1hd6f5q { gap: 12.22px; }",
  ".framer-Sbx4c.framer-v-bft53x .framer-1ii7uku { height: 461px; width: 378px; }",
  ".framer-Sbx4c.framer-v-bft53x .framer-lw8yq8 { height: 414px; left: -141px; top: -119px; width: 415px; }",
  ".framer-Sbx4c.framer-v-bft53x .framer-mw81tp { bottom: -102px; height: 435px; left: unset; right: -63px; width: 436px; }",
  ".framer-Sbx4c.framer-v-bft53x .framer-wkk6z1 { order: 1; }",
  ".framer-Sbx4c.framer-v-1jof4ma.framer-1r33axl { height: 427px; width: 395px; }",
  ".framer-Sbx4c.framer-v-1jof4ma .framer-gmp0mt { height: 307px; width: 395px; }",
  ".framer-Sbx4c.framer-v-1jof4ma .framer-1wf6mf2, .framer-Sbx4c.framer-v-1jof4ma .framer-1hd6f5q { gap: 8.22px; }",
  ".framer-Sbx4c.framer-v-1jof4ma .framer-1wd6ffz { height: var(--framer-aspect-ratio-supported, 197px); left: 50%; top: 19px; width: 131px; }",
  ".framer-Sbx4c.framer-v-1jof4ma .framer-1ii7uku { height: 310px; width: 254px; }",
  ".framer-Sbx4c.framer-v-1jof4ma .framer-lw8yq8 { height: 224px; left: -21px; top: -52px; width: 225px; }",
  ".framer-Sbx4c.framer-v-1jof4ma .framer-mw81tp { bottom: -56px; height: 229px; left: calc(54.752851711026636% - 230px / 2); width: 230px; }",
  ...sharedStyle.css,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 483.5
 * @framerIntrinsicWidth 480
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"LegJflOTb":{"layout":["auto","fixed"]},"M3dJlO3Ri":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"b0Odmcs_Z":"event","I7wqgbAd_":"date","XnbcXXegp":"image","Oz7wr6hEc":"venue","Ee2cAuq7F":"time"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramervdZO2iG_9 = withCSS(Component, css, "framer-Sbx4c");
export default FramervdZO2iG_9;
FramervdZO2iG_9.displayName = "Event Card";
FramervdZO2iG_9.defaultProps = { height: 483.5, width: 480 };
addPropertyControls(FramervdZO2iG_9, {
  variant: {
    options: ["YTjLd8kDk", "LegJflOTb", "M3dJlO3Ri"],
    optionTitles: ["Event Card - Desktop ", "Event Card - Phone", "Tablet"],
    title: "Variant",
    type: ControlType.Enum,
  },
  b0Odmcs_Z: {
    defaultValue: "Mehendi",
    description: "",
    displayTextArea: false,
    title: "Event",
    type: ControlType.String,
  },
  I7wqgbAd_: {
    defaultValue: "Thursday, January 25th ",
    displayTextArea: true,
    title: "Date",
    type: ControlType.String,
  },
  XnbcXXegp: {
    __defaultAssetReference:
      "data:framer/asset-reference,zUjMeX1Vi81LrP1ei9hBLurabM.png?originalFilename=Inside.png&preferredSize=auto",
    __vekterDefault: {
      alt: "",
      assetReference:
        "data:framer/asset-reference,zUjMeX1Vi81LrP1ei9hBLurabM.png?originalFilename=Inside.png&preferredSize=auto",
    },
    title: "Image",
    type: ControlType.ResponsiveImage,
  },
  Oz7wr6hEc: {
    defaultValue: "JW Mariott, Mussoorie",
    displayTextArea: true,
    title: "Venue",
    type: ControlType.String,
  },
  Ee2cAuq7F: {
    defaultValue: "6pm Onwards",
    description: "Find more templates on ",
    displayTextArea: false,
    title: "Time",
    type: ControlType.String,
  },
});
addFonts(
  FramervdZO2iG_9,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Cormorant Infant",
          source: "google",
          style: "normal",
          uiFamilyName: "Cormorant Infant",
          url: "https://fonts.gstatic.com/s/cormorantinfant/v22/HhyCU44g9vKiM1sORYSiWeAsLN99xfs9KOOc_agJPrgvYOWWhDlDkWSy.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Cormorant",
          source: "google",
          style: "normal",
          uiFamilyName: "Cormorant",
          url: "https://fonts.gstatic.com/s/cormorant/v24/H4c2BXOCl9bbnla_nHIA47NMUjsNbCVrFhFTQ7Fg7A2uwYs.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Cormorant",
          source: "google",
          style: "normal",
          uiFamilyName: "Cormorant",
          url: "https://fonts.gstatic.com/s/cormorant/v24/H4c2BXOCl9bbnla_nHIA47NMUjsNbCVrFvZUQ7Fg7A2uwYs.woff2",
          weight: "700",
        },
      ],
    },
    ...getFontsFromSharedStyle(sharedStyle.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramervdZO2iG_9",
      slots: [],
      annotations: {
        framerIntrinsicHeight: "483.5",
        framerColorSyntax: "true",
        framerIntrinsicWidth: "480",
        framerVariables:
          '{"b0Odmcs_Z":"event","I7wqgbAd_":"date","XnbcXXegp":"image","Oz7wr6hEc":"venue","Ee2cAuq7F":"time"}',
        framerComponentViewportWidth: "true",
        framerContractVersion: "1",
        framerDisplayContentsDiv: "false",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"LegJflOTb":{"layout":["auto","fixed"]},"M3dJlO3Ri":{"layout":["fixed","fixed"]}}}',
        framerImmutableVariables: "true",
        framerAutoSizeImages: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./vdZO2iG_9.map
