// Generated by Framer (0b247b4)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getLoadingLazyAtYPosition,
  Image,
  Link,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const serializationHash = "framer-gcKUR";
const variantClassNames = { Uc77ms71D: "framer-v-1xtf5zg" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, whatsApp, width, ...props }) => {
  return { ...props, nJ7HcFiVz: whatsApp ?? props.nJ7HcFiVz };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, nJ7HcFiVz, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    defaultVariant: "Uc77ms71D",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(Image, {
          ...restProps,
          ...gestureHandlers,
          background: {
            alt: "",
            fit: "fill",
            intrinsicHeight: 300.5,
            intrinsicWidth: 300.5,
            loading: getLoadingLazyAtYPosition(componentViewport?.y || 0),
            pixelHeight: 601,
            pixelWidth: 601,
            sizes: componentViewport?.width || "100vw",
            src: "https://framerusercontent.com/images/0OP0chhTYt5XIODuolhFrRLMEXI.png?scale-down-to=512&width=601&height=601",
            srcSet:
              "https://framerusercontent.com/images/0OP0chhTYt5XIODuolhFrRLMEXI.png?scale-down-to=512&width=601&height=601 512w,https://framerusercontent.com/images/0OP0chhTYt5XIODuolhFrRLMEXI.png?width=601&height=601 601w",
          },
          className: cx(
            scopingClassNames,
            "framer-1xtf5zg",
            className,
            classNames
          ),
          "data-framer-name": "Variant 1",
          layoutDependency: layoutDependency,
          layoutId: "Uc77ms71D",
          ref: refBinding,
          style: { ...style },
          children: [
            /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.p, {
                  style: {
                    "--font-selector":
                      "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                    "--framer-font-family":
                      '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                    "--framer-font-size": "60px",
                    "--framer-line-height": "80%",
                    "--framer-text-alignment": "center",
                    "--framer-text-color":
                      "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                  },
                  children: "Looking forward to see you",
                }),
              }),
              className: "framer-1pkypk9",
              "data-framer-name": "Looking forward to see you",
              fonts: ["GF;Cormorant Upright-regular"],
              layoutDependency: layoutDependency,
              layoutId: "EeCP1TWH3",
              style: {
                "--extracted-r6o4lv": "rgb(255, 255, 255)",
                "--framer-paragraph-spacing": "0px",
              },
              transformTemplate: transformTemplate1,
              verticalAlignment: "top",
              withExternalLayout: true,
            }),
            /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.p, {
                  style: {
                    "--font-selector": "R0Y7Q29ybW9yYW50LXJlZ3VsYXI=",
                    "--framer-font-family":
                      '"Cormorant", "Cormorant Placeholder", serif',
                    "--framer-font-size": "17.61px",
                    "--framer-text-alignment": "center",
                    "--framer-text-color":
                      "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                  },
                  children: "Click the link to RSVP",
                }),
              }),
              className: "framer-17iwojs",
              "data-framer-name": "Click the link to RSVP",
              fonts: ["GF;Cormorant-regular"],
              layoutDependency: layoutDependency,
              layoutId: "bLYDzafeo",
              style: {
                "--extracted-r6o4lv": "rgb(255, 255, 255)",
                "--framer-paragraph-spacing": "0px",
              },
              transformTemplate: transformTemplate1,
              verticalAlignment: "top",
              withExternalLayout: true,
            }),
            /*#__PURE__*/ _jsx(Link, {
              href: nJ7HcFiVz,
              motionChild: true,
              nodeId: "D4If8fmYD",
              openInNewTab: false,
              scopeId: "dnS84hjFr",
              children: /*#__PURE__*/ _jsx(Image, {
                as: "a",
                background: {
                  alt: "",
                  fit: "fill",
                  loading: getLoadingLazyAtYPosition(
                    (componentViewport?.y || 0) +
                      (componentViewport?.height || 556) -
                      219
                  ),
                  pixelHeight: 1024,
                  pixelWidth: 1024,
                  sizes: "119px",
                  src: "https://framerusercontent.com/images/nlWOMLIMhz1MNMSV0qDfTHbCJUc.png?width=1024&height=1024",
                  srcSet:
                    "https://framerusercontent.com/images/nlWOMLIMhz1MNMSV0qDfTHbCJUc.png?scale-down-to=512&width=1024&height=1024 512w,https://framerusercontent.com/images/nlWOMLIMhz1MNMSV0qDfTHbCJUc.png?width=1024&height=1024 1024w",
                },
                className: "framer-1lbfqcp framer-ujpfw3",
                "data-framer-name": "WhatsApp Link",
                layoutDependency: layoutDependency,
                layoutId: "D4If8fmYD",
                transformTemplate: transformTemplate1,
              }),
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-gcKUR.framer-ujpfw3, .framer-gcKUR .framer-ujpfw3 { display: block; }",
  ".framer-gcKUR.framer-1xtf5zg { height: 556px; overflow: visible; position: relative; width: 556px; }",
  ".framer-gcKUR .framer-1pkypk9 { flex: none; height: auto; left: 50%; position: absolute; top: 134px; white-space: pre-wrap; width: 298px; word-break: break-word; word-wrap: break-word; }",
  ".framer-gcKUR .framer-17iwojs { bottom: 225px; flex: none; height: auto; left: 50%; position: absolute; white-space: pre-wrap; width: 308px; word-break: break-word; word-wrap: break-word; }",
  ".framer-gcKUR .framer-1lbfqcp { aspect-ratio: 1 / 1; bottom: 100px; flex: none; height: var(--framer-aspect-ratio-supported, 119px); left: 50%; position: absolute; text-decoration: none; width: 119px; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 556
 * @framerIntrinsicWidth 556
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"nJ7HcFiVz":"whatsApp"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerdnS84hjFr = withCSS(Component, css, "framer-gcKUR");
export default FramerdnS84hjFr;
FramerdnS84hjFr.displayName = "WhatsApp link";
FramerdnS84hjFr.defaultProps = { height: 556, width: 556 };
addPropertyControls(FramerdnS84hjFr, {
  nJ7HcFiVz: {
    description:
      "Paste your WhatsApp link above\n\nFind more templates on ",
    title: "WhatsApp",
    type: ControlType.Link,
  },
});
addFonts(
  FramerdnS84hjFr,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Cormorant Upright",
          source: "google",
          style: "normal",
          url: "https://fonts.gstatic.com/s/cormorantupright/v19/VuJrdM3I2Y35poFONtLdafkUCHw1y2vQjjTkeMnz.woff2",
          weight: "400",
        },
        {
          family: "Cormorant",
          source: "google",
          style: "normal",
          url: "https://fonts.gstatic.com/s/cormorant/v24/H4c2BXOCl9bbnla_nHIA47NMUjsNbCVrFhFTQ7Fg7A2uwYs.woff2",
          weight: "400",
        },
      ],
    },
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerdnS84hjFr",
      slots: [],
      annotations: {
        framerDisplayContentsDiv: "false",
        framerContractVersion: "1",
        framerVariables: '{"nJ7HcFiVz":"whatsApp"}',
        framerColorSyntax: "true",
        framerImmutableVariables: "true",
        framerComponentViewportWidth: "true",
        framerIntrinsicHeight: "556",
        framerAutoSizeImages: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}',
        framerIntrinsicWidth: "556",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./dnS84hjFr.map
