// Generated by Framer (b71bad1)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
  withFX,
  withOptimizedAppearEffect,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const RichTextWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
  withFX(RichText)
);
const MotionDivWithFX = withFX(motion.div);
const cycleOrder = ["Vye0uw2AD", "dlWKLOMte", "BolKfP6ix"];
const serializationHash = "framer-ig1kp";
const variantClassNames = {
  BolKfP6ix: "framer-v-xo58x2",
  dlWKLOMte: "framer-v-iify01",
  Vye0uw2AD: "framer-v-cul24p",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const transition2 = { bounce: 0.2, delay: 0, duration: 5.2, type: "spring" };
const animation = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition2,
  x: 0,
  y: 0,
};
const animation1 = {
  opacity: 1,
  rotate: 12,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 400,
};
const animation2 = {
  opacity: 1,
  rotate: 15,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 400,
};
const animation3 = {
  opacity: 1,
  rotate: -10,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 400,
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  Desktop: "Vye0uw2AD",
  Phone: "BolKfP6ix",
  Tablet: "dlWKLOMte",
};
const getProps = ({ height, id, name1, name2, width, ...props }) => {
  return {
    ...props,
    AllP6UN2U: name1 ?? props.AllP6UN2U ?? "ABHISHEK",
    CtrfkD_zI: name2 ?? props.CtrfkD_zI ?? "KANIKA",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "Vye0uw2AD",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    AllP6UN2U,
    CtrfkD_zI,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "Vye0uw2AD",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(MotionDivWithFX, {
          ...restProps,
          ...gestureHandlers,
          __framer__adjustPosition: false,
          __framer__offset: 0,
          __framer__parallaxTransformEnabled: true,
          __framer__speed: 70,
          __perspectiveFX: false,
          __smartComponentFX: true,
          __targetOpacity: 1,
          className: cx(
            scopingClassNames,
            "framer-cul24p",
            className,
            classNames
          ),
          "data-framer-name": "Desktop",
          layoutDependency: layoutDependency,
          layoutId: "Vye0uw2AD",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            {
              BolKfP6ix: { "data-framer-name": "Phone" },
              dlWKLOMte: { "data-framer-name": "Tablet" },
            },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsx(RichTextWithFXWithOptimizedAppearEffect, {
              __fromCanvasComponent: true,
              __perspectiveFX: false,
              __smartComponentFX: true,
              __targetOpacity: 1,
              animate: animation,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.h1, {
                  style: {
                    "--font-selector": "R0Y7Q29ybW9yYW50LXJlZ3VsYXI=",
                    "--framer-font-family":
                      '"Cormorant", "Cormorant Placeholder", serif',
                    "--framer-font-size": "100px",
                    "--framer-letter-spacing": "-0.01em",
                    "--framer-line-height": "60px",
                    "--framer-text-alignment": "center",
                    "--framer-text-color":
                      "var(--extracted-gdpscs, rgb(255, 255, 255))",
                    "--framer-text-transform": "uppercase",
                  },
                  children: "ABHISHEK",
                }),
              }),
              className: "framer-yecg9q",
              "data-framer-appear-id": "yecg9q",
              fonts: ["GF;Cormorant-regular"],
              initial: animation1,
              layoutDependency: layoutDependency,
              layoutId: "J6unZtbma",
              optimized: true,
              style: {
                "--extracted-gdpscs": "rgb(255, 255, 255)",
                "--framer-link-text-color": "rgb(0, 153, 255)",
                "--framer-link-text-decoration": "underline",
              },
              text: AllP6UN2U,
              verticalAlignment: "top",
              withExternalLayout: true,
              ...addPropertyOverrides(
                {
                  BolKfP6ix: {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.h1, {
                        style: {
                          "--font-selector": "R0Y7Q29ybW9yYW50LXJlZ3VsYXI=",
                          "--framer-font-family":
                            '"Cormorant", "Cormorant Placeholder", serif',
                          "--framer-font-size": "52px",
                          "--framer-letter-spacing": "-0.01em",
                          "--framer-line-height": "48px",
                          "--framer-text-alignment": "center",
                          "--framer-text-color":
                            "var(--extracted-gdpscs, rgb(255, 255, 255))",
                          "--framer-text-transform": "uppercase",
                        },
                        children: "ABHISHEK",
                      }),
                    }),
                  },
                },
                baseVariant,
                gestureVariant
              ),
            }),
            /*#__PURE__*/ _jsx(RichTextWithFXWithOptimizedAppearEffect, {
              __fromCanvasComponent: true,
              __perspectiveFX: false,
              __smartComponentFX: true,
              __targetOpacity: 1,
              animate: animation,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.h2, {
                  style: {
                    "--font-selector": "R0Y7Q29ybW9yYW50LXJlZ3VsYXI=",
                    "--framer-font-family":
                      '"Cormorant", "Cormorant Placeholder", serif',
                    "--framer-font-size": "42px",
                    "--framer-letter-spacing": "0.42em",
                    "--framer-line-height": "60px",
                    "--framer-text-alignment": "center",
                    "--framer-text-color":
                      "var(--extracted-1of0zx5, rgb(255, 255, 255))",
                  },
                  children: "WEDS",
                }),
              }),
              className: "framer-1yvpwq4",
              "data-framer-appear-id": "1yvpwq4",
              fonts: ["GF;Cormorant-regular"],
              initial: animation2,
              layoutDependency: layoutDependency,
              layoutId: "pJWG80d0n",
              optimized: true,
              style: {
                "--extracted-1of0zx5": "rgb(255, 255, 255)",
                "--framer-link-text-color": "rgb(0, 153, 255)",
                "--framer-link-text-decoration": "underline",
              },
              verticalAlignment: "top",
              withExternalLayout: true,
              ...addPropertyOverrides(
                {
                  BolKfP6ix: {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.h2, {
                        style: {
                          "--font-selector": "R0Y7Q29ybW9yYW50LXJlZ3VsYXI=",
                          "--framer-font-family":
                            '"Cormorant", "Cormorant Placeholder", serif',
                          "--framer-font-size": "24px",
                          "--framer-letter-spacing": "0.42em",
                          "--framer-line-height": "48px",
                          "--framer-text-alignment": "center",
                          "--framer-text-color":
                            "var(--extracted-1of0zx5, rgb(255, 255, 255))",
                        },
                        children: "WEDS",
                      }),
                    }),
                  },
                },
                baseVariant,
                gestureVariant
              ),
            }),
            /*#__PURE__*/ _jsx(RichTextWithFXWithOptimizedAppearEffect, {
              __fromCanvasComponent: true,
              __perspectiveFX: false,
              __smartComponentFX: true,
              __targetOpacity: 1,
              animate: animation,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.h1, {
                  style: {
                    "--font-selector": "R0Y7Q29ybW9yYW50LXJlZ3VsYXI=",
                    "--framer-font-family":
                      '"Cormorant", "Cormorant Placeholder", serif',
                    "--framer-font-size": "100px",
                    "--framer-letter-spacing": "-0.01em",
                    "--framer-line-height": "60px",
                    "--framer-text-alignment": "center",
                    "--framer-text-color":
                      "var(--extracted-gdpscs, rgb(255, 255, 255))",
                    "--framer-text-transform": "uppercase",
                  },
                  children: "KANIKA",
                }),
              }),
              className: "framer-u5rkni",
              "data-framer-appear-id": "u5rkni",
              fonts: ["GF;Cormorant-regular"],
              initial: animation3,
              layoutDependency: layoutDependency,
              layoutId: "dSEbNxyaS",
              optimized: true,
              style: {
                "--extracted-gdpscs": "rgb(255, 255, 255)",
                "--framer-link-text-color": "rgb(0, 153, 255)",
                "--framer-link-text-decoration": "underline",
              },
              text: CtrfkD_zI,
              verticalAlignment: "top",
              withExternalLayout: true,
              ...addPropertyOverrides(
                {
                  BolKfP6ix: {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.h1, {
                        style: {
                          "--font-selector": "R0Y7Q29ybW9yYW50LXJlZ3VsYXI=",
                          "--framer-font-family":
                            '"Cormorant", "Cormorant Placeholder", serif',
                          "--framer-font-size": "52px",
                          "--framer-letter-spacing": "-0.01em",
                          "--framer-line-height": "45px",
                          "--framer-text-alignment": "center",
                          "--framer-text-color":
                            "var(--extracted-gdpscs, rgb(255, 255, 255))",
                          "--framer-text-transform": "uppercase",
                        },
                        children: "KANIKA",
                      }),
                    }),
                  },
                },
                baseVariant,
                gestureVariant
              ),
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-ig1kp.framer-7jxg58, .framer-ig1kp .framer-7jxg58 { display: block; }",
  ".framer-ig1kp.framer-cul24p { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 393px; }",
  ".framer-ig1kp .framer-yecg9q, .framer-ig1kp .framer-1yvpwq4, .framer-ig1kp .framer-u5rkni { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-ig1kp.framer-v-xo58x2.framer-cul24p { gap: 0px; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 200
 * @framerIntrinsicWidth 393
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"dlWKLOMte":{"layout":["fixed","auto"]},"BolKfP6ix":{"layout":["fixed","auto"]}}}
 * @framerVariables {"AllP6UN2U":"name1","CtrfkD_zI":"name2"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerWWcA4xoYs = withCSS(Component, css, "framer-ig1kp");
export default FramerWWcA4xoYs;
FramerWWcA4xoYs.displayName = "Names";
FramerWWcA4xoYs.defaultProps = { height: 200, width: 393 };
addPropertyControls(FramerWWcA4xoYs, {
  variant: {
    options: ["Vye0uw2AD", "dlWKLOMte", "BolKfP6ix"],
    optionTitles: ["Desktop", "Tablet", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
  AllP6UN2U: {
    defaultValue: "ABHISHEK",
    description:
      "Enter the groom or bride's name above. \n\nFind more templates on ",
    displayTextArea: false,
    title: "Name 1",
    type: ControlType.String,
  },
  CtrfkD_zI: {
    defaultValue: "KANIKA",
    description:
      "Enter the groom or bride's name above. \n\nFind more templates on ",
    displayTextArea: false,
    title: "Name 2",
    type: ControlType.String,
  },
});
addFonts(
  FramerWWcA4xoYs,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Cormorant",
          source: "google",
          style: "normal",
          url: "https://fonts.gstatic.com/s/cormorant/v24/H4c2BXOCl9bbnla_nHIA47NMUjsNbCVrFhFTQ7Fg7A2uwYs.woff2",
          weight: "400",
        },
      ],
    },
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerWWcA4xoYs",
      slots: [],
      annotations: {
        framerImmutableVariables: "true",
        framerComponentViewportWidth: "true",
        framerColorSyntax: "true",
        framerVariables: '{"AllP6UN2U":"name1","CtrfkD_zI":"name2"}',
        framerIntrinsicWidth: "393",
        framerIntrinsicHeight: "200",
        framerAutoSizeImages: "true",
        framerContractVersion: "1",
        framerDisplayContentsDiv: "false",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"dlWKLOMte":{"layout":["fixed","auto"]},"BolKfP6ix":{"layout":["fixed","auto"]}}}',
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./WWcA4xoYs.map
