// Generated by Framer (4eeba22)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  ComponentViewportProvider,
  Container,
  cx,
  GeneratedComponentContext,
  getFonts,
  getFontsFromSharedStyle,
  Image,
  Link,
  PropertyOverrides,
  RenderTarget,
  RichText,
  useCustomCursors,
  useHydratedBreakpointVariants,
  useIsOnFramerCanvas,
  useLocaleInfo,
  withCodeBoundaryForOverrides,
  withCSS,
  withMappedReactProps,
} from "framer";
import { LayoutGroup, motion } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import DiscountButton, * as DiscountButtonInfo from "#framer/local/canvasComponent/enDRnjdQs/enDRnjdQs.js";
import NavigationBar from "#framer/local/canvasComponent/HYEJo7hq0/HYEJo7hq0.js";
import { withoutRightClick } from "#framer/local/codeFile/oVDZnT9/no_Right_click_save.js";
import * as sharedStyle1 from "#framer/local/css/bqzoPsKqs/bqzoPsKqs.js";
import * as sharedStyle from "#framer/local/css/qlbbgH4df/qlbbgH4df.js";
const DiscountButtonFonts = getFonts(DiscountButton);
const DiscountButtonWithoutRightClick1avycatWithMappedReactProps1f51p88 =
  withMappedReactProps(
    withCodeBoundaryForOverrides(DiscountButton, {
      nodeId: "qDKoBYo1e",
      override: withoutRightClick,
      scopeId: "pHRKi0e8z",
    }),
    DiscountButtonInfo
  );
const NavigationBarFonts = getFonts(NavigationBar);
const breakpoints = {
  C71cKSVP5: "(max-width: 809.98px)",
  iOqY39SDY: "(min-width: 1094px)",
  lJnlU637I: "(min-width: 810px) and (max-width: 1093.98px)",
};
const isBrowser = () => typeof document !== "undefined";
const serializationHash = "framer-DR6fM";
const variantClassNames = {
  C71cKSVP5: "framer-v-1k1qxhe",
  iOqY39SDY: "framer-v-1e77eq1",
  lJnlU637I: "framer-v-32ruxk",
};
const breakpointRules = {
  C71cKSVP5: [
    ".framer-DR6fM .framer-18106e7 { gap: 0px; }",
    ".framer-DR6fM .framer-1ayglh { gap: 44px 43px; }",
    ".framer-DR6fM .framer-1jkpfsu { flex-wrap: nowrap; min-width: 300px; }",
    ".framer-DR6fM .framer-18knqnd { flex-wrap: wrap; }",
    ".framer-DR6fM .framer-190erqx { height: 88px; width: 330px; }",
    ".framer-DR6fM .framer-1937cdr { flex: 1 0 0px; width: 1px; }",
    ".framer-DR6fM .framer-rz1lpf { width: 277px; }",
    ".framer-DR6fM .framer-1h1cs1j { width: 305px; }",
    ".framer-DR6fM .framer-89qxe9 { overflow: visible; width: 270px; }",
    ".framer-DR6fM .framer-1voij2w { height: min-content; min-width: unset; }",
    ".framer-DR6fM .framer-1avycat-container { height: 462px; }",
    ".framer-DR6fM .framer-54qdc2-container { height: 74px; }",
  ],
  lJnlU637I: [".framer-DR6fM .framer-18knqnd { gap: 75px; }"],
};
const breakpointKeys = Object.keys(breakpointRules);
const selectors = {
  C71cKSVP5: ".framer-1k1qxhe-override",
  lJnlU637I: ".framer-32ruxk-override",
};
const rules = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-DR6fM.framer-7n5udu, .framer-DR6fM .framer-7n5udu { display: block; }",
  ".framer-DR6fM.framer-1e77eq1 { align-content: center; align-items: center; background-color: var(--token-1c21ae32-c50c-4cd6-b383-1ad64b2d123b, #ffffff); display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
  ".framer-DR6fM .framer-sfa3t7 { background: transparent; flex-grow: 1; height: 0px; margin: 0px; margin-bottom: -0px; position: relative; width: 0px; }",
  ".framer-DR6fM .framer-18106e7 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; order: 1001; overflow: hidden; padding: 40px 30px 40px 30px; position: relative; width: 100%; }",
  ".framer-DR6fM .framer-1ayglh { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 79px 43px; height: min-content; justify-content: flex-start; max-width: 1500px; overflow: hidden; padding: 30px 0px 30px 0px; position: relative; width: 100%; }",
  ".framer-DR6fM .framer-1jkpfsu { --border-bottom-width: 0px; --border-color: #000000; --border-left-width: 0px; --border-right-width: 0px; --border-style: solid; --border-top-width: 1px; align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: wrap; gap: 36px; height: min-content; justify-content: flex-start; min-width: 614px; overflow: hidden; padding: 50px 0px 0px 0px; position: relative; width: 1px; }",
  ".framer-DR6fM .framer-18knqnd { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 49px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-DR6fM .framer-190erqx { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 144px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 173px; }",
  ".framer-DR6fM .framer-1937cdr { --framer-link-text-color: #0099ff; --framer-link-text-decoration: underline; flex: none; height: auto; position: relative; white-space: pre-wrap; width: 173px; word-break: break-word; word-wrap: break-word; }",
  ".framer-DR6fM .framer-rz1lpf { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 227px; }",
  ".framer-DR6fM .framer-d1xnn4 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 21px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-DR6fM .framer-1h1cs1j { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-DR6fM .framer-89qxe9 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 197px; }",
  ".framer-DR6fM .framer-kzb8mv { --framer-paragraph-spacing: 0px; flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
  ".framer-DR6fM .framer-19yee6j { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 228px; }",
  ".framer-DR6fM .framer-1bb6uyw { --framer-paragraph-spacing: 0px; flex: none; height: auto; position: relative; white-space: pre-wrap; width: 247px; word-break: break-word; word-wrap: break-word; }",
  ".framer-DR6fM .framer-166gjrj { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-DR6fM .framer-1dox7hm, .framer-DR6fM .framer-1sdltc5 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 25px); overflow: visible; position: relative; text-decoration: none; width: 25px; }",
  ".framer-DR6fM .framer-s0xwr4 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
  ".framer-DR6fM .framer-wqevy { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 21px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-DR6fM .framer-acnuld, .framer-DR6fM .framer-1641fh2, .framer-DR6fM .framer-f68p68, .framer-DR6fM .framer-1y78ikv, .framer-DR6fM .framer-ialscl, .framer-DR6fM .framer-1jgu37o { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
  ".framer-DR6fM .framer-103tbk9, .framer-DR6fM .framer-1lgxw97, .framer-DR6fM .framer-1nhps8v, .framer-DR6fM .framer-90jfwl, .framer-DR6fM .framer-zyrpz3, .framer-DR6fM .framer-nmny92 { --framer-paragraph-spacing: 0px; flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-DR6fM .framer-15u10f6 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-DR6fM .framer-du0gvk { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; min-height: 18px; min-width: 97px; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
  ".framer-DR6fM .framer-1voij2w { --border-bottom-width: 0px; --border-color: #000000; --border-left-width: 0px; --border-right-width: 0px; --border-style: solid; --border-top-width: 1px; align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 313px; justify-content: center; min-width: 377px; overflow: hidden; padding: 50px 0px 0px 0px; position: relative; width: 1px; }",
  ".framer-DR6fM .framer-1avycat-container { flex: 1 0 0px; height: auto; position: relative; width: 1px; }",
  ".framer-DR6fM .framer-54qdc2-container { flex: none; height: auto; max-width: 1500px; position: relative; width: 100%; }",
  '[data-layout-template="true"] > #overlay { margin-bottom: -0px; }',
  ...sharedStyle.css,
  ...sharedStyle1.css,
  '.framer-DR6fM[data-border="true"]::after, .framer-DR6fM [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
const mediaQueries = {
  C71cKSVP5: "(max-width: 809.98px)",
  iOqY39SDY: "(min-width: 1094px)",
  lJnlU637I: "(min-width: 810px) and (max-width: 1093.98px)",
};
const HTMLStyle = ({ value }) => {
  const onCanvas = useIsOnFramerCanvas();
  if (onCanvas) return null;
  return /*#__PURE__*/ _jsx("style", {
    dangerouslySetInnerHTML: { __html: value },
    "data-framer-html-style": "",
  });
};
const humanReadableVariantMap = {
  Desktop: "iOqY39SDY",
  Phone: "C71cKSVP5",
  Tablet: "lJnlU637I",
};
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "iOqY39SDY",
  };
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const { style, className, layoutId, variant, children, ...restProps } =
    getProps(props);
  const [baseVariant, hydratedBaseVariant] = useHydratedBreakpointVariants(
    variant,
    breakpoints,
    false
  );
  const gestureVariant = undefined;
  const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (!isBrowser()) return true;
    if (baseVariant === "C71cKSVP5") return false;
    return true;
  };
  useCustomCursors({});
  return /*#__PURE__*/ _jsx(GeneratedComponentContext.Provider, {
    value: {
      isLayoutTemplate: true,
      primaryVariantId: "iOqY39SDY",
      variantClassNames,
    },
    children: /*#__PURE__*/ _jsxs(LayoutGroup, {
      id: layoutId ?? defaultLayoutId,
      children: [
        /*#__PURE__*/ _jsx(HTMLStyle, {
          value:
            ":root body { background: var(--token-1c21ae32-c50c-4cd6-b383-1ad64b2d123b, rgb(255, 255, 255)); }",
        }),
        /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          className: cx(scopingClassNames, "framer-1e77eq1", className),
          "data-layout-template": true,
          ref: refBinding,
          style: { ...style },
          children: [
            children,
            /*#__PURE__*/ _jsx("div", { className: "framer-sfa3t7" }),
            /*#__PURE__*/ _jsxs("section", {
              className: "framer-18106e7",
              "data-framer-name": "Section 7",
              children: [
                /*#__PURE__*/ _jsxs("div", {
                  className: "framer-1ayglh",
                  "data-framer-name": "Main Footer",
                  children: [
                    /*#__PURE__*/ _jsx("div", {
                      className: "framer-1jkpfsu",
                      "data-border": true,
                      "data-framer-name": "Footer - left side stack",
                      children: /*#__PURE__*/ _jsxs("div", {
                        className: "framer-18knqnd",
                        children: [
                          /*#__PURE__*/ _jsx("div", {
                            className: "framer-190erqx",
                            children: /*#__PURE__*/ _jsx(RichText, {
                              __fromCanvasComponent: true,
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx("h1", {
                                  className: "framer-styles-preset-1j8be3x",
                                  "data-styles-preset": "qlbbgH4df",
                                  style: {
                                    "--framer-text-alignment": "left",
                                    "--framer-text-color": "rgb(0, 0, 0)",
                                  },
                                  children:
                                    "Website Templates for Wedding Invites",
                                }),
                              }),
                              className: "framer-1937cdr",
                              fonts: ["Inter"],
                              verticalAlignment: "top",
                              withExternalLayout: true,
                            }),
                          }),
                          /*#__PURE__*/ _jsxs("div", {
                            className: "framer-rz1lpf",
                            "data-framer-name": "Get in touch stack",
                            children: [
                              /*#__PURE__*/ _jsx("div", {
                                className: "framer-d1xnn4",
                                children: /*#__PURE__*/ _jsxs("div", {
                                  className: "framer-1h1cs1j",
                                  children: [
                                    /*#__PURE__*/ _jsx("div", {
                                      className: "framer-89qxe9",
                                      children: /*#__PURE__*/ _jsx(
                                        PropertyOverrides,
                                        {
                                          breakpoint: baseVariant,
                                          overrides: {
                                            C71cKSVP5: {
                                              children: /*#__PURE__*/ _jsx(
                                                React.Fragment,
                                                {
                                                  children: /*#__PURE__*/ _jsx(
                                                    "p",
                                                    {
                                                      style: {
                                                        "--font-selector":
                                                          "R0Y7TWFucm9wZS1yZWd1bGFy",
                                                        "--framer-font-family":
                                                          '"Manrope", "Manrope Placeholder", sans-serif',
                                                        "--framer-font-size":
                                                          "23px",
                                                        "--framer-letter-spacing":
                                                          "-0.03em",
                                                        "--framer-text-color":
                                                          "rgb(28, 28, 28)",
                                                      },
                                                      children:
                                                        /*#__PURE__*/ _jsx(
                                                          "strong",
                                                          {
                                                            children:
                                                              "Need any help ? We've got your back.",
                                                          }
                                                        ),
                                                    }
                                                  ),
                                                }
                                              ),
                                            },
                                          },
                                          children: /*#__PURE__*/ _jsx(
                                            RichText,
                                            {
                                              __fromCanvasComponent: true,
                                              children: /*#__PURE__*/ _jsx(
                                                React.Fragment,
                                                {
                                                  children: /*#__PURE__*/ _jsx(
                                                    "p",
                                                    {
                                                      style: {
                                                        "--font-selector":
                                                          "R0Y7TWFucm9wZS1yZWd1bGFy",
                                                        "--framer-font-family":
                                                          '"Manrope", "Manrope Placeholder", sans-serif',
                                                        "--framer-font-size":
                                                          "15px",
                                                        "--framer-letter-spacing":
                                                          "-0.03em",
                                                        "--framer-text-color":
                                                          "rgb(28, 28, 28)",
                                                      },
                                                      children:
                                                        /*#__PURE__*/ _jsx(
                                                          "strong",
                                                          {
                                                            children:
                                                              "Need any help ? We've got your back.",
                                                          }
                                                        ),
                                                    }
                                                  ),
                                                }
                                              ),
                                              className: "framer-kzb8mv",
                                              "data-framer-name":
                                                "Need Help? WhatsApp Us",
                                              fonts: [
                                                "GF;Manrope-regular",
                                                "GF;Manrope-700",
                                              ],
                                              verticalAlignment: "top",
                                              withExternalLayout: true,
                                            }
                                          ),
                                        }
                                      ),
                                    }),
                                    /*#__PURE__*/ _jsx("div", {
                                      className: "framer-19yee6j",
                                      children: /*#__PURE__*/ _jsx(RichText, {
                                        __fromCanvasComponent: true,
                                        children: /*#__PURE__*/ _jsx(
                                          React.Fragment,
                                          {
                                            children: /*#__PURE__*/ _jsx("p", {
                                              style: {
                                                "--font-selector":
                                                  "R0Y7TWFucm9wZS1yZWd1bGFy",
                                                "--framer-font-family":
                                                  '"Manrope", "Manrope Placeholder", sans-serif',
                                                "--framer-font-size": "15px",
                                                "--framer-letter-spacing":
                                                  "-0.03em",
                                                "--framer-text-alignment":
                                                  "left",
                                                "--framer-text-color":
                                                  "rgb(28, 28, 28)",
                                              },
                                              children: /*#__PURE__*/ _jsx(
                                                Link,
                                                {
                                                  href: "mailto:hello@",
                                                  motionChild: true,
                                                  nodeId: "iISOVydBq",
                                                  openInNewTab: true,
                                                  relValues: [],
                                                  scopeId: "pHRKi0e8z",
                                                  smoothScroll: false,
                                                  children: /*#__PURE__*/ _jsx(
                                                    motion.a,
                                                    {
                                                      className:
                                                        "framer-styles-preset-kmt2jv",
                                                      "data-styles-preset":
                                                        "bqzoPsKqs",
                                                      children:
                                                        "hello@",
                                                    }
                                                  ),
                                                }
                                              ),
                                            }),
                                          }
                                        ),
                                        className: "framer-1bb6uyw",
                                        "data-framer-name":
                                          "hello@",
                                        fonts: ["GF;Manrope-regular"],
                                        verticalAlignment: "top",
                                        withExternalLayout: true,
                                      }),
                                    }),
                                  ],
                                }),
                              }),
                              /*#__PURE__*/ _jsxs("div", {
                                className: "framer-166gjrj",
                                "data-framer-name": "Social",
                                children: [
                                  /*#__PURE__*/ _jsx(Link, {
                                    href: "https://www.instagram.com/missingpieceinvites",
                                    motionChild: true,
                                    nodeId: "joLXKRg3_",
                                    openInNewTab: true,
                                    scopeId: "pHRKi0e8z",
                                    children: /*#__PURE__*/ _jsx(Image, {
                                      as: "a",
                                      background: {
                                        alt: "",
                                        fit: "fill",
                                        intrinsicHeight: 25,
                                        intrinsicWidth: 25,
                                        pixelHeight: 50,
                                        pixelWidth: 50,
                                        sizes: "25px",
                                        src: "https://framerusercontent.com/images/mTNpaCYEtvbU38EdLAwWSkz3I.png?width=50&height=50",
                                      },
                                      className: "framer-1dox7hm framer-7n5udu",
                                      "data-framer-name": "Instagram",
                                    }),
                                  }),
                                  /*#__PURE__*/ _jsx(PropertyOverrides, {
                                    breakpoint: baseVariant,
                                    overrides: {
                                      lJnlU637I: {
                                        href: "https://www.youtube.com/@MissingPieceTutorials",
                                      },
                                    },
                                    children: /*#__PURE__*/ _jsx(Link, {
                                      href: "https://www.youtube.com/@MissingPieceInvites",
                                      motionChild: true,
                                      nodeId: "QDSK7Wfxd",
                                      openInNewTab: true,
                                      scopeId: "pHRKi0e8z",
                                      children: /*#__PURE__*/ _jsx(Image, {
                                        as: "a",
                                        background: {
                                          alt: "",
                                          fit: "fill",
                                          intrinsicHeight: 25,
                                          intrinsicWidth: 25,
                                          pixelHeight: 50,
                                          pixelWidth: 50,
                                          sizes: "25px",
                                          src: "https://framerusercontent.com/images/Zkho1ZBitcL8cRrDurkSmMrxx20.png?width=50&height=50",
                                        },
                                        className:
                                          "framer-1sdltc5 framer-7n5udu",
                                        "data-framer-name": "Instagram",
                                      }),
                                    }),
                                  }),
                                ],
                              }),
                            ],
                          }),
                          /*#__PURE__*/ _jsx("div", {
                            className: "framer-s0xwr4",
                            "data-framer-name": "Information Stack",
                            children: /*#__PURE__*/ _jsxs("div", {
                              className: "framer-wqevy",
                              children: [
                                /*#__PURE__*/ _jsx("div", {
                                  className: "framer-acnuld",
                                  children: /*#__PURE__*/ _jsx(RichText, {
                                    __fromCanvasComponent: true,
                                    children: /*#__PURE__*/ _jsx(
                                      React.Fragment,
                                      {
                                        children: /*#__PURE__*/ _jsx("p", {
                                          style: {
                                            "--font-selector":
                                              "R0Y7TWFucm9wZS03MDA=",
                                            "--framer-font-family":
                                              '"Manrope", "Manrope Placeholder", sans-serif',
                                            "--framer-font-size": "15px",
                                            "--framer-font-weight": "700",
                                            "--framer-letter-spacing":
                                              "-0.03em",
                                            "--framer-text-color":
                                              "rgb(28, 28, 28)",
                                          },
                                          children: "Information",
                                        }),
                                      }
                                    ),
                                    className: "framer-103tbk9",
                                    "data-framer-name": "Get in touch",
                                    fonts: ["GF;Manrope-700"],
                                    verticalAlignment: "top",
                                    withExternalLayout: true,
                                  }),
                                }),
                                /*#__PURE__*/ _jsxs("div", {
                                  className: "framer-15u10f6",
                                  children: [
                                    /*#__PURE__*/ _jsx("div", {
                                      className: "framer-1641fh2",
                                      children: /*#__PURE__*/ _jsx(RichText, {
                                        __fromCanvasComponent: true,
                                        children: /*#__PURE__*/ _jsx(
                                          React.Fragment,
                                          {
                                            children: /*#__PURE__*/ _jsx("p", {
                                              style: {
                                                "--font-selector":
                                                  "R0Y7TWFucm9wZS1yZWd1bGFy",
                                                "--framer-font-family":
                                                  '"Manrope", "Manrope Placeholder", sans-serif',
                                                "--framer-font-size": "15px",
                                                "--framer-letter-spacing":
                                                  "-0.03em",
                                                "--framer-text-color":
                                                  "rgb(28, 28, 28)",
                                              },
                                              children: /*#__PURE__*/ _jsx(
                                                Link,
                                                {
                                                  href: {
                                                    webPageId: "HR6aM93Mr",
                                                  },
                                                  motionChild: true,
                                                  nodeId: "CaHYzL5HR",
                                                  openInNewTab: false,
                                                  relValues: [],
                                                  scopeId: "pHRKi0e8z",
                                                  smoothScroll: false,
                                                  children: /*#__PURE__*/ _jsx(
                                                    motion.a,
                                                    {
                                                      className:
                                                        "framer-styles-preset-kmt2jv",
                                                      "data-styles-preset":
                                                        "bqzoPsKqs",
                                                      children: "About Us",
                                                    }
                                                  ),
                                                }
                                              ),
                                            }),
                                          }
                                        ),
                                        className: "framer-1lgxw97",
                                        "data-framer-name":
                                          "Need Help? WhatsApp Us",
                                        fonts: ["GF;Manrope-regular"],
                                        verticalAlignment: "top",
                                        withExternalLayout: true,
                                      }),
                                    }),
                                    /*#__PURE__*/ _jsx("div", {
                                      className: "framer-f68p68",
                                      children: /*#__PURE__*/ _jsx(RichText, {
                                        __fromCanvasComponent: true,
                                        children: /*#__PURE__*/ _jsx(
                                          React.Fragment,
                                          {
                                            children: /*#__PURE__*/ _jsx("p", {
                                              style: {
                                                "--font-selector":
                                                  "R0Y7TWFucm9wZS1yZWd1bGFy",
                                                "--framer-font-family":
                                                  '"Manrope", "Manrope Placeholder", sans-serif',
                                                "--framer-font-size": "15px",
                                                "--framer-letter-spacing":
                                                  "-0.03em",
                                                "--framer-text-color":
                                                  "rgb(28, 28, 28)",
                                              },
                                              children: /*#__PURE__*/ _jsx(
                                                Link,
                                                {
                                                  href: {
                                                    webPageId: "FEC8Goujq",
                                                  },
                                                  motionChild: true,
                                                  nodeId: "LCcwdtai7",
                                                  openInNewTab: false,
                                                  relValues: [],
                                                  scopeId: "pHRKi0e8z",
                                                  smoothScroll: false,
                                                  children: /*#__PURE__*/ _jsx(
                                                    motion.a,
                                                    {
                                                      className:
                                                        "framer-styles-preset-kmt2jv",
                                                      "data-styles-preset":
                                                        "bqzoPsKqs",
                                                      children: "Contact us",
                                                    }
                                                  ),
                                                }
                                              ),
                                            }),
                                          }
                                        ),
                                        className: "framer-1nhps8v",
                                        "data-framer-name":
                                          "Need Help? WhatsApp Us",
                                        fonts: ["GF;Manrope-regular"],
                                        verticalAlignment: "top",
                                        withExternalLayout: true,
                                      }),
                                    }),
                                    /*#__PURE__*/ _jsx("div", {
                                      className: "framer-1y78ikv",
                                      children: /*#__PURE__*/ _jsx(RichText, {
                                        __fromCanvasComponent: true,
                                        children: /*#__PURE__*/ _jsx(
                                          React.Fragment,
                                          {
                                            children: /*#__PURE__*/ _jsx("p", {
                                              style: {
                                                "--font-selector":
                                                  "R0Y7TWFucm9wZS1yZWd1bGFy",
                                                "--framer-font-family":
                                                  '"Manrope", "Manrope Placeholder", sans-serif',
                                                "--framer-font-size": "15px",
                                                "--framer-letter-spacing":
                                                  "-0.03em",
                                                "--framer-text-color":
                                                  "rgb(28, 28, 28)",
                                              },
                                              children: /*#__PURE__*/ _jsx(
                                                Link,
                                                {
                                                  href: {
                                                    webPageId: "ZA56ODscC",
                                                  },
                                                  motionChild: true,
                                                  nodeId: "PmfrHxCv_",
                                                  openInNewTab: false,
                                                  relValues: [],
                                                  scopeId: "pHRKi0e8z",
                                                  smoothScroll: false,
                                                  children: /*#__PURE__*/ _jsx(
                                                    motion.a,
                                                    {
                                                      className:
                                                        "framer-styles-preset-kmt2jv",
                                                      "data-styles-preset":
                                                        "bqzoPsKqs",
                                                      children:
                                                        "Privacy Policy",
                                                    }
                                                  ),
                                                }
                                              ),
                                            }),
                                          }
                                        ),
                                        className: "framer-90jfwl",
                                        "data-framer-name":
                                          "Need Help? WhatsApp Us",
                                        fonts: ["GF;Manrope-regular"],
                                        verticalAlignment: "top",
                                        withExternalLayout: true,
                                      }),
                                    }),
                                    /*#__PURE__*/ _jsx("div", {
                                      className: "framer-ialscl",
                                      children: /*#__PURE__*/ _jsx(RichText, {
                                        __fromCanvasComponent: true,
                                        children: /*#__PURE__*/ _jsx(
                                          React.Fragment,
                                          {
                                            children: /*#__PURE__*/ _jsx("p", {
                                              style: {
                                                "--font-selector":
                                                  "R0Y7TWFucm9wZS1yZWd1bGFy",
                                                "--framer-font-family":
                                                  '"Manrope", "Manrope Placeholder", sans-serif',
                                                "--framer-font-size": "15px",
                                                "--framer-letter-spacing":
                                                  "-0.03em",
                                                "--framer-text-color":
                                                  "rgb(28, 28, 28)",
                                              },
                                              children: /*#__PURE__*/ _jsx(
                                                Link,
                                                {
                                                  href: {
                                                    webPageId: "CiiiQJ7Ve",
                                                  },
                                                  motionChild: true,
                                                  nodeId: "N3N6G_NEr",
                                                  openInNewTab: false,
                                                  relValues: [],
                                                  scopeId: "pHRKi0e8z",
                                                  smoothScroll: false,
                                                  children: /*#__PURE__*/ _jsx(
                                                    motion.a,
                                                    {
                                                      className:
                                                        "framer-styles-preset-kmt2jv",
                                                      "data-styles-preset":
                                                        "bqzoPsKqs",
                                                      children: "Refund Policy",
                                                    }
                                                  ),
                                                }
                                              ),
                                            }),
                                          }
                                        ),
                                        className: "framer-zyrpz3",
                                        "data-framer-name":
                                          "Need Help? WhatsApp Us",
                                        fonts: ["GF;Manrope-regular"],
                                        verticalAlignment: "top",
                                        withExternalLayout: true,
                                      }),
                                    }),
                                    /*#__PURE__*/ _jsx("div", {
                                      className: "framer-1jgu37o",
                                      children: /*#__PURE__*/ _jsx(RichText, {
                                        __fromCanvasComponent: true,
                                        children: /*#__PURE__*/ _jsx(
                                          React.Fragment,
                                          {
                                            children: /*#__PURE__*/ _jsx("p", {
                                              style: {
                                                "--font-selector":
                                                  "R0Y7TWFucm9wZS1yZWd1bGFy",
                                                "--framer-font-family":
                                                  '"Manrope", "Manrope Placeholder", sans-serif',
                                                "--framer-font-size": "15px",
                                                "--framer-letter-spacing":
                                                  "-0.03em",
                                                "--framer-text-color":
                                                  "rgb(28, 28, 28)",
                                              },
                                              children: /*#__PURE__*/ _jsx(
                                                Link,
                                                {
                                                  href: {
                                                    webPageId: "yWsprztqQ",
                                                  },
                                                  motionChild: true,
                                                  nodeId: "N_K5Kzfhh",
                                                  openInNewTab: false,
                                                  relValues: [],
                                                  scopeId: "pHRKi0e8z",
                                                  smoothScroll: false,
                                                  children: /*#__PURE__*/ _jsx(
                                                    motion.a,
                                                    {
                                                      className:
                                                        "framer-styles-preset-kmt2jv",
                                                      "data-styles-preset":
                                                        "bqzoPsKqs",
                                                      children: "Terms",
                                                    }
                                                  ),
                                                }
                                              ),
                                            }),
                                          }
                                        ),
                                        className: "framer-nmny92",
                                        "data-framer-name":
                                          "Need Help? WhatsApp Us",
                                        fonts: ["GF;Manrope-regular"],
                                        verticalAlignment: "top",
                                        withExternalLayout: true,
                                      }),
                                    }),
                                    isDisplayed() &&
                                      /*#__PURE__*/ _jsx("div", {
                                        className:
                                          "framer-du0gvk hidden-1k1qxhe",
                                      }),
                                  ],
                                }),
                              ],
                            }),
                          }),
                        ],
                      }),
                    }),
                    /*#__PURE__*/ _jsx("div", {
                      className: "framer-1voij2w",
                      "data-border": true,
                      "data-framer-name": "Footer - Right Side",
                      children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                        breakpoint: baseVariant,
                        overrides: {
                          C71cKSVP5: {
                            height: 462,
                            width: "max(min(100vw - 60px, 1500px), 1px)",
                          },
                        },
                        children: /*#__PURE__*/ _jsx(
                          ComponentViewportProvider,
                          {
                            height: 263,
                            width:
                              "max(max(min(100vw - 60px, 1500px), 377px), 1px)",
                            children: /*#__PURE__*/ _jsx(Container, {
                              className: "framer-1avycat-container",
                              nodeId: "qDKoBYo1e",
                              rendersWithMotion: true,
                              scopeId: "pHRKi0e8z",
                              children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                                breakpoint: baseVariant,
                                overrides: {
                                  C71cKSVP5: {
                                    style: { height: "100%", width: "100%" },
                                    variant: "Av5QcKBD4",
                                  },
                                },
                                children: /*#__PURE__*/ _jsx(
                                  DiscountButtonWithoutRightClick1avycatWithMappedReactProps1f51p88,
                                  {
                                    height: "100%",
                                    id: "qDKoBYo1e",
                                    layoutId: "qDKoBYo1e",
                                    style: { width: "100%" },
                                    variant: "FvMMfTZpN",
                                    width: "100%",
                                  }
                                ),
                              }),
                            }),
                          }
                        ),
                      }),
                    }),
                  ],
                }),
                /*#__PURE__*/ _jsx(PropertyOverrides, {
                  breakpoint: baseVariant,
                  overrides: { C71cKSVP5: { height: 74 } },
                  children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 92,
                    width: "min(100vw - 60px, 1500px)",
                    children: /*#__PURE__*/ _jsx(Container, {
                      className: "framer-54qdc2-container",
                      nodeId: "i4njsXJXQ",
                      scopeId: "pHRKi0e8z",
                      children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                        breakpoint: baseVariant,
                        overrides: {
                          C71cKSVP5: {
                            style: {
                              height: "100%",
                              maxWidth: "100%",
                              width: "100%",
                            },
                            variant: "T5sy80Cd3",
                          },
                        },
                        children: /*#__PURE__*/ _jsx(NavigationBar, {
                          height: "100%",
                          id: "i4njsXJXQ",
                          layoutId: "i4njsXJXQ",
                          style: { maxWidth: "100%", width: "100%" },
                          variant: "T0ybRMQG9",
                          width: "100%",
                        }),
                      }),
                    }),
                  }),
                }),
              ],
            }),
          ],
        }),
        /*#__PURE__*/ _jsx("div", { id: "template-overlay" }),
      ],
    }),
  });
});
const css = (target) => {
  const isStaticRenderer =
    target === RenderTarget.canvas || target === RenderTarget.export;
  if (!isStaticRenderer) {
    return [
      ...rules,
      ...breakpointKeys.map((key) => {
        const query = mediaQueries[key];
        return `@media ${query} { ${breakpointRules[key].join(" ")} }`;
      }),
    ];
  }
  return [
    ...rules,
    ...breakpointKeys.flatMap((key) => {
      const selector = selectors[key];
      return breakpointRules[key].map((rule) => `${selector} {${rule}}`);
    }),
  ];
};
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 1000
 * @framerIntrinsicWidth 1094
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"lJnlU637I":{"layout":["fixed","fixed"]},"C71cKSVP5":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerHitTargets {"iOqY39SDY":[".framer-18106e7"],"lJnlU637I":[".framer-18106e7"],"C71cKSVP5":[".framer-18106e7"]}
 * @framerBreakpoints {"iOqY39SDY":{"min":1094,"canvasClassName":"framer-1e77eq1-override","minHeight":1000,"name":"Desktop","width":1094,"rootFontSize":16},"lJnlU637I":{"min":810,"max":1093,"canvasClassName":"framer-32ruxk-override","minHeight":1000,"viewportHeight":779,"name":"Tablet","width":810,"rootFontSize":16},"C71cKSVP5":{"max":809,"canvasClassName":"framer-1k1qxhe-override","minHeight":1415,"viewportHeight":647,"name":"Phone","width":396,"rootFontSize":16}}
 * @framerDefaultVariant iOqY39SDY
 * @framerLayoutTemplate true
 */ const FramerpHRKi0e8z = withCSS(Component, css, "framer-DR6fM");
export default FramerpHRKi0e8z;
FramerpHRKi0e8z.displayName = "Footer";
FramerpHRKi0e8z.defaultProps = { height: 1e3, width: 1094 };
addFonts(
  FramerpHRKi0e8z,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Manrope",
          source: "google",
          style: "normal",
          uiFamilyName: "Manrope",
          url: "https://fonts.gstatic.com/s/manrope/v20/xn7_YHE41ni1AdIRqAuZuw1Bx9mbZk79FO_A87jxeN7B.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Manrope",
          source: "google",
          style: "normal",
          uiFamilyName: "Manrope",
          url: "https://fonts.gstatic.com/s/manrope/v20/xn7_YHE41ni1AdIRqAuZuw1Bx9mbZk4aE-_A87jxeN7B.woff2",
          weight: "700",
        },
      ],
    },
    ...DiscountButtonFonts,
    ...NavigationBarFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerpHRKi0e8z",
      slots: [],
      annotations: {
        framerBreakpoints:
          '{"iOqY39SDY":{"min":1094,"canvasClassName":"framer-1e77eq1-override","minHeight":1000,"name":"Desktop","width":1094,"rootFontSize":16},"lJnlU637I":{"min":810,"max":1093,"canvasClassName":"framer-32ruxk-override","minHeight":1000,"viewportHeight":779,"name":"Tablet","width":810,"rootFontSize":16},"C71cKSVP5":{"max":809,"canvasClassName":"framer-1k1qxhe-override","minHeight":1415,"viewportHeight":647,"name":"Phone","width":396,"rootFontSize":16}}',
        framerDefaultVariant: "iOqY39SDY",
        framerColorSyntax: "true",
        framerIntrinsicHeight: "1000",
        framerAutoSizeImages: "true",
        framerDisplayContentsDiv: "false",
        framerImmutableVariables: "true",
        framerContractVersion: "1",
        framerLayoutTemplate: "true",
        framerHitTargets:
          '{"iOqY39SDY":[".framer-18106e7"],"lJnlU637I":[".framer-18106e7"],"C71cKSVP5":[".framer-18106e7"]}',
        framerIntrinsicWidth: "1094",
        framerComponentViewportWidth: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"lJnlU637I":{"layout":["fixed","fixed"]},"C71cKSVP5":{"layout":["fixed","fixed"]}}}',
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
