// Generated by Framer (6bbae76)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const cycleOrder = ["A7oG51jV2", "DoRZs8Vt_"];
const serializationHash = "framer-IOcQc";
const variantClassNames = {
  A7oG51jV2: "framer-v-hw73z3",
  DoRZs8Vt_: "framer-v-ih2d53",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const CD_FFHPDY = undefined;
const IYD7eMWNf = undefined;
const mycvmc0lT = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  "Desktop + tablet": "A7oG51jV2",
  Phone: "DoRZs8Vt_",
};
const getProps = ({
  blessingOf,
  grandparents,
  height,
  id,
  parents,
  width,
  ...props
}) => {
  return {
    ...props,
    CD_FFHPDY:
      blessingOf ?? props.CD_FFHPDY ?? "With the heavenly blessings of ",
    IYD7eMWNf:
      grandparents ?? props.IYD7eMWNf ?? "Smt. Sita Devi & Sm. Kamal Mittal",
    mycvmc0lT: parents ?? props.mycvmc0lT ?? "Mrs. Lata & Mr. Kishore Kapoor",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "A7oG51jV2",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    CD_FFHPDY,
    IYD7eMWNf,
    mycvmc0lT,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "A7oG51jV2",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-hw73z3",
            className,
            classNames
          ),
          "data-framer-name": "Desktop + tablet",
          layoutDependency: layoutDependency,
          layoutId: "A7oG51jV2",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            { DoRZs8Vt_: { "data-framer-name": "Phone" } },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.p, {
                  style: {
                    "--font-selector":
                      "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                    "--framer-font-family":
                      '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                    "--framer-font-size": "30px",
                    "--framer-letter-spacing": "-0.03em",
                    "--framer-line-height": "100%",
                    "--framer-text-alignment": "center",
                    "--framer-text-color":
                      "var(--extracted-r6o4lv, rgb(230, 210, 255))",
                  },
                  children: "With the heavenly blessings of ",
                }),
              }),
              className: "framer-12vqqeu",
              "data-framer-name":
                "With the heavenly blessings of Smt. Sita Devi & Sm. Om Puri",
              fonts: ["GF;Cormorant Upright-regular"],
              layoutDependency: layoutDependency,
              layoutId: "TBEoHjQ8e",
              style: {
                "--extracted-r6o4lv": "rgb(230, 210, 255)",
                "--framer-paragraph-spacing": "0px",
              },
              text: CD_FFHPDY,
              verticalAlignment: "top",
              withExternalLayout: true,
              ...addPropertyOverrides(
                {
                  DoRZs8Vt_: {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector":
                            "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                          "--framer-font-family":
                            '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                          "--framer-font-size": "20px",
                          "--framer-letter-spacing": "-0.03em",
                          "--framer-line-height": "100%",
                          "--framer-text-alignment": "center",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, rgb(230, 210, 255))",
                        },
                        children: "With the heavenly blessings of ",
                      }),
                    }),
                  },
                },
                baseVariant,
                gestureVariant
              ),
            }),
            /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.p, {
                  style: {
                    "--font-selector":
                      "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                    "--framer-font-family":
                      '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                    "--framer-font-size": "30px",
                    "--framer-letter-spacing": "-0.03em",
                    "--framer-line-height": "100%",
                    "--framer-text-alignment": "center",
                    "--framer-text-color":
                      "var(--extracted-r6o4lv, rgb(230, 210, 255))",
                  },
                  children: "Smt. Sita Devi & Sm. Kamal Mittal",
                }),
              }),
              className: "framer-1bbvm6z",
              "data-framer-name":
                "With the heavenly blessings of Smt. Sita Devi & Sm. Om Puri",
              fonts: ["GF;Cormorant Upright-regular"],
              layoutDependency: layoutDependency,
              layoutId: "iOW0dIy1R",
              style: {
                "--extracted-r6o4lv": "rgb(230, 210, 255)",
                "--framer-paragraph-spacing": "0px",
              },
              text: IYD7eMWNf,
              verticalAlignment: "top",
              withExternalLayout: true,
              ...addPropertyOverrides(
                {
                  DoRZs8Vt_: {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector":
                            "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                          "--framer-font-family":
                            '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                          "--framer-font-size": "20px",
                          "--framer-letter-spacing": "-0.03em",
                          "--framer-line-height": "100%",
                          "--framer-text-alignment": "center",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, rgb(230, 210, 255))",
                        },
                        children: "Smt. Sita Devi & Sm. Kamal Mittal",
                      }),
                    }),
                  },
                },
                baseVariant,
                gestureVariant
              ),
            }),
            /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.p, {
                  style: {
                    "--font-selector":
                      "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                    "--framer-font-family":
                      '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                    "--framer-font-size": "30px",
                    "--framer-letter-spacing": "-0.03em",
                    "--framer-line-height": "150%",
                    "--framer-text-alignment": "center",
                    "--framer-text-color":
                      "var(--extracted-r6o4lv, rgb(230, 210, 255))",
                  },
                  children: "——",
                }),
              }),
              className: "framer-1tg6hsf",
              "data-framer-name": "and",
              fonts: ["GF;Cormorant Upright-regular"],
              layoutDependency: layoutDependency,
              layoutId: "WK9lzSxL0",
              style: {
                "--extracted-r6o4lv": "rgb(230, 210, 255)",
                "--framer-paragraph-spacing": "0px",
              },
              verticalAlignment: "top",
              withExternalLayout: true,
              ...addPropertyOverrides(
                {
                  DoRZs8Vt_: {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector":
                            "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                          "--framer-font-family":
                            '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                          "--framer-font-size": "20px",
                          "--framer-letter-spacing": "-0.03em",
                          "--framer-line-height": "150%",
                          "--framer-text-alignment": "center",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, rgb(230, 210, 255))",
                        },
                        children: "——",
                      }),
                    }),
                  },
                },
                baseVariant,
                gestureVariant
              ),
            }),
            /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.p, {
                  style: {
                    "--font-selector":
                      "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                    "--framer-font-family":
                      '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                    "--framer-font-size": "30px",
                    "--framer-letter-spacing": "-0.03em",
                    "--framer-line-height": "150%",
                    "--framer-text-alignment": "center",
                    "--framer-text-color":
                      "var(--extracted-r6o4lv, rgb(230, 210, 255))",
                  },
                  children: "Mrs. Lata & Mr. Kishore Kapoor",
                }),
              }),
              className: "framer-1i1bqsu",
              "data-framer-name": "Mrs. Lata & Mr. Kishore Kapoor",
              fonts: ["GF;Cormorant Upright-regular"],
              layoutDependency: layoutDependency,
              layoutId: "DYKoBRj8j",
              style: {
                "--extracted-r6o4lv": "rgb(230, 210, 255)",
                "--framer-paragraph-spacing": "0px",
              },
              text: mycvmc0lT,
              verticalAlignment: "top",
              withExternalLayout: true,
              ...addPropertyOverrides(
                {
                  DoRZs8Vt_: {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector":
                            "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                          "--framer-font-family":
                            '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                          "--framer-font-size": "20px",
                          "--framer-letter-spacing": "-0.03em",
                          "--framer-line-height": "150%",
                          "--framer-text-alignment": "center",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, rgb(230, 210, 255))",
                        },
                        children: "Mrs. Lata & Mr. Kishore Kapoor",
                      }),
                    }),
                  },
                },
                baseVariant,
                gestureVariant
              ),
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-IOcQc.framer-4ntxe6, .framer-IOcQc .framer-4ntxe6 { display: block; }",
  ".framer-IOcQc.framer-hw73z3 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 38px 0px 38px 0px; position: relative; width: 1200px; }",
  ".framer-IOcQc .framer-12vqqeu, .framer-IOcQc .framer-1bbvm6z, .framer-IOcQc .framer-1tg6hsf, .framer-IOcQc .framer-1i1bqsu { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 256
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"DoRZs8Vt_":{"layout":["fixed","auto"]}}}
 * @framerVariables {"CD_FFHPDY":"blessingOf","IYD7eMWNf":"grandparents","mycvmc0lT":"parents"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramersFD5X5Hsy = withCSS(Component, css, "framer-IOcQc");
export default FramersFD5X5Hsy;
FramersFD5X5Hsy.displayName = "Family names 2";
FramersFD5X5Hsy.defaultProps = { height: 256, width: 1200 };
addPropertyControls(FramersFD5X5Hsy, {
  variant: {
    options: ["A7oG51jV2", "DoRZs8Vt_"],
    optionTitles: ["Desktop + tablet", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
  CD_FFHPDY: {
    defaultValue: "With the heavenly blessings of ",
    displayTextArea: true,
    title: "Blessing of",
    type: ControlType.String,
  },
  IYD7eMWNf: {
    defaultValue: "Smt. Sita Devi & Sm. Kamal Mittal",
    description:
      "Enter your grandparent's name above\n\nFind more templates on ",
    displayTextArea: true,
    title: "Grandparents",
    type: ControlType.String,
  },
  mycvmc0lT: {
    defaultValue: "Mrs. Lata & Mr. Kishore Kapoor",
    description:
      "Enter your grandparent's name above\n\nFind more templates on ",
    displayTextArea: true,
    title: "Parents",
    type: ControlType.String,
  },
});
addFonts(
  FramersFD5X5Hsy,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Cormorant Upright",
          source: "google",
          style: "normal",
          uiFamilyName: "Cormorant Upright",
          url: "https://fonts.gstatic.com/s/cormorantupright/v19/VuJrdM3I2Y35poFONtLdafkUCHw1y2vQjjTkeMnz.woff2",
          weight: "400",
        },
      ],
    },
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramersFD5X5Hsy",
      slots: [],
      annotations: {
        framerIntrinsicHeight: "256",
        framerIntrinsicWidth: "1200",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"DoRZs8Vt_":{"layout":["fixed","auto"]}}}',
        framerVariables:
          '{"CD_FFHPDY":"blessingOf","IYD7eMWNf":"grandparents","mycvmc0lT":"parents"}',
        framerAutoSizeImages: "true",
        framerContractVersion: "1",
        framerColorSyntax: "true",
        framerComponentViewportWidth: "true",
        framerDisplayContentsDiv: "false",
        framerImmutableVariables: "true",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./sFD5X5Hsy.map
