// Generated by Framer (569fd08)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  Link,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const cycleOrder = [
  "Ix7kqPHgy",
  "wjaThoAIo",
  "hd85ADDzQ",
  "dEcQWXXsf",
  "hcQUrlITC",
  "RNeBrk15w",
];
const serializationHash = "framer-p7TwT";
const variantClassNames = {
  dEcQWXXsf: "framer-v-1s5qqfe",
  hcQUrlITC: "framer-v-1pjknas",
  hd85ADDzQ: "framer-v-s7k8ck",
  Ix7kqPHgy: "framer-v-1pd453m",
  RNeBrk15w: "framer-v-155jika",
  wjaThoAIo: "framer-v-1wc0dz6",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const Ud5p4AQv5 = undefined;
const p7klC1ZHB = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  "Home-Desktop-Scroll": "hcQUrlITC",
  "Home-Phone-Sroll": "RNeBrk15w",
  "Phone View": "wjaThoAIo",
  "Variant 1": "Ix7kqPHgy",
  "Variant 4": "dEcQWXXsf",
  "White and black": "hd85ADDzQ",
};
const getProps = ({ height, id, link, title, width, ...props }) => {
  return {
    ...props,
    p7klC1ZHB: title ?? props.p7klC1ZHB ?? "Choose a template",
    Ud5p4AQv5: link ?? props.Ud5p4AQv5,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "Ix7kqPHgy",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    p7klC1ZHB,
    Ud5p4AQv5,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "Ix7kqPHgy",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(Link, {
          href: Ud5p4AQv5,
          motionChild: true,
          nodeId: "Ix7kqPHgy",
          openInNewTab: false,
          scopeId: "ve3uyNBsX",
          smoothScroll: true,
          ...addPropertyOverrides(
            {
              hcQUrlITC: {
                href: { hash: ":eA5YfGPOn", webPageId: "NU5gDu6ml" },
              },
              RNeBrk15w: {
                href: { hash: ":eA5YfGPOn", webPageId: "NU5gDu6ml" },
              },
            },
            baseVariant,
            gestureVariant
          ),
          children: /*#__PURE__*/ _jsx(motion.a, {
            ...restProps,
            ...gestureHandlers,
            className: `${cx(
              scopingClassNames,
              "framer-1pd453m",
              className,
              classNames
            )} framer-1e4g727`,
            "data-framer-name": "Variant 1",
            layoutDependency: layoutDependency,
            layoutId: "Ix7kqPHgy",
            ref: refBinding,
            style: {
              backgroundColor: "rgb(0, 0, 0)",
              borderBottomLeftRadius: 60,
              borderBottomRightRadius: 60,
              borderTopLeftRadius: 60,
              borderTopRightRadius: 60,
              ...style,
            },
            variants: { hd85ADDzQ: { backgroundColor: "rgb(255, 255, 255)" } },
            ...addPropertyOverrides(
              {
                dEcQWXXsf: { "data-framer-name": "Variant 4" },
                hcQUrlITC: { "data-framer-name": "Home-Desktop-Scroll" },
                hd85ADDzQ: { "data-framer-name": "White and black" },
                RNeBrk15w: { "data-framer-name": "Home-Phone-Sroll" },
                wjaThoAIo: { "data-framer-name": "Phone View" },
              },
              baseVariant,
              gestureVariant
            ),
            children: /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.p, {
                  style: {
                    "--font-selector": "R0Y7TWFucm9wZS02MDA=",
                    "--framer-font-family":
                      '"Manrope", "Manrope Placeholder", sans-serif',
                    "--framer-font-size": "14px",
                    "--framer-font-weight": "600",
                    "--framer-letter-spacing": "-0.03em",
                    "--framer-text-alignment": "center",
                    "--framer-text-color":
                      "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                  },
                  children: "Choose a template",
                }),
              }),
              className: "framer-hxeya6",
              "data-framer-name": "See Wedding Templates",
              fonts: ["GF;Manrope-600"],
              layoutDependency: layoutDependency,
              layoutId: "YEtpM_bvL",
              style: {
                "--extracted-r6o4lv": "rgb(255, 255, 255)",
                "--framer-paragraph-spacing": "0px",
              },
              text: p7klC1ZHB,
              verticalAlignment: "top",
              withExternalLayout: true,
              ...addPropertyOverrides(
                {
                  dEcQWXXsf: {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector": "R0Y7TWFucm9wZS02MDA=",
                          "--framer-font-family":
                            '"Manrope", "Manrope Placeholder", sans-serif',
                          "--framer-font-size": "12px",
                          "--framer-font-weight": "600",
                          "--framer-letter-spacing": "-0.03em",
                          "--framer-text-alignment": "center",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                        },
                        children: "Choose a template",
                      }),
                    }),
                  },
                  hd85ADDzQ: {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector": "R0Y7TWFucm9wZS03MDA=",
                          "--framer-font-family":
                            '"Manrope", "Manrope Placeholder", sans-serif',
                          "--framer-font-size": "14px",
                          "--framer-font-weight": "700",
                          "--framer-letter-spacing": "-0.03em",
                          "--framer-text-alignment": "center",
                        },
                        children: "Choose a template",
                      }),
                    }),
                    fonts: ["GF;Manrope-700"],
                  },
                },
                baseVariant,
                gestureVariant
              ),
            }),
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-p7TwT.framer-1e4g727, .framer-p7TwT .framer-1e4g727 { display: block; }",
  ".framer-p7TwT.framer-1pd453m { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 15px 30px 15px 30px; position: relative; text-decoration: none; width: min-content; }",
  ".framer-p7TwT .framer-hxeya6 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-p7TwT.framer-v-1wc0dz6.framer-1pd453m, .framer-p7TwT.framer-v-155jika.framer-1pd453m { width: 240px; }",
  ".framer-p7TwT.framer-v-1s5qqfe.framer-1pd453m { padding: 12px 25px 12px 25px; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 47
 * @framerIntrinsicWidth 178
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"wjaThoAIo":{"layout":["fixed","auto"]},"hd85ADDzQ":{"layout":["auto","auto"]},"dEcQWXXsf":{"layout":["auto","auto"]},"hcQUrlITC":{"layout":["auto","auto"]},"RNeBrk15w":{"layout":["fixed","auto"]}}}
 * @framerVariables {"p7klC1ZHB":"title","Ud5p4AQv5":"link"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const Framerve3uyNBsX = withCSS(Component, css, "framer-p7TwT");
export default Framerve3uyNBsX;
Framerve3uyNBsX.displayName = "Main CTA";
Framerve3uyNBsX.defaultProps = { height: 47, width: 178 };
addPropertyControls(Framerve3uyNBsX, {
  variant: {
    options: [
      "Ix7kqPHgy",
      "wjaThoAIo",
      "hd85ADDzQ",
      "dEcQWXXsf",
      "hcQUrlITC",
      "RNeBrk15w",
    ],
    optionTitles: [
      "Variant 1",
      "Phone View",
      "White and black",
      "Variant 4",
      "Home-Desktop-Scroll",
      "Home-Phone-Sroll",
    ],
    title: "Variant",
    type: ControlType.Enum,
  },
  p7klC1ZHB: {
    defaultValue: "Choose a template",
    displayTextArea: false,
    title: "Title",
    type: ControlType.String,
  },
  Ud5p4AQv5: { title: "Link", type: ControlType.Link },
});
addFonts(
  Framerve3uyNBsX,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Manrope",
          source: "google",
          style: "normal",
          uiFamilyName: "Manrope",
          url: "https://fonts.gstatic.com/s/manrope/v20/xn7_YHE41ni1AdIRqAuZuw1Bx9mbZk4jE-_A87jxeN7B.woff2",
          weight: "600",
        },
        {
          cssFamilyName: "Manrope",
          source: "google",
          style: "normal",
          uiFamilyName: "Manrope",
          url: "https://fonts.gstatic.com/s/manrope/v20/xn7_YHE41ni1AdIRqAuZuw1Bx9mbZk4aE-_A87jxeN7B.woff2",
          weight: "700",
        },
      ],
    },
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "Framerve3uyNBsX",
      slots: [],
      annotations: {
        framerContractVersion: "1",
        framerImmutableVariables: "true",
        framerAutoSizeImages: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"wjaThoAIo":{"layout":["fixed","auto"]},"hd85ADDzQ":{"layout":["auto","auto"]},"dEcQWXXsf":{"layout":["auto","auto"]},"hcQUrlITC":{"layout":["auto","auto"]},"RNeBrk15w":{"layout":["fixed","auto"]}}}',
        framerIntrinsicHeight: "47",
        framerComponentViewportWidth: "true",
        framerDisplayContentsDiv: "false",
        framerIntrinsicWidth: "178",
        framerColorSyntax: "true",
        framerVariables: '{"p7klC1ZHB":"title","Ud5p4AQv5":"link"}',
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./ve3uyNBsX.map
